import { expect, test, type Page } from '@playwright/test'
import { addCalendarPlan, manageRun, returnCalendar, runPage, stagePlan } from './calendar-actions'

test.setTimeout(90000)
const b = (p: Page, name: string) => p.getByRole('button', { name, exact: true })
const f = (p: Page, name: string) => p.getByLabel(name, { exact: true })
async function rows(page: Page, store: string) {
  return page.evaluate(async (store) => { const db = await new Promise<IDBDatabase>((resolve, reject) => { const r = indexedDB.open('boros'); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error) }); try { return await new Promise<any[]>((resolve, reject) => { const r = db.transaction(store).objectStore(store).getAll(); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error) }) } finally { db.close() } }, store)
}
async function setup(page: Page, names = ['Alpha', 'Beta']) {
  await page.clock.setFixedTime(new Date('2026-10-08T12:00:00Z')); await page.goto('./'); await expect(b(page, 'Calendar')).toBeVisible(); if (await b(page, 'Understood').isVisible()) await b(page, 'Understood').click()
  for (const name of names) { await b(page, 'Create').click(); await b(page, 'Import AI Output').click(); await f(page, 'AI output JSON').fill(JSON.stringify({ schemaVersion: 3, kind: 'plan', plan: { name, durationWeeks: 3, trainingDaysPerWeek: 2, days: ['Upper', 'Lower'].map((name) => ({ name, exercises: [{ name: 'Press', sets: [{ reps: { min: 5, max: 5 } }] }] })) } })); await b(page, 'Validate and preview').click(); await b(page, 'Save plan').click(); await expect(page.getByRole('article', { name: `Plan ${name}` })).toBeVisible() }
  await b(page, 'Calendar').click(); await f(page, 'Calendar date').fill('2026-10-05')
}

test('blank mapping validation, staging/edit/leave, cancel without warnings or writes, shared subtitle and active exclusion', async ({ page }) => {
  await setup(page); const address = page.url(), dialogs: string[] = []; page.on('dialog', async d => { dialogs.push(d.type()); await d.dismiss() })
  await b(page, 'Add Plan').click(); await expect(page.getByRole('heading', { level: 1 })).toHaveText('Add Plan'); await expect(b(page, 'Save')).toBeDisabled(); await expect(page.getByLabel('Show archived plans')).toHaveCount(0)
  const card = page.getByRole('article', { name: 'Plan Alpha' }); await expect(card).toContainText('3 weeks · 2 training days · 5 rest days'); await card.getByRole('button').click()
  await expect(f(page, 'Upper weekday')).toHaveValue(''); await page.getByRole('dialog').getByRole('button', { name: 'Save', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('Choose a weekday')
  await f(page, 'Upper weekday').selectOption('0'); await f(page, 'Lower weekday').selectOption('0'); await page.getByRole('dialog').getByRole('button', { name: 'Save', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('distinct weekday'); await expect(f(page, 'Upper weekday')).toHaveValue('0')
  await f(page, 'Lower weekday').selectOption('4'); await page.getByRole('dialog').getByRole('button', { name: 'Save', exact: true }).click(); expect(await rows(page, 'schedules')).toHaveLength(0); await expect(card).toContainText('Scheduled')
  await card.getByRole('button').click(); await b(page, 'Edit').click(); await expect(f(page, 'Lower weekday')).toHaveValue('4'); await f(page, 'Lower weekday').selectOption('6'); await page.getByRole('dialog').getByRole('button', { name: 'Cancel', exact: true }).click()
  await card.getByRole('button').click(); await b(page, 'Edit').click(); await expect(f(page, 'Lower weekday')).toHaveValue('4'); await page.keyboard.press('Escape'); await card.getByRole('button').click(); await b(page, 'Leave').click(); await expect(b(page, 'Save')).toBeDisabled()
  await stagePlan(page, 'Alpha'); await b(page, 'Cancel').click(); await expect(b(page, 'Add Plan')).toBeFocused(); expect(dialogs).toEqual([]); expect(await rows(page, 'schedules')).toHaveLength(0); expect(page.url()).toBe(address)
  await b(page, 'Train').click(); await b(page, 'Add Plan').click(); await page.getByRole('dialog').getByRole('article', { name: 'Plan Alpha' }).getByRole('button').click(); await b(page, 'Calendar').click(); await b(page, 'Add Plan').click(); await expect(card).toHaveCount(0); await expect(page.getByRole('article', { name: 'Plan Beta' })).toBeVisible(); await b(page, 'Cancel').click()
  await b(page, 'Create').click(); await expect(card).toContainText('3 weeks · 2 training days · 5 rest days')
})

test('atomic batch write failure keeps staging and unload guard; retry saves all once and reload persists', async ({ page }) => {
  await setup(page); await b(page, 'Add Plan').click(); await stagePlan(page, 'Alpha'); await stagePlan(page, 'Beta', [2, 4])
  await page.evaluate(() => { const add = IDBObjectStore.prototype.add; let n = 0; (window as any).restoreWrites = () => { IDBObjectStore.prototype.add = add }; IDBObjectStore.prototype.add = function (...args) { if (this.name === 'schedules' && ++n === 2) throw new DOMException('Second plan disk full', 'QuotaExceededError'); return add.apply(this, args) } })
  await b(page, 'Save').click(); await expect(page.getByRole('alert')).toContainText('Second plan disk full'); expect(await rows(page, 'schedules')).toHaveLength(0); await expect(page.locator('.add-plan-list .status-pill')).toHaveCount(2)
  const unload = page.waitForEvent('dialog'); await page.evaluate(() => { setTimeout(() => location.reload(), 0) }); const warning = await unload; expect(warning.type()).toBe('beforeunload'); await warning.dismiss()
  await page.evaluate(() => (window as any).restoreWrites()); await b(page, 'Save').click(); await expect(b(page, 'Calendar menu')).toBeVisible(); const saved = await rows(page, 'schedules'); expect(saved).toHaveLength(2)
  await page.reload(); await expect(b(page, 'Calendar menu')).toBeVisible(); expect(await rows(page, 'schedules')).toEqual(saved)
  await b(page, 'Settings').click(); await f(page, 'New profile name').fill('Other'); await b(page, 'Create profile').click(); await b(page, 'Calendar').click(); await runPage(page); await expect(page.getByText('No current plans.', { exact: true })).toBeVisible()
})

test('competing staging tabs reject duplicate activation without partial saves or losing pending configuration', async ({ page, context }) => {
  await setup(page); await b(page, 'Add Plan').click(); await stagePlan(page, 'Alpha'); await stagePlan(page, 'Beta')
  const peer = await context.newPage(); await peer.clock.setFixedTime(new Date('2026-10-08T12:00:00Z')); await peer.goto('./'); await b(peer, 'Train').click(); await b(peer, 'Add Plan').click(); await peer.getByRole('dialog').getByRole('article', { name: 'Plan Alpha' }).getByRole('button').click()
  await b(page, 'Save').click(); await expect(page.getByRole('alert')).toContainText('active run'); expect(await rows(page, 'schedules')).toHaveLength(1); await expect(page.locator('.add-plan-list .status-pill')).toHaveCount(2)
  await page.getByRole('article', { name: 'Plan Alpha' }).getByRole('button').click(); await b(page, 'Leave').click(); await b(page, 'Save').click(); await expect(b(page, 'Calendar menu')).toBeVisible(); expect(await rows(page, 'schedules')).toHaveLength(2); await peer.close()
})

test('existing unscheduled run Edit retains ID, reset/end/hide/unhide/delete scope and reload persistence', async ({ page }) => {
  await setup(page, ['Alpha']); await b(page, 'Train').click(); await b(page, 'Add Plan').click(); await page.getByRole('dialog').getByRole('article', { name: 'Plan Alpha' }).getByRole('button').click(); const original = (await rows(page, 'schedules'))[0]
  await b(page, 'Calendar').click(); await manageRun(page, 'Edit'); await expect(f(page, 'Upper weekday')).toHaveValue(''); await f(page, 'Upper weekday').selectOption('0'); await f(page, 'Lower weekday').selectOption('4'); await b(page, 'Save').click(); await expect(page.getByRole('heading', { level: 1 })).toHaveText('Current Plans')
  await expect(page.getByRole('article', { name: 'Run Alpha' })).toContainText('Scheduled'); const saved = (await rows(page, 'schedules'))[0]; expect(saved.id).toBe(original.id); expect(saved.startWeek).toBe(original.startWeek)
  await returnCalendar(page); await b(page, 'Week').click(); await f(page, 'Calendar date').fill('2026-10-05'); await page.getByRole('region', { name: '2026-10-05', exact: true }).locator('.calendar-event').click(); await f(page, 'Press set 1 Weight (kg)').fill('25'); await f(page, 'Press set 1 Repetitions').fill('5'); await b(page, 'Save').click(); await expect(page.getByRole('region', { name: 'Saved session details' })).toBeVisible(); await b(page, 'Calendar').click(); await runPage(page); await expect(page.getByRole('img', { name: 'Completed: 1 of 6 planned days, 17%' })).toBeVisible()
  await manageRun(page, 'Reset'); const reset = page.getByRole('dialog', { name: 'Reset Plan?' }); await expect(reset).toContainText('Resetting this plan will erase all progress for this plan and restart you from the first week.'); await expect(reset.getByRole('button', { name: 'Reset', exact: true })).toHaveClass(/destructive/); await reset.getByRole('button', { name: 'Reset', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0); expect((await rows(page, 'schedules'))[0].id).toBe(original.id)
  expect(await rows(page, 'sessions')).toHaveLength(0); expect(await rows(page, 'drafts')).toHaveLength(0); await expect(page.getByRole('img', { name: 'Completed: 0 of 6 planned days, 0%' })).toBeVisible()
  await manageRun(page, 'End'); const end = page.getByRole('dialog', { name: 'Ending a Plan?' }); await expect(end).toContainText('Your saved progress will remain, but you cannot continue this plan.'); await end.getByRole('button', { name: 'Cancel', exact: true }).click(); await expect(page.getByRole('dialog').getByRole('button', { name: 'End', exact: true })).toHaveClass(/destructive/); await b(page, 'End').click(); await end.getByRole('button', { name: 'End', exact: true }).click()
  await returnCalendar(page); await runPage(page, 'Previous Plans'); const card = page.getByRole('article', { name: 'Run Alpha' }); await expect(card).toContainText('Scheduled'); await expect(card).toContainText('05/10/2026 - 08/10/2026'); await card.getByRole('button').click(); await b(page, 'Hide').click(); await expect(card).toHaveCount(0); await expect(page.getByRole('heading', { level: 1, name: 'Previous Plans', exact: true })).toBeFocused()
  await page.reload(); await runPage(page, 'Previous Plans'); await expect(card).toHaveCount(0); await page.getByLabel('Show hidden plans').check(); await card.getByRole('button').click(); await b(page, 'Unhide').click(); await page.getByLabel('Show hidden plans').uncheck(); await expect(card).toBeVisible()
  await card.getByRole('button').click(); await b(page, 'Delete').click(); const deletion = page.getByRole('dialog', { name: 'Delete Plan?' }); await expect(deletion).toContainText('Deleting this plan will delete all results associated with it. This cannot be undone.'); await deletion.getByRole('button', { name: 'Cancel', exact: true }).click(); expect(await rows(page, 'schedules')).toHaveLength(1)
  await b(page, 'Delete').click(); await deletion.getByRole('button', { name: 'Delete', exact: true }).click(); await expect(card).toHaveCount(0); expect(await rows(page, 'schedules')).toHaveLength(0); expect(await rows(page, 'plans')).toHaveLength(1)
})

test('Previous Plans searches and sorts all run types, caps scrolling at five cards and returns Calendar state', async ({ page }) => {
  await setup(page, ['Alpha']); await addCalendarPlan(page, '2026-10-05', 'Alpha')
  await page.evaluate(async () => {
    const db = await new Promise<IDBDatabase>(resolve => { const r = indexedDB.open('boros'); r.onsuccess = () => resolve(r.result) }), runs: any[] = await new Promise(resolve => { const r = db.transaction('schedules').objectStore('schedules').getAll(); r.onsuccess = () => resolve(r.result) })
    await new Promise<void>((resolve, reject) => { const tx = db.transaction('schedules', 'readwrite'); for (let i = 0; i < 12; i++) { const run = structuredClone(runs[0]); run.id = crypto.randomUUID(); run.createdAt = `2026-10-05T00:${String(i).padStart(2, '0')}:00Z`; run.closedAt = '2026-10-08T12:00:00Z'; run.stoppedFrom = '2026-10-08'; run.revisions[0].planName = `History ${String(i).padStart(2, '0')}`; if (i % 2) { run.kind = 'unscheduled'; run.identity = 'program-week' } tx.objectStore('schedules').add(run) } tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error) }); db.close()
  })
  await page.reload(); await b(page, 'Week').click(); await f(page, 'Calendar date').fill('2026-10-12'); await runPage(page, 'Previous Plans'); await expect(page.getByRole('article')).toHaveCount(12); await f(page, 'Sort plans').selectOption('newest'); await expect(page.getByRole('article').first()).toContainText('History 11'); await f(page, 'Sort plans').selectOption('oldest'); await expect(page.getByRole('article').first()).toContainText('History 00'); await f(page, 'Sort plans').selectOption('az'); await expect(page.getByRole('article').first()).toContainText('History 00'); await expect(page.getByRole('article').nth(1)).toContainText('Non-Scheduled')
  await f(page, 'Search plans').fill('History 1'); await expect(page.getByRole('article')).toHaveCount(2); await f(page, 'Sort plans').selectOption('za'); await expect(page.getByRole('article').first()).toContainText('History 11'); await f(page, 'Search plans').fill('')
  await page.setViewportSize({ width: 1440, height: 4000 }); const list = page.locator('.previous-plan-list'); await expect.poll(() => list.evaluate(el => { const first = el.children[0].getBoundingClientRect(), fifth = el.children[4].getBoundingClientRect(); return el.clientHeight <= fifth.bottom - first.top + 9 && el.scrollHeight > el.clientHeight })).toBe(true)
  await page.setViewportSize({ width: 390, height: 844 }); await b(page, 'Cancel').focus(); await page.keyboard.press('Enter'); await expect(b(page, 'Calendar menu')).toBeFocused(); await expect(b(page, 'Week')).toHaveAttribute('aria-pressed', 'true'); await expect(f(page, 'Calendar date')).toHaveValue('2026-10-12')
})

test('calendar backgrounds, Today and selection survive both themes; bounded lists/search/sort and phone/tablet layout', async ({ page }, info) => {
  await setup(page); await page.evaluate(async () => { const db = await new Promise<IDBDatabase>(resolve => { const r = indexedDB.open('boros'); r.onsuccess = () => resolve(r.result) }); const plans: any[] = await new Promise(resolve => { const r = db.transaction('plans').objectStore('plans').getAll(); r.onsuccess = () => resolve(r.result) }); await new Promise<void>((resolve, reject) => { const tx = db.transaction('plans', 'readwrite'); for (let i = 0; i < 30; i++) { const name = `Extra ${String(i).padStart(2, '0')}`; tx.objectStore('plans').add({ ...plans[0], id: crypto.randomUUID(), name, nameKey: name.toLowerCase(), activeNameKey: name.toLowerCase() }) } tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error) }); db.close() })
  for (const theme of ['Dark', 'Light']) {
    await b(page, 'Settings').click(); await b(page, theme).click(); await b(page, 'Calendar').click(); await f(page, 'Calendar date').fill('2026-10-05')
    const colors = await page.evaluate(() => { const root = getComputedStyle(document.documentElement); return { inside: root.getPropertyValue('--surface').trim(), outside: root.getPropertyValue('--bg').trim() } })
    const color = async (selector: string) => page.locator(selector).first().evaluate(el => getComputedStyle(el).backgroundColor)
    expect(await color('.calendar-day:not(.adjacent-month)')).toBe(theme === 'Dark' ? 'rgb(32, 32, 32)' : 'rgb(242, 242, 242)'); expect(await color('.adjacent-month')).toBe(theme === 'Dark' ? 'rgb(0, 0, 0)' : 'rgb(255, 255, 255)'); expect(colors.inside).not.toBe(colors.outside)
    await expect(page.locator('.calendar-day[aria-current="date"]')).toContainText('Today'); await expect(page.locator('.selected-date')).toHaveAttribute('aria-label', '2026-10-05')
    for (const view of ['Day', 'Week']) { await b(page, view).click(); expect(await color('.calendar-day')).toBe(theme === 'Dark' ? 'rgb(32, 32, 32)' : 'rgb(242, 242, 242)') }
    await b(page, 'Add Plan').click(); const list = page.locator('.add-plan-list'); expect(await list.evaluate(el => el.scrollHeight > el.clientHeight)).toBe(true); await f(page, 'Search plans').fill('Extra'); await f(page, 'Sort plans').selectOption('za'); await expect(list.locator('strong').first()).toHaveText('Extra 29'); await f(page, 'Search plans').fill('')
    await expect.poll(async () => { const box = await b(page, 'Cancel').boundingBox(), nav = await page.locator('.main-nav').boundingBox(); return box!.y + box!.height <= nav!.y }).toBe(true)
    await page.screenshot({ path: info.outputPath(`add-plan-${theme}.png`), fullPage: true }); await b(page, 'Cancel').focus(); await page.keyboard.press('Enter')
  }
  for (const width of [768, 320]) { await page.setViewportSize({ width, height: 1024 }); await b(page, 'Add Plan').click(); await page.getByRole('article', { name: 'Plan Alpha' }).getByRole('button').click(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await f(page, 'Lower weekday').focus(); await page.keyboard.press('Escape'); await expect(page.getByRole('article', { name: 'Plan Alpha' }).getByRole('button')).toBeFocused(); await b(page, 'Cancel').click() }
})

test('current-week saved day stays put while pending day moves, future mapping applies and edit Cancel preserves list', async ({ page }) => {
  await setup(page, ['Alpha']); await b(page, 'Week').click(); await addCalendarPlan(page, '2026-10-05', 'Alpha', [0, 2])
  await page.getByRole('region', { name: '2026-10-05', exact: true }).locator('.calendar-event').click(); await f(page, 'Press set 1 Weight (kg)').fill('0'); await f(page, 'Press set 1 Repetitions').fill('5'); await b(page, 'Save').click(); await expect(page.getByRole('region', { name: 'Saved session details' })).toBeVisible()
  await b(page, 'Calendar').click(); await manageRun(page, 'Edit'); await f(page, 'Upper weekday').selectOption('2'); await f(page, 'Lower weekday').selectOption('4'); await b(page, 'Save').click(); await expect(page.getByRole('heading', { level: 1 })).toHaveText('Current Plans'); await expect(page.getByRole('dialog')).toHaveCount(0); await returnCalendar(page)
  await b(page, 'Week').click(); await f(page, 'Calendar date').fill('2026-10-05'); await expect(page.getByRole('region', { name: '2026-10-05', exact: true }).locator('.calendar-event')).toContainText('Completed'); await expect(page.getByRole('region', { name: '2026-10-07', exact: true }).locator('.calendar-event')).toHaveCount(0); await expect(page.getByRole('region', { name: '2026-10-09', exact: true }).locator('.calendar-event')).toContainText('Lower')
  await b(page, 'Next period').click(); await expect(page.getByRole('region', { name: '2026-10-14', exact: true }).locator('.calendar-event')).toContainText('Upper'); await expect(page.getByRole('region', { name: '2026-10-16', exact: true }).locator('.calendar-event')).toContainText('Lower')
  await manageRun(page, 'Edit'); await f(page, 'Lower weekday').selectOption('6'); await b(page, 'Cancel').click(); await expect(page.getByRole('heading', { level: 1 })).toHaveText('Current Plans'); await manageRun(page, 'Edit'); await expect(f(page, 'Lower weekday')).toHaveValue('4')
})
