import { expect, test, type Page } from '@playwright/test'

test.setTimeout(90000)
const button = (page: Page, name: string) => page.getByRole('button', { name, exact: true })
const fixture = { schemaVersion: 1, kind: 'plan', plan: { name: 'Calendar four', trainingDaysPerWeek: 4, days: ['Upper', 'Lower', 'Push', 'Pull'].map((name) => ({ name, exercises: [{ name: `${name} exercise`, sets: [{ reps: { min: 5, max: 8 } }, { reps: { min: 8, max: 8 } }] }] })) } }
async function setup(page: Page) {
  await page.clock.setFixedTime(new Date('2025-01-06T01:00:00Z'))
  await page.goto('./'); await button(page, 'Create').click()
  const notice = button(page, 'Understood'); if (await notice.isVisible()) await notice.click()
  await button(page, 'Import AI Output').click(); await page.getByLabel('AI output JSON', { exact: true }).fill(JSON.stringify(fixture))
  await button(page, 'Validate and preview').click(); await page.getByLabel('Duration (weeks)', { exact: true }).fill('104'); await button(page, 'Save plan').click()
  await expect(page.getByRole('article', { name: 'Plan Calendar four', exact: true })).toBeVisible()
  await button(page, 'Calendar').click(); await button(page, 'Week').click(); await button(page, 'Add Plan').click()
  await page.getByLabel('Starting week (Monday)', { exact: true }).fill('2024-12-30')
  await button(page, 'Preview schedule').click(); await expect(page.getByRole('dialog')).toContainText('Friday: Rest')
  await button(page, 'Confirm schedule').click(); await expect(page.locator('.calendar-event')).toHaveCount(4)
}
const upper = (page: Page) => page.locator('.calendar-event').filter({ hasText: 'Calendar four / Upper' })
async function recordPartial(page: Page) {
  await page.getByLabel('Upper exercise set 1 Weight (kg)', { exact: true }).fill('40')
  await page.getByLabel('Upper exercise set 1 Repetitions', { exact: true }).fill('5')
  await button(page, 'Save').click(); await expect(page.getByRole('dialog')).toContainText('partial')
  await page.getByRole('dialog').getByRole('button').last().click()
  await expect(page.getByRole('region', { name: 'Saved session details' })).toContainText('Partial session')
}

test('four-day schedule: partial completion, next/prior week, all views, reload, details, themes and profile isolation', async ({ page }, testInfo) => {
  await setup(page); const address = page.url()
  await page.screenshot({ path: testInfo.outputPath('calendar-dark.png'), fullPage: true })
  await expect(button(page, 'Week')).toHaveAttribute('aria-pressed', 'true')
  await upper(page).click(); await expect(page.getByRole('region', { name: 'Training session' })).toContainText('Scheduled: 2024-12-30')
  await recordPartial(page); await button(page, 'Calendar').click(); await button(page, 'Week').click(); await page.getByLabel('Calendar date', { exact: true }).fill('2024-12-30')
  await expect(page.locator('.calendar-event.completed')).toHaveCount(1); await expect(upper(page)).toContainText('Completed · Partial')
  await button(page, 'Next period').click(); await expect(page.locator('.calendar-event')).toHaveCount(4); await expect(page.locator('.calendar-event.completed')).toHaveCount(0)
  await button(page, 'Previous period').click(); await expect(page.locator('.calendar-event.completed')).toHaveCount(1)
  await button(page, 'Day').click(); await expect(page.locator('.calendar-event')).toHaveCount(1)
  await button(page, 'Month').click(); await expect(page.getByLabel('month calendar')).toBeVisible()
  await button(page, 'Today').click(); await expect(page.getByLabel('Calendar date', { exact: true })).toHaveValue(/2025-01-0[56]/)
  await button(page, 'Week').click(); await page.getByLabel('Calendar date', { exact: true }).fill('2024-12-30')
  await page.reload(); await button(page, 'Week').click(); await page.getByLabel('Calendar date', { exact: true }).fill('2024-12-30'); await upper(page).click()
  await expect(page.getByRole('region', { name: 'Saved session details' })).toContainText('Scheduled: 2024-12-30')
  const localCompletion = await page.evaluate(() => new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date('2025-01-06T01:00:00Z')))
  await expect(page.getByRole('region', { name: 'Saved session details' })).toContainText(`Completed: ${localCompletion}`)
  await button(page, 'Settings').click(); await button(page, 'Light').click()
  await page.getByLabel('New profile name', { exact: true }).fill('Other calendar'); await button(page, 'Create profile').click()
  await button(page, 'Calendar').click(); await button(page, 'Week').click(); await expect(page.locator('.calendar-event')).toHaveCount(0); await expect(page.getByText('No schedules. Add an active plan to begin.')).toBeVisible()
  await button(page, 'Settings').click(); await page.getByRole('combobox', { name: 'Active profile', exact: true }).selectOption({ label: 'Guest' }); await button(page, 'Calendar').click()
  await page.getByLabel('Calendar date', { exact: true }).fill('2024-12-30'); await expect(page.locator('.calendar-event.completed')).toHaveCount(1)
  expect(page.url()).toBe(address)
  if (testInfo.project.name.includes('phone')) await page.setViewportSize({ width: 320, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await button(page, 'Stop Scheduling').focus(); await button(page, 'Stop Scheduling').scrollIntoViewIfNeeded()
  const actionBox = await button(page, 'Stop Scheduling').boundingBox(), navBox = await page.getByRole('navigation').boundingBox()
  expect(actionBox!.y + actionBox!.height).toBeLessThanOrEqual(navBox!.y)
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: testInfo.outputPath('calendar-light.png'), fullPage: true })
})

test('future mapping and stop explicitly keep started input; stale previews reject and keyboard cancellation preserves edits', async ({ page, context }) => {
  await setup(page)
  await button(page, 'Edit mapping / refresh plan').click()
  const cutoff = await page.getByLabel('Effective from', { exact: true }).inputValue()
  page.once('dialog', (dialog) => dialog.dismiss()); await button(page, 'Train').click(); await expect(page.getByRole('heading', { name: 'Edit schedule' })).toBeVisible()
  page.once('dialog', (dialog) => dialog.accept()); await button(page, 'Cancel').click()
  await page.getByLabel('Calendar date', { exact: true }).fill(cutoff); await upper(page).click()
  await page.getByLabel('Upper exercise set 1 Weight (kg)', { exact: true }).fill('55'); await expect(page.getByText('Draft saved locally.', { exact: true })).toBeVisible()
  await button(page, 'Calendar').click(); await button(page, 'Week').click(); await button(page, 'Edit mapping / refresh plan').click(); await page.getByLabel('Upper weekday', { exact: true }).selectOption('4')
  await button(page, 'Preview schedule').click(); await expect(page.getByRole('dialog')).toContainText('These started sessions are affected')
  await button(page, 'Confirm schedule').click(); await expect(page.getByRole('alert')).toContainText('Confirm keeping')
  await page.getByRole('checkbox').check(); await page.keyboard.press('Escape'); await expect(button(page, 'Preview schedule')).toBeFocused()
  await expect(page.getByLabel('Upper weekday', { exact: true })).toHaveValue('4'); await button(page, 'Preview schedule').click(); await page.getByRole('checkbox').check()
  const second = await context.newPage(); await second.goto('./'); await button(second, 'Calendar').click(); await button(second, 'Edit mapping / refresh plan').click(); await second.getByLabel('Upper weekday', { exact: true }).selectOption('5'); await button(second, 'Preview schedule').click(); await second.getByRole('checkbox').check(); await button(second, 'Confirm schedule').click(); await expect(second.getByRole('article', { name: 'Schedule Calendar four' })).toBeVisible()
  await button(page, 'Confirm schedule').click(); await expect(page.getByRole('alert')).toContainText('schedule changed')
  await page.keyboard.press('Escape'); page.once('dialog', (dialog) => dialog.accept()); await button(page, 'Cancel').click()
  await button(page, 'Stop Scheduling').click(); await button(page, 'Preview schedule').click(); await page.getByRole('checkbox').check(); await button(page, 'Confirm schedule').click()
  await page.getByLabel('Calendar date', { exact: true }).fill(cutoff); await expect(page.locator('.calendar-event')).toHaveCount(1); await expect(upper(page)).toContainText('Kept original session')
  await upper(page).click(); await expect(page.getByLabel('Upper exercise set 1 Weight (kg)', { exact: true })).toHaveValue('55')
  await button(page, 'Calendar').click(); await button(page, 'Week').click(); await page.getByLabel('Calendar date', { exact: true }).fill('2024-12-30'); await expect(page.locator('.calendar-event')).toHaveCount(4)
  await second.close()
})

test('stored schedule zone and Today survive a device-zone change at a Sunday/Monday boundary', async ({ page, context }) => {
  const cdp = await context.newCDPSession(page); await cdp.send('Emulation.setTimezoneOverride', { timezoneId: 'America/New_York' })
  await setup(page); await expect(page.getByLabel('Displayed time zone', { exact: true })).toHaveCount(0)
  await button(page, 'Today').click(); await expect(page.getByLabel('Calendar date', { exact: true })).toHaveValue('2025-01-05')
  await cdp.send('Emulation.setTimezoneOverride', { timezoneId: 'Asia/Tokyo' }); await page.reload()
  await button(page, 'Today').click(); await expect(page.getByLabel('Calendar date', { exact: true })).toHaveValue('2025-01-05')
  await button(page, 'Settings').click(); await page.getByLabel('Time zone', { exact: true }).fill('Asia/Tokyo'); await button(page, 'Save profile').click(); await expect(page.getByText('Profile saved.', { exact: true })).toBeVisible()
  await button(page, 'Calendar').click(); await button(page, 'Today').click(); await expect(page.getByLabel('Calendar date', { exact: true })).toHaveValue('2025-01-06'); await expect(page.locator('.calendar-event').first()).toContainText('America/New_York')
  await expect(page.getByRole('article', { name: 'Schedule Calendar four' })).toContainText('America/New_York')
})

test('failed schedule save preserves preview and unload guard; retry creates one independent overlapping schedule', async ({ page }) => {
  await setup(page); await button(page, 'Add Plan').click(); await page.getByLabel('Starting week (Monday)', { exact: true }).fill('2024-12-30')
  await page.getByLabel('Lower weekday', { exact: true }).selectOption('0'); await button(page, 'Preview schedule').click(); await expect(page.getByRole('alert')).toContainText('distinct weekday')
  await page.getByLabel('Lower weekday', { exact: true }).selectOption('1'); await button(page, 'Preview schedule').click()
  await page.evaluate(() => {
    const original = IDBObjectStore.prototype.add
    ;(window as unknown as { restoreCalendarWrite: () => void }).restoreCalendarWrite = () => { IDBObjectStore.prototype.add = original }
    IDBObjectStore.prototype.add = function (...args) { if (this.name === 'schedules') throw new DOMException('Simulated schedule disk full', 'QuotaExceededError'); return original.apply(this, args) }
  })
  await button(page, 'Confirm schedule').click(); await expect(page.getByRole('alert')).toContainText('Simulated schedule disk full'); await expect(page.getByRole('dialog')).toContainText('Monday: Upper')
  const unload = page.waitForEvent('dialog'); await page.evaluate(() => { setTimeout(() => window.location.reload(), 0) })
  const warning = await unload; expect(warning.type()).toBe('beforeunload'); await warning.dismiss(); await expect(page.getByRole('dialog')).toBeVisible()
  await page.evaluate(() => (window as unknown as { restoreCalendarWrite: () => void }).restoreCalendarWrite())
  await button(page, 'Confirm schedule').click(); await expect(page.locator('.calendar-event')).toHaveCount(8)
  const names = await upper(page).allTextContents(); expect(names[0]).not.toEqual(names[1])
  await upper(page).first().click(); await recordPartial(page); await button(page, 'Calendar').click(); await button(page, 'Week').click(); await page.getByLabel('Calendar date', { exact: true }).fill('2024-12-30')
  await expect(page.locator('.calendar-event.completed')).toHaveCount(1); await expect(upper(page)).toHaveCount(2)
  await page.reload(); await button(page, 'Week').click(); await page.getByLabel('Calendar date', { exact: true }).fill('2024-12-30'); await expect(page.locator('.calendar-event')).toHaveCount(8); await expect(page.locator('.calendar-event.completed')).toHaveCount(1)
})
