import { createNamedProfile } from './settings-actions'
import { startWeekly, closeTimer } from './train-actions'
import { expect, test, type Page } from '@playwright/test'
import { copyExercise } from '../../src/schemas/plan'
import { cardAction, occurrenceAction } from './create-actions'

test.setTimeout(90000)
const b = (p: Page, name: string) => p.getByRole('button', { name, exact: true })
const f = (p: Page, name: string) => p.getByLabel(name, { exact: true })
const planCard = (p: Page) => p.getByRole('article', { name: 'Plan Existing AI', exact: true })
async function open(p: Page) { await p.goto('./'); await b(p, 'Create').click(); if (await b(p, 'Understood').isVisible()) await b(p, 'Understood').click(); await expect(b(p, 'Create exercise')).toBeEnabled() }
async function records(p: Page, store = 'plans') {
  return p.evaluate(async (store) => {
    const db = await new Promise<IDBDatabase>((resolve, reject) => { const r = indexedDB.open('boros'); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error) })
    try { return await new Promise<any[]>((resolve, reject) => { const r = db.transaction(store).objectStore(store).getAll(); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error) }) } finally { db.close() }
  }, store)
}
// Seed already-saved, source-less AI snapshots into this test's fresh context.
// Nothing is imported through Create and no existing records are cleared.
async function seed(p: Page, finalGroup = false) {
  await open(p)
  const groupId = crypto.randomUUID()
  const exercise = (name: string, reps: number, tag = 'Upper') => copyExercise({ name, sets: [{ reps: { min: reps, max: reps } }, { reps: { min: reps, max: reps } }], tagNames: [tag], restBetweenSeconds: 999, restAfterSeconds: 999 })
  const first = { id: crypto.randomUUID(), name: 'First', groups: [{ id: groupId, number: 1, restBetweenRoundsSeconds: 75, restAfterGroupSeconds: 180 }], exercises: [{ ...exercise('A', 20), groupId }, { ...exercise('B', 8), groupId }, ...(finalGroup ? [] : [exercise('A', 5, 'Legs')])] }
  const days = [first, ...(finalGroup ? [] : [{ id: crypto.randomUUID(), name: 'Second', exercises: [exercise('A', 20), ...['C', 'D', 'E', 'F', 'G', 'H'].map((name) => exercise(name, 10, 'Legs'))] }])]
  const owner = (await records(p, 'settings'))[0].activeProfileId
  const plan = { id: crypto.randomUUID(), profileId: owner, name: 'Existing AI', nameKey: 'existing ai', activeNameKey: 'existing ai', durationWeeks: 12, days, revision: 1, createdAt: '2025-01-01T12:00:00.000Z', updatedAt: '2025-01-01T12:00:00.000Z' }
  await p.evaluate(async (plan) => {
    const db = await new Promise<IDBDatabase>((resolve, reject) => { const r = indexedDB.open('boros'); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error) })
    try { await new Promise<void>((resolve, reject) => { const tx = db.transaction('plans', 'readwrite'); tx.objectStore('plans').put(plan); tx.oncomplete = () => resolve(); tx.onabort = () => reject(tx.error) }) } finally { db.close() }
  }, plan)
  await p.reload(); await expect(planCard(p)).toBeVisible()
  return plan
}

test('existing plans repair into standalone templates; library notes save directly and plan variations stay independent', async ({ page }) => {
  const plan = await seed(page), catalog = page.getByRole('region', { name: 'Exercise catalog' }), address = page.url()
  await expect(catalog.getByRole('article')).toHaveCount(8)
  expect(await records(page, 'exercises')).toHaveLength(8)
  const repaired = (await records(page))[0]
  expect(repaired.updatedAt).toBe(plan.updatedAt); expect(repaired.revision).toBe(2)
  const a = catalog.getByRole('article', { name: 'A', exact: true })
  await expect(a.getByRole('button').locator('strong')).toHaveText('A'); await expect(a.getByRole('button').locator('small')).toHaveText(/Added: \d{2}\/\d{2}\/\d{4}/)
  await cardAction(page, a, 'Edit')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Create > Exercise')
  await expect(page.getByRole('heading', { level: 1 })).toBeFocused()
  await f(page, 'Notes (optional)').fill('Saved directly on the template')
  await b(page, 'Cancel').click(); await page.getByRole('dialog').getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(f(page, 'Notes (optional)')).toHaveValue('Saved directly on the template')
  page.once('dialog', (dialog) => dialog.dismiss()); await b(page, 'Calendar').click()
  await b(page, 'Save exercise').click()
  expect(await records(page)).toEqual([repaired])
  await cardAction(page, planCard(page), 'Duplicate'); await b(page, 'Save plan').click()
  const second = (await records(page)).find((p) => p.name === 'Existing AI (copy)')
  await cardAction(page, planCard(page), 'Edit')
  await occurrenceAction(page, page.locator('.plan-day').first(), 'Edit')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Create > Plan > Exercise')
  await f(page, 'Number of sets').fill('4'); await page.locator('.count-controls button').click()
  await f(page, 'Set 1 Reps minimum').fill('10'); await b(page, 'Apply to All').click()
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm' }).click()
  await page.locator('.exercise-editor').getByRole('button', { name: 'Cancel', exact: true }).click(); await page.getByRole('dialog').getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(f(page, 'Set 1 Reps minimum')).toHaveValue('10')
  await page.locator('.exercise-editor button[type=submit]').click(); await b(page, 'Save plan').click()
  const templates = await records(page, 'exercises'), template = templates.find((e) => e.name === 'A')
  expect(template.sets).toHaveLength(2); expect(template.sets[0].reps.min).toBe(20)
  expect(template.notes).toBe('Saved directly on the template')
  expect((await records(page)).find((p) => p.id === second.id)).toEqual(second)
  await page.reload(); expect(await records(page, 'exercises')).toEqual(templates)
  await f(page, 'Search exercises').fill('A'); await b(page, 'Tags').click(); await b(page, 'Legs').click()
  await expect(catalog.getByRole('article')).toHaveCount(0)
  await b(page, 'Upper').click(); await expect(catalog.getByRole('article')).toHaveCount(1)
  await b(page, 'Tags (2)').click(); await expect(catalog.getByRole('article')).toHaveCount(1)
  await b(page, 'Clear').click()
  await b(page, 'Settings').click(); await createNamedProfile(page, 'Private')
  await expect(page.locator('input[name=name]')).toHaveValue('Private'); await b(page, 'Create').click()
  await expect(catalog.getByRole('article')).toHaveCount(0); await expect(planCard(page)).toHaveCount(0)
  expect(await records(page, 'exercises')).toEqual(templates); expect(page.url()).toBe(address)
})

test('shared rest editor preserves blank and zero, displays 75/180 exactly, and rejects invalid seconds without losing input', async ({ page }) => {
  await open(page); await b(page, 'Create exercise').click(); await f(page, 'Exercise name').fill('Rest example'); await f(page, 'Set 1 Reps minimum').fill('8')
  await f(page, 'Rest between sets (optional) minutes').fill('1'); await f(page, 'Rest between sets (optional) seconds').fill('15')
  await f(page, 'Rest after exercise (optional) minutes').fill('3'); await b(page, 'Save exercise').click()
  const card = page.getByRole('article', { name: 'Rest example', exact: true })
  await cardAction(page, card, 'Edit')
  await expect(f(page, 'Rest after exercise (optional) seconds')).toHaveValue('0')
  await expect(f(page, 'Rest between sets (optional) minutes')).toHaveValue('1'); await expect(f(page, 'Rest between sets (optional) seconds')).toHaveValue('15')
  await f(page, 'Rest between sets (optional) seconds').fill('60'); await b(page, 'Save exercise').click()
  await expect(f(page, 'Rest between sets (optional) seconds')).toHaveAttribute('aria-invalid', 'true')
  await expect(f(page, 'Exercise name')).toHaveValue('Rest example')
  expect((await records(page, 'exercises'))[0].restBetweenSeconds).toBe(75)
  await f(page, 'Rest between sets (optional) minutes').fill(''); await f(page, 'Rest between sets (optional) seconds').fill('')
  await f(page, 'Rest after exercise (optional) minutes').fill(''); await f(page, 'Instructions (optional)').fill('Unrelated change'); await b(page, 'Save exercise').click()
  await page.reload(); await cardAction(page, card, 'Edit')
  await expect(f(page, 'Rest between sets (optional) minutes')).toHaveValue(''); await expect(f(page, 'Rest between sets (optional) seconds')).toHaveValue('')
  const saved = (await records(page, 'exercises'))[0]; expect(saved.restBetweenSeconds).toBeUndefined(); expect(saved.restAfterSeconds).toBe(0)
})

test('both themes: compact scrollable cards, keyboard dialogs, footer placement, move focus and grouping deletion preserve prescriptions', async ({ page }, info) => {
  const original = await seed(page), catalog = page.getByRole('region', { name: 'Exercise catalog' })
  await b(page, 'Create exercise').click(); await f(page, 'Exercise name').fill('Extra'); await f(page, 'Set 1 Reps minimum').fill('1'); await b(page, 'Save exercise').click()
  for (const theme of ['Dark', 'Light']) {
    await b(page, 'Settings').click(); await b(page, theme).click(); await b(page, 'Create').click()
    await expect(planCard(page)).toContainText('12 weeks · 2 training days · 5 rest days')
    expect(await catalog.evaluate((node) => node.scrollHeight > node.clientHeight)).toBe(true)
    await catalog.getByRole('button').last().focus()
    expect(await catalog.evaluate((node) => node.scrollTop)).toBeGreaterThan(0)
    await planCard(page).getByRole('button').focus(); await page.keyboard.press('Shift+Tab'); await page.keyboard.press('Tab'); await expect(planCard(page).getByRole('button')).toBeFocused(); expect(await planCard(page).getByRole('button').evaluate((node) => getComputedStyle(node).outlineStyle)).not.toBe('none'); await page.keyboard.press('Enter'); await expect(page.getByRole('dialog')).toBeVisible()
    await page.screenshot({ path: info.outputPath(`plan-actions-${theme}.png`) })
    await page.keyboard.press('Escape'); await expect(planCard(page).getByRole('button')).toBeFocused()
    expect(await planCard(page).getByRole('button').evaluate((node) => getComputedStyle(node).outlineStyle)).not.toBe('none')
    await page.evaluate(() => window.scrollTo(0, 0)); await page.screenshot({ path: info.outputPath(`catalog-${theme}.png`), fullPage: true })
    await cardAction(page, planCard(page), 'Edit')
    const first = page.locator('.plan-day').first(), footer = first.locator('.superset-footer')
    expect(await footer.evaluate((node) => node.previousElementSibling?.getAttribute('data-occurrence-id'))).toBe(original.days[0].exercises[1].id)
    expect(await footer.evaluate((node) => node.nextElementSibling?.getAttribute('data-occurrence-id'))).toBe(original.days[0].exercises[2].id)
    await expect(f(page, 'Rest between rounds minutes')).toHaveValue('1'); await expect(f(page, 'Rest between rounds seconds')).toHaveValue('15')
    const occurrence = first.locator('[data-occurrence-id]').last(), move = occurrence.getByRole('button', { name: /^Actions for / })
    await occurrenceAction(page, occurrence, 'Move'); await expect(page.getByRole('dialog').getByRole('button', { name: 'Day 1: First' })).toHaveCount(0)
    await page.screenshot({ path: info.outputPath(`move-${theme}.png`) }); await page.keyboard.press('Escape'); await expect(move).toBeFocused()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await footer.scrollIntoViewIfNeeded(); await page.screenshot({ path: info.outputPath(`footer-${theme}.png`) })
    await b(page, 'Cancel').click()
  }
  await cardAction(page, planCard(page), 'Edit')
  const first = page.locator('.plan-day').first()
  await occurrenceAction(page, first.locator('[data-occurrence-id]').last(), 'Move')
  await page.getByRole('dialog').getByRole('button', { name: 'Day 2: Second', exact: true }).click()
  await expect(page.locator(`[data-occurrence-id="${original.days[0].exercises[2].id}"]`).getByRole('button', { name: /^Actions for / })).toBeFocused()
  await first.locator('.superset-settings').getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('keeps every exercise and prescription')
  await page.keyboard.press('Escape'); await expect(first.locator('.superset-settings')).toBeVisible()
  await first.locator('.superset-settings').getByRole('button', { name: 'Delete', exact: true }).click(); await page.getByRole('dialog').getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(first.locator('[data-occurrence-id]')).toHaveCount(2); await expect(first.locator('.superset-settings')).toHaveCount(0)
  await b(page, 'Save plan').click()
  const saved = (await records(page))[0], oldItems = original.days.flatMap((day) => day.exercises), newItems = saved.days.flatMap((day) => day.exercises)
  for (const item of oldItems) expect(newItems.find((value) => value.id === item.id).prescription).toEqual(item.prescription)
})

test('A20 B8 rounds expose one correct rest each, including final block and timer recovery', async ({ page }) => {
  await seed(page, true); await startWeekly(page, 'Existing AI', 'First')
  const rounds = page.locator('.superset-round'); await expect(rounds).toHaveCount(2)
  for (let i = 0; i < 2; i++) { await expect(rounds.nth(i).locator('.training-set')).toHaveCount(2); await expect(rounds.nth(i).locator('.rest-control')).toHaveCount(1) }
  await expect(rounds.first()).toContainText('20'); await expect(rounds.first()).toContainText('8')
  await b(page, 'REST Superset 1 after round 1').click(); await expect(page.getByRole('timer')).toContainText('1:15')
  await closeTimer(page); await b(page, 'REST Superset 1 after group').click(); await expect(page.getByRole('timer')).toContainText('3:00')
  await page.reload(); await expect(page.getByRole('region', { name: 'Unfinished sessions' })).toHaveCount(0); await startWeekly(page, 'Existing AI', 'First'); await expect(page.getByRole('region', { name: 'Rest timer' })).toContainText('after group')
})

test('picker selection obeys filtered identities, sort order, Select All, single Add, cancel and repeated-click rules', async ({ page }) => {
  await seed(page); await b(page, 'Create Plan').click(); await f(page, 'Plan name').fill('Selection'); await f(page, 'Duration (weeks)').fill('2')
  const picker = page.getByRole('region', { name: 'Choose exercise', exact: true }), rows = picker.locator('.exercise-selection-row')
  const check = (name: string) => picker.getByRole('checkbox', { name, exact: true })
  const openPicker = () => b(page, 'Add exercise').click()
  await openPicker(); await expect(rows).toHaveCount(8)
  await expect(b(page, 'Add selected')).toBeDisabled(); await expect(b(page, 'Tags')).toHaveAttribute('aria-expanded', 'false')
  await check('A').check(); await expect(check('Select All')).not.toBeChecked()
  await check('Select All').check(); await expect(rows.locator('input:checked')).toHaveCount(8)
  await check('H').uncheck(); await expect(check('Select All')).not.toBeChecked()
  await check('Select All').check(); await check('Select All').uncheck(); await expect(rows.locator('input:checked')).toHaveCount(0)
  for (const name of ['A','B','C','D','E','F','G','H']) await check(name).check()
  await expect(check('Select All')).toBeChecked()
  expect(await picker.getByRole('region', { name: 'Available exercises' }).evaluate((node) => node.scrollHeight > node.clientHeight)).toBe(true)
  await f(page, 'Sort exercises to add').selectOption('za'); await expect(rows.first().getByRole('checkbox')).toHaveAccessibleName('H')
  await expect(check('Select All')).toBeChecked()
  await b(page, 'Tags').click(); await b(page, 'Upper').click(); await expect(rows).toHaveCount(2)
  await expect(rows.locator('input:checked')).toHaveCount(2)
  await b(page, 'Tags (1)').click(); await expect(rows).toHaveCount(2)
  await b(page, 'Clear').click(); await expect(rows).toHaveCount(8); await expect(rows.locator('input:checked')).toHaveCount(2)
  await expect(f(page, 'Sort exercises to add')).toHaveValue('az')
  await f(page, 'Search exercises to add').fill('missing'); await expect(check('Select All')).toBeDisabled(); await expect(b(page, 'Add selected')).toBeDisabled()
  await b(page, 'Clear').click(); await expect(rows.locator('input:checked')).toHaveCount(0)
  await check('Select All').check(); await b(page, 'Cancel selection').click(); await expect(page.locator('[data-occurrence-id]')).toHaveCount(0)
  await openPicker(); await check('A').check(); await check('B').check(); await b(page, 'Add C').click()
  await expect(picker).toHaveCount(0); await expect(page.locator('[data-occurrence-id]')).toHaveCount(1)
  await openPicker(); await check('Select All').check(); await f(page, 'Sort exercises to add').selectOption('za')
  await b(page, 'Add selected').evaluate((node: HTMLButtonElement) => { node.click(); node.click() })
  await expect(picker).toHaveCount(0); await expect(page.locator('[data-occurrence-id]')).toHaveCount(9)
  expect((await records(page)).filter((p) => p.name === 'Selection')).toHaveLength(0)
  await b(page, 'Save plan').click(); await page.reload()
  const saved = (await records(page)).find((p) => p.name === 'Selection'), items = saved.days[0].exercises
  expect(items.map((e) => e.prescription.name)).toEqual(['C','H','G','F','E','D','C','B','A'])
  expect(new Set(items.map((e) => e.id)).size).toBe(9)
})

test('occurrence popup keyboard order and Cancel preserve dirty input; tag controls scroll without dropping options in both themes', async ({ page }, info) => {
  await seed(page)
  await page.evaluate(async () => {
    const db = await new Promise<IDBDatabase>((resolve) => { const r = indexedDB.open('boros'); r.onsuccess = () => resolve(r.result) })
    const owner = await new Promise<string>((resolve) => { const r = db.transaction('settings').objectStore('settings').get('workspace'); r.onsuccess = () => resolve(r.result.activeProfileId) })
    await new Promise<void>((resolve, reject) => { const tx = db.transaction('tags', 'readwrite'); for (let i = 36; i >= 1; i--) { const name = 'Tag ' + String(i).padStart(2, '0'); tx.objectStore('tags').put({ id: crypto.randomUUID(), profileId: owner, name, nameKey: name.toLowerCase(), createdAt: '2025-01-01T00:00:00.000Z', updatedAt: '2025-01-01T00:00:00.000Z' }) }; tx.oncomplete = () => resolve(); tx.onabort = () => reject(tx.error) }); db.close()
  })
  for (const theme of ['Dark', 'Light']) {
    await b(page, 'Settings').click(); await b(page, theme).click(); await b(page, 'Create').click()
    await b(page, 'Tags').click()
    const tags = page.locator('.tag-scroll'); await expect(tags.getByRole('button')).toHaveCount(38)
    expect(await tags.evaluate((node) => node.scrollWidth > node.clientWidth)).toBe(true)
    expect(await tags.evaluate((node) => new Set([...node.children].map((el) => Math.round(el.getBoundingClientRect().top))).size)).toBeLessThanOrEqual(3)
    await tags.getByRole('button').last().focus(); expect(await tags.evaluate((node) => node.scrollLeft)).toBeGreaterThan(0)
    await cardAction(page, page.getByRole('article', { name: 'A', exact: true }), 'Edit')
    const summary = page.locator('.tag-dropdown summary'); await summary.focus(); await page.keyboard.press('Enter')
    const options = page.getByRole('group', { name: 'Existing tags' }); await expect(options.getByRole('button')).toHaveCount(38)
    expect(await options.getByRole('button').allTextContents()).toEqual(['Legs', ...Array.from({ length: 36 }, (_, i) => 'Tag ' + String(i + 1).padStart(2,'0')), 'Upper'])
    expect(await options.evaluate((node) => node.clientHeight <= 440 && node.scrollHeight > node.clientHeight)).toBe(true)
    await options.getByRole('button', { name: 'Tag 24', exact: true }).focus(); await page.keyboard.press('Enter')
    await expect(b(page, 'Remove tag Tag 24')).toBeVisible(); await expect(summary).toBeFocused()
    await page.screenshot({ path: info.outputPath('exercise-spacing-' + theme + '.png'), fullPage: true })
    await b(page, 'Save exercise').click(); await cardAction(page, planCard(page), 'Edit')
    const occurrence = page.locator('[data-occurrence-id]').first(), menu = occurrence.getByRole('button', { name: /^Actions for / })
    await menu.focus(); await page.keyboard.press('Enter')
    const actions = page.locator('.occurrence-menu button'); expect(await actions.allTextContents()).toEqual(['Edit','Duplicate','Move','Delete'])
    await expect(actions.first()).toBeFocused(); await page.keyboard.press('Tab'); await expect(actions.nth(1)).toBeFocused()
    await page.keyboard.press('Escape'); await expect(menu).toBeFocused()
    const surfaces = await occurrence.evaluate((node) => [getComputedStyle(node).backgroundColor, getComputedStyle(node.closest('.plan-day')!).backgroundColor])
    expect(surfaces[0]).not.toBe(surfaces[1])
    await occurrenceAction(page, occurrence, 'Duplicate'); await expect(page.locator('.plan-day').first().locator('[data-occurrence-id]')).toHaveCount(4)
    await occurrenceAction(page, page.locator('.plan-day').first().locator('[data-occurrence-id]').last(), 'Delete'); await page.getByRole('dialog').getByRole('button', { name: 'Confirm' }).click()
    await expect(page.locator('.plan-day').first().locator('[data-occurrence-id]')).toHaveCount(3)
    await b(page, 'Cancel').click(); await page.getByRole('dialog').getByRole('button', { name: 'Cancel', exact: true }).click(); await expect(f(page, 'Plan name')).toHaveValue('Existing AI')
    await b(page, 'Cancel').click(); await page.getByRole('dialog').getByRole('button', { name: 'Confirm', exact: true }).click()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
})
