import { expect, test, type Page } from './strength-test'
import { cardAction, occurrenceAction } from './create-actions'

test.setTimeout(90000)
const b = (p: Page, name: string) => p.getByRole('button', { name, exact: true })
const f = (p: Page, name: string) => p.getByLabel(name, { exact: true })
const card = (p: Page) => p.getByRole('article', { name: 'Modal squat', exact: true }).getByRole('button')
const instructions = '<b>Plain instructions</b>\n' + Array.from({ length: 30 }, (_, i) => `Instruction line ${i + 1}`).join('\n')
const note = 'Library note only\nSecond note line <script>inert</script>'
async function rows(p: Page, store: string) {
  return p.evaluate(async (store) => {
    const db = await new Promise<IDBDatabase>((resolve, reject) => { const r = indexedDB.open('boros'); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error) })
    try { return await new Promise<any[]>((resolve, reject) => { const r = db.transaction(store).objectStore(store).getAll(); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error) }) } finally { db.close() }
  }, store)
}
async function title(p: Page, text: string) {
  await expect(p.getByRole('heading', { level: 1 })).toHaveCount(1)
  await expect(p.getByRole('heading', { level: 1 })).toHaveText(text)
  await expect(p.getByRole('navigation', { name: 'Editor breadcrumbs' })).toHaveCount(0)
  await expect(p.getByRole('button', { name: /^Back to (Create|Plan|AI)$/ })).toHaveCount(0)
  await expect(p.locator('h1 button, h1 a')).toHaveCount(0)
}
async function setup(p: Page) {
  await p.goto('./'); await b(p, 'Create').click()
  if (await b(p, 'Understood').isVisible()) await b(p, 'Understood').click()
  await b(p, 'Create exercise').click(); await f(p, 'Exercise name').fill('Modal squat'); await f(p, 'Set 1 Reps minimum').fill('8')
  await f(p, 'Instructions (optional)').fill(instructions); await f(p, 'Notes (optional)').fill(note)
  await f(p, 'YouTube tutorial URL (optional)').fill('https://youtu.be/M7lc1UVf-VE?autoplay=1&note=private')
  await b(p, 'Save').click(); await expect(card(p)).toBeVisible()
  await b(p, 'Create Plan').click(); await f(p, 'Plan name').fill('Independent plan'); await f(p, 'Duration (weeks)').fill('4')
  await b(p, 'Add exercise').click(); await b(p, 'Add Modal squat').click(); await b(p, 'Save plan').click()
  await expect(p.getByRole('article', { name: 'Plan Independent plan', exact: true })).toBeVisible()
}

for (const theme of ['Dark', 'Light']) test(`details block background, stack actions and preserve template ownership (${theme}, simulated embed)`, async ({ page, context }, info) => {
  const embeds: { url: string; referer?: string }[] = []
  await page.route('https://www.youtube.com/embed/**', async (route) => {
    embeds.push({ url: route.request().url(), referer: (await route.request().allHeaders()).referer })
    await route.fulfill({ contentType: 'text/html', body: '<title>Simulated YouTube</title><button>Play simulation</button><button>Fullscreen simulation</button>' })
  })
  await setup(page)
  const originalPlan = await rows(page, 'plans'), original = (await rows(page, 'exercises'))[0], address = page.url()
  await b(page, 'Settings').click(); await b(page, theme).click(); await b(page, 'Create').click()
  expect(embeds).toEqual([])
  await card(page).scrollIntoViewIfNeeded(); await card(page).focus()
  const scrollBefore = await page.evaluate(() => scrollY)
  await card(page).click()
  const details = page.getByRole('dialog', { name: 'Modal squat', exact: true })
  await expect(details).toBeVisible(); await expect(page.locator('body')).toHaveCSS('position', 'fixed')
  await expect(details.getByRole('region', { name: 'Instructions', exact: true })).toHaveText('Instructions' + instructions)
  await expect(details.getByRole('region', { name: 'Note', exact: true })).toHaveText('Note' + note)
  await expect(details.locator('script, b')).toHaveCount(0)
  await expect(details.getByRole('button', { name: 'Edit', exact: true })).toHaveCount(0)
  const player = details.locator('iframe')
  await expect(player).toHaveAttribute('title', 'YouTube exercise tutorial')
  await expect(player).toHaveAttribute('src', 'https://www.youtube.com/embed/M7lc1UVf-VE?autoplay=0&controls=1&playsinline=1&fs=1')
  await expect(player).toHaveAttribute('referrerpolicy', 'strict-origin-when-cross-origin')
  await expect(player).toHaveAttribute('allowfullscreen', '')
  const dimensions = await player.boundingBox(); expect(dimensions!.width).toBeGreaterThanOrEqual(200); expect(dimensions!.height).toBeGreaterThanOrEqual(200)
  expect(await details.evaluate((node) => node.scrollHeight > node.clientHeight)).toBe(true)
  const bodyTop = await page.locator('body').evaluate((node) => node.getBoundingClientRect().top)
  await expect(b(page, 'Settings').click({ timeout: 250 })).rejects.toThrow()
  await expect(b(page, 'Calendar').click({ timeout: 250 })).rejects.toThrow()
  await page.mouse.click(2, 2) // Visible backdrop, not a scrolled-off header coordinate.
  await page.mouse.move(2, 2); await page.mouse.wheel(0, 800)
  expect(await page.locator('body').evaluate((node) => node.getBoundingClientRect().top)).toBe(bodyTop)
  await b(page, 'Settings').evaluate((node: HTMLButtonElement) => node.focus())
  const focusState = await details.evaluate((node: HTMLDialogElement) => ({ contained: node.contains(document.activeElement), active: document.activeElement?.outerHTML.slice(0, 200), modal: node.matches(':modal'), inert: node.inert }))
  expect(focusState.contained, JSON.stringify(focusState)).toBe(true)
  await player.scrollIntoViewIfNeeded(); await expect(player).toBeInViewport()
  await page.screenshot({ path: info.outputPath(`details-${theme}.png`) })
  await b(page, 'Exercise actions').click()
  const actions = page.getByRole('dialog', { name: 'Exercise actions', exact: true })
  await expect(actions).toBeVisible(); await expect(page.locator('iframe')).toHaveCount(0)
  expect(await page.locator('.exercise-details').evaluate((node) => node.inert)).toBe(true)
  expect(await actions.locator('.exercise-action-list button').allTextContents()).toEqual(['Edit', 'Duplicate', 'Merge', 'Archive', 'Delete'])
  await expect(actions.getByRole('button', { name: 'Archive', exact: true })).toHaveClass('archive-action')
  await actions.getByRole('button', { name: 'Edit', exact: true }).focus()
  for (let i = 0; i < 9; i++) { await page.keyboard.press('Tab'); expect(await actions.evaluate((node) => node.contains(document.activeElement))).toBe(true) }
  await page.keyboard.press('Escape'); await expect(actions).toHaveCount(0); await expect(b(page, 'Exercise actions')).toBeFocused()
  await expect(player).toHaveCount(1)
  await page.keyboard.press('Escape'); await expect(page.locator('dialog')).toHaveCount(0); await expect(card(page)).toBeFocused()
  expect(await page.evaluate(() => scrollY)).toBe(scrollBefore)
  await expect(page.locator('body')).not.toHaveCSS('position', 'fixed')
  await expect(page.locator('iframe')).toHaveCount(0)
  await cardAction(page, page.getByRole('article', { name: 'Modal squat', exact: true }), 'Edit')
  await title(page, 'Create > Exercise'); await expect(page.locator('dialog, iframe')).toHaveCount(0)
  await f(page, 'Notes (optional)').fill('Updated standalone note'); await b(page, 'Save').click()
  expect(await rows(page, 'plans')).toEqual(originalPlan)
  expect((await rows(page, 'exercises'))[0].id).toBe(original.id)
  await cardAction(page, page.getByRole('article', { name: 'Modal squat', exact: true }), 'Duplicate')
  await expect(f(page, 'Exercise name')).toHaveValue('Modal squat (copy)'); await b(page, 'Save').click()
  const duplicate = (await rows(page, 'exercises')).find((row) => row.name === 'Modal squat (copy)'); expect(duplicate.id).not.toBe(original.id)
  await cardAction(page, page.getByRole('article', { name: 'Modal squat', exact: true }), 'Archive')
  await expect(page.locator('iframe')).toHaveCount(0)
  await expect(page.getByRole('dialog')).toHaveCount(1); await b(page, 'Cancel').click(); await expect(card(page)).toBeFocused()
  await cardAction(page, page.getByRole('article', { name: 'Modal squat', exact: true }), 'Archive'); await page.getByRole('dialog').getByRole('button', { name: 'Archive', exact: true }).click()
  await expect(card(page)).toHaveCount(0)
  expect((await rows(page, 'exercises')).find((row) => row.id === original.id).archivedAt).toBeTruthy()
  expect(await rows(page, 'plans')).toEqual(originalPlan)
  expect(context.pages()).toHaveLength(1); expect(page.url()).toBe(address)
  expect(embeds.length).toBeGreaterThan(0)
  for (const embed of embeds) { expect(embed.url).toBe('https://www.youtube.com/embed/M7lc1UVf-VE?autoplay=0&controls=1&playsinline=1&fs=1'); expect(embed.referer).toBe(new URL(address).origin + '/') }
})

test('one plain-text title path through nested editors; Cancel keeps unsaved input', async ({ page }) => {
  await setup(page); await title(page, 'Create')
  await cardAction(page, page.getByRole('article', { name: 'Plan Independent plan', exact: true }), 'Edit')
  await title(page, 'Create > Plan')
  await occurrenceAction(page, page.locator('.plan-day'), 'Edit'); await title(page, 'Create > Plan > Exercise')
  await f(page, 'Notes (optional)').fill('Unsaved occurrence note')
  await page.locator('.exercise-editor').getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(f(page, 'Notes (optional)')).toHaveValue('Unsaved occurrence note')
  await page.locator('.exercise-editor button[type=submit]').click(); await title(page, 'Create > Plan')
  await b(page, 'Cancel').click(); await page.getByRole('dialog').getByRole('button', { name: 'Cancel', exact: true }).click(); await title(page, 'Create > Plan')
  await b(page, 'Save plan').click(); await title(page, 'Create')
  await b(page, 'Create exercise').click(); await title(page, 'Create > Exercise'); await b(page, 'Cancel').click()
  await b(page, 'Import').click(); await title(page, 'Create > AI'); await b(page, 'Close').click(); await title(page, 'Create')
})

test('invalid saved tutorial never mounts a player; blocked embed leaves details and Close available', async ({ page, context }) => {
  await setup(page)
  await page.evaluate(async () => {
    const db = await new Promise<IDBDatabase>((resolve) => { const r = indexedDB.open('boros'); r.onsuccess = () => resolve(r.result) })
    await new Promise<void>((resolve, reject) => { const tx = db.transaction('exercises', 'readwrite'), store = tx.objectStore('exercises'); const r = store.getAll(); r.onsuccess = () => { store.put({ ...r.result[0], tutorialUrl: 'https://evil.test/embed/abcdefghijk' }) }; tx.oncomplete = () => resolve(); tx.onabort = () => reject(tx.error) }); db.close()
  })
  await page.reload(); await card(page).click(); await expect(page.locator('iframe')).toHaveCount(0); await b(page, 'Close').click()
  await cardAction(page, page.getByRole('article', { name: 'Modal squat', exact: true }), 'Edit')
  await f(page, 'YouTube tutorial URL (optional)').fill('https://youtu.be/M7lc1UVf-VE'); await b(page, 'Save').click()
  await page.route('https://www.youtube.com/embed/**', (route) => route.abort('failed'))
  await card(page).click(); await expect(page.getByRole('region', { name: 'Note', exact: true })).toContainText(note)
  await b(page, 'Close').click(); await expect(card(page)).toBeFocused(); await expect(page.locator('iframe')).toHaveCount(0)
  expect(context.pages()).toHaveLength(1)
})
