import { createNamedProfile } from './settings-actions'
import { cardAction } from './create-actions'
import { expect, test, type Page } from '@playwright/test'

async function openCreate(page: Page) {
  await page.goto('./')
  await page.getByRole('button', { name: 'Create', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Create', exact: true })).toBeVisible()
  const notice = page.getByRole('button', { name: 'Understood' })
  if (await notice.isVisible()) await notice.click()
}
async function add(page: Page, name: string, tag?: string) {
  await page.getByRole('button', { name: 'Create exercise', exact: true }).click()
  await page.getByLabel('Exercise name', { exact: true }).fill(name)
  await page.getByLabel('Set 1 Reps minimum', { exact: true }).fill('5')
  if (tag) { await page.getByLabel('New tag', { exact: true }).fill(tag); await page.getByRole('button', { name: 'Add', exact: true }).click() }
  await page.getByRole('button', { name: 'Save exercise', exact: true }).click()
  await expect(page.getByRole('article', { name, exact: true })).toBeVisible()
}
test('three-set prescription, edit, duplicate, archive/restore and reload', async ({ page }, testInfo) => {
  const external: string[] = []
  await page.route('https://www.youtube.com/embed/**', (route) => route.fulfill({ contentType: 'text/html', body: '<button>Simulated player</button>' }))
  page.on('request', (request) => { if (/(^|\.)youtube\.com$|(^|\.)youtu\.be$/.test(new URL(request.url()).hostname)) external.push(request.url()) })
  await openCreate(page)
  await page.getByRole('button', { name: 'Create exercise', exact: true }).click()
  await page.getByLabel('Exercise name', { exact: true }).fill('High Bar Squat')
  await page.getByLabel('Number of sets', { exact: true }).fill('3')
  await page.getByRole('button', { name: 'Apply', exact: true }).click()
  await page.getByLabel('Set 1 Reps minimum', { exact: true }).fill('5')
  await page.getByLabel('Set 1 Reps maximum (optional)', { exact: true }).fill('8')
  await page.getByLabel('Set 1 RIR minimum (optional)', { exact: true }).fill('1')
  await page.getByLabel('Set 1 RIR maximum (optional)', { exact: true }).fill('2')
  await page.getByRole('button', { name: 'Apply to All' }).click()
  await page.getByLabel('Set 2 Reps minimum', { exact: true }).fill('6')
  await page.getByLabel('Set 2 Reps maximum (optional)', { exact: true }).fill('')
  await page.getByLabel('Set 2 RIR minimum (optional)', { exact: true }).fill('0')
  await page.getByLabel('Set 2 RIR maximum (optional)', { exact: true }).fill('')
  await page.getByLabel('Set 3 Reps minimum', { exact: true }).fill('10')
  await page.getByLabel('Set 3 Reps maximum (optional)', { exact: true }).fill('12')
  await page.getByLabel('Set 3 RIR minimum (optional)', { exact: true }).fill('')
  await page.getByLabel('Set 3 RIR maximum (optional)', { exact: true }).fill('')
  await page.getByLabel('Rest between sets (optional) seconds', { exact: true }).fill('0')
  await page.getByLabel('Instructions (optional)', { exact: true }).fill('<script>alert("inert")</script>\nKeep this as plain text.')
  await page.getByLabel('YouTube tutorial URL (optional)', { exact: true }).fill('https://youtu.be/abcdefghijk')
  await page.getByLabel('New tag', { exact: true }).fill('Legs')
  await page.getByRole('button', { name: 'Add', exact: true }).click()
  await page.screenshot({ path: testInfo.outputPath('exercise-editor.png'), fullPage: true })
  await page.getByRole('button', { name: 'Save exercise', exact: true }).click()
  const card = page.getByRole('article', { name: 'High Bar Squat', exact: true })
  expect(external).toEqual([]) // No background editor/library video loading.
  await card.getByRole('button').click()
  await expect(page.getByRole('dialog')).toContainText('6 reps; 0 RIR')
  await expect(page.getByRole('dialog')).toContainText('10–12 reps; RIR unspecified')
  await expect(page.getByRole('dialog').locator('script')).toHaveCount(0)
  await page.reload()
  await cardAction(page, card, 'Edit')
  await expect(page.getByLabel('Set 2 RIR minimum (optional)', { exact: true })).toHaveValue('0')
  await expect(page.getByLabel('Rest after exercise (optional) seconds', { exact: true })).toHaveValue('')
  await page.getByLabel('Set 3 Reps minimum', { exact: true }).fill('11')
  await page.getByRole('button', { name: 'Save exercise', exact: true }).click()
  await cardAction(page, card, 'Duplicate')
  await expect(page.getByLabel('Exercise name', { exact: true })).toHaveValue('High Bar Squat (copy)')
  await page.getByLabel('Exercise name', { exact: true }).fill('Squat variation')
  await page.getByRole('button', { name: 'Save exercise', exact: true }).click()
  await expect(page.getByRole('article')).toHaveCount(2)
  await cardAction(page, card, 'Archive')
  await page.getByRole('dialog').getByRole('button', { name: 'Archive', exact: true }).click()
  await expect(card).toHaveCount(0)
  await page.getByLabel('Show archived exercises', { exact: true }).check()
  await cardAction(page, card, 'Restore')
  await page.getByLabel('Show archived exercises', { exact: true }).uncheck()
  await expect(card).toBeVisible()
  await page.reload()
  await expect(page.getByRole('article')).toHaveCount(2)
  expect(external.length).toBeGreaterThan(0)
  expect(external.every((url) => url === 'https://www.youtube.com/embed/abcdefghijk?autoplay=0&controls=1&playsinline=1&fs=1')).toBe(true)
})

test('combined search, sorting, ANY-tag filters and profile isolation', async ({ page }) => {
  await openCreate(page)
  await add(page, 'Zeta squat', 'Legs'); await add(page, 'Alpha squat', 'Arms'); await add(page, 'Row', 'Back')
  await page.getByLabel('Search exercises', { exact: true }).fill('squat')
  await page.getByRole('button', { name: 'Tags', exact: true }).click()
  const tags = page.locator('.tag-scroll')
  await tags.getByRole('button', { name: 'Legs', exact: true }).click(); await tags.getByRole('button', { name: 'Arms', exact: true }).click()
  await expect(page.getByRole('article').first()).toHaveAccessibleName('Alpha squat')
  await page.getByRole('combobox', { name: 'Sort exercises' }).selectOption('za')
  await expect(page.getByRole('article').first()).toHaveAccessibleName('Zeta squat')
  await page.getByRole('combobox', { name: 'Sort exercises' }).selectOption('newest')
  await expect(page.getByRole('article').first()).toHaveAccessibleName('Alpha squat')
  await page.getByRole('combobox', { name: 'Sort exercises' }).selectOption('oldest')
  await expect(page.getByRole('article').first()).toHaveAccessibleName('Zeta squat')
  await expect(page.getByRole('article')).toHaveCount(2)
  await tags.getByRole('button', { name: 'Legs', exact: true }).click()
  await expect(page.getByRole('article')).toHaveCount(1)
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await createNamedProfile(page, 'Other')
  await expect(page.locator('input[name="name"]')).toHaveValue('Other')
  await page.getByRole('button', { name: 'Create', exact: true }).click()
  await expect(page.getByRole('article')).toHaveCount(0)
  await page.getByRole('button', { name: 'Tags', exact: true }).click(); await expect(page.getByText('No tags yet.')).toBeVisible()
  await add(page, 'Zeta squat', 'Private tag')
  await page.reload()
  await expect(page.getByRole('article')).toHaveCount(1)
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByLabel('Active profile').selectOption({ label: 'Guest' })
  await expect(page.getByLabel('Active profile').locator('option:checked')).toHaveText('Guest')
  await page.getByRole('button', { name: 'Create', exact: true }).click()
  await expect(page.getByRole('article')).toHaveCount(3)
  await expect(page.getByText('Private tag', { exact: true })).toHaveCount(0)
})

test('set growth preserves values, reduction confirms, errors identify fields, mobile spacing', async ({ page }, testInfo) => {
  await openCreate(page)
  await page.getByRole('button', { name: 'Create exercise', exact: true }).click()
  await page.getByLabel('Exercise name', { exact: true }).fill('Test')
  await page.getByLabel('Set 1 Reps minimum', { exact: true }).fill('7')
  await page.getByLabel('Number of sets', { exact: true }).fill('3')
  const apply = page.getByRole('button', { name: 'Apply', exact: true })
  await apply.click()
  await expect(page.getByLabel('Set 1 Reps minimum', { exact: true })).toHaveValue('7')
  await page.getByLabel('Set 3 Reps minimum', { exact: true }).fill('12')
  await page.getByLabel('Number of sets', { exact: true }).fill('1'); await apply.click()
  await expect(page.getByRole('dialog', { name: 'Remove customized sets?' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(apply).toBeFocused()
  await expect(page.getByLabel('Set 3 Reps minimum', { exact: true })).toHaveValue('12')
  await apply.click(); await page.getByRole('dialog').getByRole('button', { name: 'Confirm' }).click()
  await page.getByLabel('Set 1 Reps maximum (optional)', { exact: true }).fill('2')
  await page.getByRole('button', { name: 'Save exercise' }).click()
  await expect(page.getByLabel('Set 1 Reps maximum (optional)', { exact: true })).toHaveAttribute('aria-invalid', 'true')
  await expect(page.getByText('Maximum reps must be at least the minimum.')).toBeVisible()
  await page.setViewportSize({ width: 320, height: 640 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Save exercise' }).focus()
  const save = await page.getByRole('button', { name: 'Save exercise' }).boundingBox()
  const nav = await page.getByRole('navigation', { name: 'Main navigation' }).boundingBox()
  expect(save!.y + save!.height).toBeLessThanOrEqual(nav!.y)
  await page.screenshot({ path: testInfo.outputPath('exercise-320.png'), fullPage: true })
})

test('failed save keeps exercise input and creates no tags until retry', async ({ page }) => {
  await openCreate(page)
  await page.getByRole('button', { name: 'Create exercise', exact: true }).click()
  await page.getByLabel('Exercise name', { exact: true }).fill('Recoverable')
  await page.getByLabel('Set 1 Reps minimum', { exact: true }).fill('8')
  await page.getByLabel('New tag', { exact: true }).fill('Pending tag')
  await page.getByRole('button', { name: 'Add', exact: true }).click()
  await page.evaluate(() => {
    const original = IDBObjectStore.prototype.put
    ;(window as unknown as { restoreWrite: () => void }).restoreWrite = () => { IDBObjectStore.prototype.put = original }
    IDBObjectStore.prototype.put = function (...args) { if (this.name === 'exercises') throw new DOMException('Simulated disk full', 'QuotaExceededError'); return original.apply(this, args) }
  })
  await page.getByRole('button', { name: 'Save exercise' }).click()
  await expect(page.getByRole('alert')).toContainText('Simulated disk full')
  await expect(page.getByLabel('Exercise name', { exact: true })).toHaveValue('Recoverable')
  expect(await page.evaluate(() => new Promise<number>((resolve, reject) => {
    const request = indexedDB.open('boros')
    request.onerror = () => reject(request.error)
    request.onsuccess = () => { const database = request.result; const count = database.transaction('tags').objectStore('tags').count(); count.onsuccess = () => { resolve(count.result); database.close() }; count.onerror = () => { reject(count.error); database.close() } }
  }))).toBe(0)
  await page.evaluate(() => (window as unknown as { restoreWrite: () => void }).restoreWrite())
  await page.getByRole('button', { name: 'Save exercise' }).click()
  await expect(page.getByRole('article', { name: 'Recoverable' })).toBeVisible()
})

test('two tabs reject stale exercise edits and preserve input', async ({ page, context }) => {
  await openCreate(page); await add(page, 'Squat')
  const other = await context.newPage(); await openCreate(other)
  await cardAction(page, page.getByRole('article'), 'Edit')
  await cardAction(other, other.getByRole('article'), 'Edit')
  await other.getByLabel('Exercise name', { exact: true }).fill('Stale draft')
  await page.getByLabel('Exercise name', { exact: true }).fill('Saved squat')
  await page.getByRole('button', { name: 'Save exercise' }).click()
  await other.getByRole('button', { name: 'Save exercise' }).click()
  await expect(other.getByRole('alert')).toContainText('another tab')
  await expect(other.getByLabel('Exercise name', { exact: true })).toHaveValue('Stale draft')
  await expect(page.getByRole('article', { name: 'Saved squat' })).toBeVisible()
})

test('another tab selecting a profile cannot retarget an exercise draft; light theme and existing tags', async ({ page, context }, testInfo) => {
  await openCreate(page); await add(page, 'Guest squat', 'Legs')
  await cardAction(page, page.getByRole('article'), 'Edit')
  await page.getByLabel('Exercise name', { exact: true }).fill('Guest only')
  const other = await context.newPage()
  await other.goto('./')
  await other.getByRole('button', { name: 'Settings', exact: true }).click()
  await createNamedProfile(other, 'Other')
  await expect(other.locator('input[name="name"]')).toHaveValue('Other')
  await other.getByRole('button', { name: 'Light', exact: true }).click()
  await other.getByRole('button', { name: 'Create', exact: true }).click()
  await expect(other.getByRole('article')).toHaveCount(0)
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await expect(page.getByLabel('Exercise name', { exact: true })).toHaveValue('Guest only')
  await page.screenshot({ path: testInfo.outputPath('exercise-light.png'), fullPage: true })
  await page.getByRole('button', { name: 'Save exercise' }).click()
  await expect(page.getByRole('article', { name: 'Guest only' })).toBeVisible()
  await other.reload(); await expect(other.getByRole('article')).toHaveCount(0)
  await page.getByRole('button', { name: 'Create exercise', exact: true }).click()
  await page.getByLabel('Exercise name', { exact: true }).fill('Second guest exercise')
  await page.getByLabel('Set 1 Reps minimum', { exact: true }).fill('5')
  await page.locator('.tag-editor').getByRole('button', { name: 'Legs', exact: true }).click()
  await expect(page.locator('.tag-editor').getByRole('button', { name: 'Legs', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Save exercise' }).click()
  await page.getByRole('article', { name: 'Second guest exercise' }).getByRole('button').click(); await expect(page.getByRole('dialog')).toContainText('Legs')
})
