import { openExerciseAction } from './train-actions'
import { expect, test, type Page, type Locator } from '@playwright/test'
import { cardAction, occurrenceAction } from './create-actions'
import { waitForDraft } from './train-actions'
const b=(p:Page,n:string)=>p.getByRole('button',{name:n,exact:true})
const f=(p:Page,n:string)=>p.getByLabel(n,{exact:true})
async function rows(p:Page,store:string) {return p.evaluate(async store=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('boros');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});try{return await new Promise<any[]>((resolve,reject)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}finally{db.close()}},store)}
async function open(p:Page,theme='Dark') {await p.goto('./');await b(p,'Settings').click();if(await b(p,'Understood').isVisible())await b(p,'Understood').click();await b(p,theme).click();await b(p,'Create').click()}
const exercise=(name:string,reps=8)=>({name,sets:[{reps:{min:reps,max:reps},rir:{min:0,max:0}}],tags:['Shared',name],instructions:name+' original'})
async function importPreview(p:Page,data:unknown) {await b(p,'Import').click();await f(p,'AI output JSON').fill(JSON.stringify(data));await b(p,'Validate and preview').click()}
async function importWorkout(p:Page) {await importPreview(p,{schemaVersion:5,kind:'workout',workout:{name:'Pair',supersets:[{number:1}],exercises:[exercise('A'),{...exercise('B',10),superset:1},{...exercise('A'),superset:1}]}});await b(p,'Save workout').click();await expect(b(p,'Create workout')).toBeVisible()}
async function start(p:Page) {await b(p,'Train').click();await b(p,'Existing Workout').click();await p.getByRole('article',{name:'Workout Pair',exact:true}).getByRole('button').click();await expect(p.getByRole('heading',{level:1})).toHaveText('Standalone Workout')}
for(const theme of ['Dark','Light'])test(`typing preserves DOM, focus, caret and geometry across autosave; compact Skip (${theme})`,async({page},info)=>{
 test.setTimeout(90000);await open(page,theme);await importWorkout(page);await start(page)
 for(const label of ['A occurrence 1 set 1 Weight (kg)','A occurrence 1 set 1 Repetitions','A occurrence 1 set 1 Actual RIR (optional)','B set 1 Weight (kg)','A occurrence 3 set 1 Repetitions']) {
  const input=f(page,label);await input.focus();await expect(input).toBeFocused()
  await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))))
  await input.evaluate(node=>{const w=window as any;w.retainedInput=node;w.entryTop=node.getBoundingClientRect().top;w.entryY=scrollY;w.scrollCalls=[];if(!w.originalScroll){w.originalScroll={into:Element.prototype.scrollIntoView,by:window.scrollBy,to:window.scrollTo};Element.prototype.scrollIntoView=function(...args){w.scrollCalls.push('into');return w.originalScroll.into.apply(this,args)};window.scrollBy=function(...args:any[]){w.scrollCalls.push('by');return w.originalScroll.by.apply(window,args)} as any;window.scrollTo=function(...args:any[]){w.scrollCalls.push('to');return w.originalScroll.to.apply(window,args)} as any}})
  await input.pressSequentially('0');await expect(page.locator('.draft-save-status')).toHaveText('')
  await input.pressSequentially('2');await expect(page.locator('.draft-save-status')).toHaveText('')
  const state=await input.evaluate(node=>({same:node===(window as any).retainedInput,focus:document.activeElement===node,value:(node as HTMLInputElement).value,caret:(node as HTMLInputElement).selectionStart,calls:(window as any).scrollCalls,delta:node.getBoundingClientRect().top-(window as any).entryTop,y:scrollY-(window as any).entryY}))
  expect(state).toMatchObject({same:true,focus:true,value:'02',caret:2,calls:[]});expect(Math.abs(state.delta)).toBeLessThan(2);expect(Math.abs(state.y)).toBeLessThan(2)
 }
 await waitForDraft(page);const draft=(await rows(page,'drafts'))[0];expect(draft.input.exercises[0].sets[0]).toMatchObject({load:'02',reps:'02',rir:'02'});expect(draft.input.exercises[1].sets[0].rir).toBe('')
 const skip=f(page,'Skip A occurrence 1 set 1'),row=skip.locator('xpath=ancestor::div[contains(@class,"skip-row")]');await row.scrollIntoViewIfNeeded();const box=await row.boundingBox();await row.click({position:{x:box!.width-5,y:22}});await expect(skip).not.toBeChecked();await skip.check();await expect(skip).toBeChecked();await skip.focus();await page.keyboard.press('Space');await expect(skip).not.toBeChecked()
 // Emulated viewport resizing is separate from physical software-keyboard evidence.
 await page.setViewportSize({width:390,height:440});await f(page,'A occurrence 3 set 1 Actual RIR (optional)').focus();await expect.poll(async()=>{const input=await f(page,'A occurrence 3 set 1 Actual RIR (optional)').boundingBox(),actions=await page.locator('.session-actions').boundingBox();return input!.y+input!.height<=actions!.y-7}).toBe(true)
 await b(page,'Add Exercise').scrollIntoViewIfNeeded();await expect(b(page,'Add Exercise')).toBeVisible();await b(page,'Add Exercise').click();await b(page,'Cancel selection').click();await expect(b(page,'Add Exercise')).toBeFocused();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.screenshot({path:info.outputPath('input-'+theme+'.png'),fullPage:true})
})

async function editReturn(p:Page,occurrence:Locator,apply:boolean) {
 const trigger=occurrence.getByRole('button',{name:/^Actions for/});await trigger.scrollIntoViewIfNeeded();const before=await occurrence.boundingBox();await occurrenceAction(p,occurrence,'Edit');await expect(b(p,'Merge')).toHaveCount(0);await f(p,'Exercise name').fill(apply?'Edited occurrence':'Canceled name')
 if(apply)await b(p,'Apply').last().click();else {await b(p,'Cancel').click();await p.getByRole('dialog',{name:'Discard unsaved exercise?'}).getByRole('button',{name:'Confirm',exact:true}).click()}
 await expect(trigger).toBeFocused();await expect.poll(async()=>Math.abs((await occurrence.boundingBox())!.y-before!.y)).toBeLessThan(3)
 await expect(occurrence).toContainText(apply?'Edited occurrence':'A')
}
test('parent anchors survive Apply/Cancel in Workout 4, unique weeks, standalone builders and AI previews',async({page})=>{
 test.setTimeout(120000);await open(page)
 const days=Array.from({length:4},(_,i)=>({name:'Day '+(i+1),exercises:[exercise('A')]}))
 await importPreview(page,{schemaVersion:5,kind:'plan',plan:{mode:'repeating',name:'Long plan',durationWeeks:4,trainingDaysPerWeek:4,days}})
 await f(page,'Note (optional):').fill('Unsaved parent note')
 const fourth=page.locator('.plan-day').nth(3).locator('li[data-occurrence-id]').first();await editReturn(page,fourth,false);await editReturn(page,fourth,true);await expect(f(page,'Note (optional):')).toHaveValue('Unsaved parent note');await b(page,'Save plan').click()
 await cardAction(page,page.getByRole('article',{name:'Plan Long plan',exact:true}),'Edit');await editReturn(page,page.locator('.plan-day').nth(3).locator('li[data-occurrence-id]').first(),true);await b(page,'Save plan').click()
 await importPreview(page,{schemaVersion:5,kind:'plan',plan:{mode:'unique',name:'Unique plan',durationWeeks:4,uniqueWeekCount:2,weeks:[{trainingDaysPerWeek:4,days},{trainingDaysPerWeek:4,days}]}})
 const second=page.getByRole('region',{name:'Week 2',exact:true});await editReturn(page,second.locator('.plan-day').nth(3).locator('li[data-occurrence-id]').first(),true);await expect(second.locator('.plan-day')).toHaveCount(4);await b(page,'Save plan').click()
 await importPreview(page,{schemaVersion:5,kind:'workout',workout:{name:'Long workout',exercises:Array.from({length:6},()=>exercise('A'))}})
 await editReturn(page,page.locator('.standalone-workout-builder li[data-occurrence-id]').nth(4),false);await b(page,'Save workout').click();await cardAction(page,page.getByRole('article',{name:'Workout Long workout',exact:true}),'Edit');await editReturn(page,page.locator('.standalone-workout-builder li[data-occurrence-id]').nth(4),true);await b(page,'Save workout').click()
 await b(page,'Create Plan').click();await expect(f(page,'Plan name')).toHaveValue('');expect(await page.evaluate(()=>scrollY)).toBeLessThan(250)
})

for(const theme of ['Dark','Light'])test(`merge direction, cancellation, unsaved edits, historical review and combined Progress (${theme})`,async({page},info)=>{
 test.setTimeout(90000);await open(page,theme);await importWorkout(page);await start(page)
 for(const name of ['A occurrence 1','B','A occurrence 3']) {await f(page,`${name} set 1 Weight (kg)`).fill(name==='B'?'20':'10');await f(page,`${name} set 1 Repetitions`).fill('8')}
 await openExerciseAction(page, 'B', 'Note');await f(page,'Note').fill('Recorded B note');await page.getByRole('dialog').last().getByRole('button', { name: 'Save', exact: true }).click();await waitForDraft(page);await b(page,'Save').click();await expect(page.getByRole('region',{name:'Saved session details'})).toBeVisible()
 const before=await rows(page,'sessions'),workouts=await rows(page,'workouts');await b(page,'Create').click();await cardAction(page,page.getByRole('article',{name:'A',exact:true}),'Edit');await f(page,'Instructions (optional)').fill('Unapplied A edit');const old=await rows(page,'exercises')
 await b(page,'Merge').click();const picker=page.getByRole('dialog',{name:'Merge exercise',exact:true});await expect(picker.getByRole('button',{name:'Merge',exact:true})).toBeDisabled();await expect(picker.locator('.exercise-selection-card')).toHaveCount(1);await picker.locator('.exercise-selection-card').click();await picker.getByRole('button',{name:'Cancel',exact:true}).click();expect(await rows(page,'exercises')).toEqual(old);await expect(f(page,'Instructions (optional)')).toHaveValue('Unapplied A edit')
 await b(page,'Merge').click();await picker.locator('.exercise-selection-card').click();await picker.getByRole('button',{name:'Merge',exact:true}).click();const confirm=page.getByRole('dialog',{name:'Merging Exercises?',exact:true});await expect(confirm).toContainText('Merge: A');await expect(confirm).toContainText('Into: B');await confirm.getByRole('button',{name:'Switch',exact:true}).click();await expect(confirm).toContainText('Merge: B');await expect(confirm).toContainText('Into: A');await confirm.getByRole('button',{name:'Switch',exact:true}).click();expect(await rows(page,'exercises')).toEqual(old)
 await confirm.getByRole('button',{name:'Cancel',exact:true}).click();await expect(picker.getByRole('button',{name:'Merge',exact:true})).toBeFocused();await expect(picker.locator('[aria-pressed=true]')).toHaveCount(1);await picker.getByRole('button',{name:'Merge',exact:true}).click();await confirm.getByRole('button',{name:'Merge',exact:true}).click()
 await expect(page.getByRole('dialog',{name:'B',exact:true})).toBeVisible();await b(page,'Close').click();await expect(page.getByRole('region',{name:'Exercise catalog'}).getByRole('article')).toHaveCount(1)
 const after=await rows(page,'exercises'),a=after.find(e=>e.name==='A'),bb=after.find(e=>e.name==='B');expect(a.mergedIntoId).toBe(bb.id);expect(a.instructions).toBe('Unapplied A edit');expect(bb.sets).toEqual(old.find(e=>e.name==='B').sets);expect(await rows(page,'sessions')).toEqual(before);expect(await rows(page,'workouts')).toEqual(workouts)
 await b(page,'Calendar').click();await page.locator('.calendar-event').filter({hasText:'Pair'}).click();await page.getByRole('dialog',{name:'Completed workout'}).getByRole('button',{name:'Note for B',exact:true}).click();await expect(page.getByRole('dialog').last()).toContainText('Recorded B note');await b(page,'Close note').click();await b(page,'Close').click()
 await b(page,'Progress').click();await page.getByRole('button',{name:'B',exact:true}).click();await expect(page.getByRole('region',{name:'Exercise analytics'})).toContainText('Overall');await expect(page.getByText('Times Completed',{exact:true}).locator('..')).toContainText('3');await expect(page.getByText('Weight Max',{exact:true}).locator('..')).toContainText('20 kg');await expect(page.getByText('Weight Min',{exact:true}).locator('..')).toContainText('10 kg');await expect(page.getByRole('region',{name:'Exercise analytics'})).not.toContainText('undefined');await page.getByRole('button',{name:'Weight Max: 20 kg',exact:true}).click();await expect(page.getByRole('dialog',{name:'Weight Max',exact:true})).toContainText('Pair');await b(page,'Close').click()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('merge-'+theme+'.png'),fullPage:true});await page.reload();await b(page,'Create').click();await expect(page.getByRole('region',{name:'Exercise catalog'}).getByRole('article')).toHaveCount(1)
})
test('stale merge rejects without writes; another tab keeps active inputs through a successful merge',async({page,context})=>{
 test.setTimeout(90000);await open(page);await importWorkout(page);await cardAction(page,page.getByRole('article',{name:'A',exact:true}),'Edit');await f(page,'Instructions (optional)').fill('Local kept');await b(page,'Merge').click()
 const picker=page.getByRole('dialog',{name:'Merge exercise',exact:true});await picker.locator('.exercise-selection-card').click();await picker.getByRole('button',{name:'Merge',exact:true}).click()
 const peer=await context.newPage();await peer.goto('./');await b(peer,'Create').click();await cardAction(peer,peer.getByRole('article',{name:'A',exact:true}),'Edit');await f(peer,'Instructions (optional)').fill('Peer saved');await b(peer,'Save').click();await expect(peer.getByRole('article',{name:'A',exact:true})).toBeVisible()
 const confirm=page.getByRole('dialog',{name:'Merging Exercises?',exact:true});await confirm.getByRole('button',{name:'Merge',exact:true}).click();await expect(confirm.getByRole('alert')).toContainText('another tab');expect((await rows(page,'exercises')).some(e=>e.mergedIntoId)).toBe(false)
 await confirm.getByRole('button',{name:'Cancel',exact:true}).click();await picker.getByRole('button',{name:'Cancel',exact:true}).click();await expect(f(page,'Instructions (optional)')).toHaveValue('Local kept');await b(page,'Cancel').click();await b(page,'Confirm').click()
 await start(peer);const live=f(peer,'A occurrence 1 set 1 Weight (kg)');await live.fill('0');await live.evaluate(node=>(window as any).liveInput=node)
 await cardAction(page,page.getByRole('article',{name:'A',exact:true}),'Edit');await b(page,'Merge').click();await picker.locator('.exercise-selection-card').click();await picker.getByRole('button',{name:'Merge',exact:true}).click();await confirm.getByRole('button',{name:'Merge',exact:true}).click();await expect(page.getByRole('dialog',{name:'B',exact:true})).toBeVisible()
 await expect(live).toBeFocused();expect(await live.evaluate(node=>node===(window as any).liveInput)).toBe(true);await live.pressSequentially('2');await expect(live).toHaveValue('02');await waitForDraft(peer);expect((await rows(peer,'exercises')).filter(e=>!e.mergedIntoId)).toHaveLength(1);await peer.close()
})
test('merge picker selects one eligible record, combines filters and cancels without writes',async({page},info)=>{
 await open(page);await importWorkout(page);for(const name of ['C','Archived']){await importPreview(page,{schemaVersion:5,kind:'exercise',exercise:exercise(name)});await b(page,'Save').click()}
 await cardAction(page,page.getByRole('article',{name:'Archived',exact:true}),'Archive');await page.getByRole('dialog',{name:'Archive exercise?'}).getByRole('button',{name:'Archive',exact:true}).click();await expect(page.getByRole('article',{name:'Archived',exact:true})).toHaveCount(0)
 await cardAction(page,page.getByRole('article',{name:'A',exact:true}),'Edit');await f(page,'Exercise name').fill('A local');const before=await rows(page,'exercises');await b(page,'Merge').click();const picker=page.getByRole('dialog',{name:'Merge exercise',exact:true}),cards=picker.locator('.exercise-selection-card');await expect(cards).toHaveCount(2)
 await cards.filter({hasText:/^B/}).click();await cards.filter({hasText:/^C/}).click();await expect(picker.locator('.exercise-selection-card[aria-pressed=true]')).toHaveCount(1)
 await picker.getByLabel('Sort exercises to add',{exact:true}).selectOption('za');await picker.getByLabel('Search exercises to add',{exact:true}).fill('C');await picker.getByRole('button',{name:'Tags',exact:true}).click();await picker.locator('.tag-scroll').getByRole('button',{name:'Shared',exact:true}).click();await expect(cards).toHaveCount(1);await picker.getByRole('button',{name:'Merge',exact:true}).click();const confirmation=page.getByRole('dialog',{name:'Merging Exercises?',exact:true});await expect(confirmation).toContainText('Into: C');await expect(confirmation).toContainText('Merge: A local');await page.screenshot({path:info.outputPath('merge-confirmation.png')});await page.keyboard.press('Escape');await expect(picker.getByRole('button',{name:'Merge',exact:true})).toBeFocused();await picker.getByRole('button',{name:'Cancel',exact:true}).click();await expect(f(page,'Exercise name')).toHaveValue('A local');expect(await rows(page,'exercises')).toEqual(before)
})
