import { openWorkoutNote, setWorkoutNote } from './train-actions'
import { test, expect, type Page } from '@playwright/test'
import { cardAction } from './create-actions'
const b=(p:Page,n:string)=>p.getByRole('button',{name:n,exact:true})
const f=(p:Page,n:string)=>p.getByLabel(n,{exact:true})
const exercise=(name:string,activeSeconds:number,recoverySeconds:number)=>({name,activeSeconds,recoverySeconds})
const workout={name:'Sprint Madness',circuits:[{name:'Starting slow',repeat:1,restAfterCircuitSeconds:30,exercises:[exercise('Push-up',20,10),exercise('Sprint',20,10),exercise('Pull-up',10,20)]},{name:'Sprint madness',repeat:0,restAfterCircuitSeconds:30,exercises:[exercise('High knees',50,10),exercise('Backwards jog',50,10),exercise('Full sprint',20,10)]}],postWorkoutRestSeconds:60}
async function open(p:Page){await p.goto('./');if(await b(p,'Understood').isVisible())await b(p,'Understood').click();await b(p,'Create').click()}
async function importWorkout(p:Page,value=workout){await b(p,'Import').click();await f(p,'AI output JSON').fill(JSON.stringify({schemaVersion:8,kind:'workout',trainingType:'interval',workout:value}));await b(p,'Validate and preview').click();await expect(f(p,'Repeat circuit').first()).toHaveValue(String(value.circuits[0].repeat));await expect(f(p,'Sets')).toHaveCount(0);await expect(f(p,'Rounds per set')).toHaveCount(0);await b(p,'Save workout').click();await expect(p.getByRole('article',{name:'Workout '+value.name,exact:true})).toBeVisible()}
async function train(p:Page){await b(p,'Train').click();await b(p,'Existing Workout').click();await p.getByRole('article',{name:'Workout Sprint Madness',exact:true}).getByRole('button').click();await expect(f(p,'Continuous workout')).toBeEnabled()}
async function tick(p:Page,ms:number){await expect(p.locator('.interval-timer-main').getByRole('button',{name:'Pause',exact:true})).toBeEnabled();await p.clock.fastForward(ms);await p.waitForTimeout(350)}
async function rows(p:Page,store:string){return p.evaluate(async store=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('boros');r.onupgradeneeded=()=>r.transaction!.abort();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});try{return await new Promise<any[]>((resolve,reject)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}finally{db.close()}},store)}

test('exact repeated execution, ring resets, stable focused buttons, synchronized timer and explicit Save',async({page},info)=>{
 await open(page);await importWorkout(page);await train(page);await page.clock.install({time:new Date()});await f(page,'Continuous workout').check()
 await expect(page.getByText('2nd',{exact:true})).toHaveCount(1);await expect(page.getByText('Push-up',{exact:true})).toHaveCount(2)
 const start=await b(page,'Start').first().boundingBox();expect(start!.width).toBeGreaterThan(200)
 await b(page,'Start').first().click();await expect(page.locator('.interval-timer-main h3')).toHaveText('Warm Up');await expect(page.getByRole('timer')).toContainText('/ 00:10')
 await b(page,'Pause').focus()
 await page.evaluate(()=>{const node=document.querySelector('.interval-timer-main .actions button')!;Object.assign(window,{stableTimerButton:node,disabledChanges:0});new MutationObserver(changes=>{(window as any).disabledChanges+=changes.length}).observe(node,{attributes:true,attributeFilter:['disabled']})})
 await tick(page,10000);await expect(page.getByRole('timer')).toContainText('/ 01:30');await expect(b(page,'Pause')).toBeFocused()
 await tick(page,20000);await expect(page.locator('.interval-timer-main h3')).toHaveText('Rest');await expect(page.locator('.interval-timer-main p')).toHaveText('Next: Sprint')
 expect(await page.evaluate(()=>({same:(window as any).stableTimerButton===document.querySelector('.interval-timer-main .actions button'),disabled:(window as any).disabledChanges}))).toEqual({same:true,disabled:0})
 await tick(page,70000);await expect(page.getByRole('timer')).toContainText('/ 00:30');await expect(page.locator('.interval-timer-main p')).toHaveText('Next: Push-up')
 await tick(page,30000);await expect(page.locator('.interval-timer-main h3')).toHaveText('Push-up');await expect(page.getByRole('timer')).toContainText('/ 01:30');expect(parseFloat((await page.locator('.interval-timer-main .timer-progress').getAttribute('stroke-dasharray'))!)).toBeLessThan(.06)
 await tick(page,90000);await expect(page.locator('.interval-timer-main p')).toHaveText('Next: High knees');await expect(page.getByRole('timer')).toContainText('/ 00:30')
 await tick(page,30000);await expect(page.locator('.interval-timer-main h3')).toHaveText('High knees');await expect(page.getByRole('timer')).toContainText('/ 02:30')
 await page.evaluate(()=>scrollTo(0,document.documentElement.scrollHeight));await page.clock.runFor(50);await b(page,'Pause timer').click();const paused=await page.getByRole('timer').textContent();await b(page,'Open timer').click();const modal=page.getByRole('dialog',{name:'Timer',exact:true});await expect(modal.getByRole('timer')).toHaveText(paused!);await modal.getByRole('button',{name:'Start',exact:true}).click();await modal.getByRole('button',{name:'Close',exact:true}).click()
 await tick(page,140000);await expect(page.locator('.interval-sticky-title')).toHaveText('Rest');await expect(page.locator('.interval-sticky-time')).toContainText('/ 08:00')
 await tick(page,10000);await expect(page.locator('.interval-sticky-time')).toContainText('/ 08:00');await tick(page,30000);await b(page,'Open timer').click();await expect(modal.getByRole('timer')).toContainText('/ 01:00');await expect(modal.getByText('Next: Workout Complete!',{exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('repeated-post-rest.png')});await modal.getByRole('button',{name:'Close',exact:true}).click();await tick(page,60000)
 await expect(page.getByRole('status').filter({hasText:'Ready to save'})).toBeVisible();expect(await rows(page,'sessions')).toHaveLength(0)
 const draft=(await rows(page,'drafts'))[0];expect(draft.interval.results.filter((r:any)=>r.phase.kind==='active')).toHaveLength(9);expect(draft.interval.results.filter((r:any)=>r.phase.kind==='circuit-rest')).toHaveLength(3)
 await b(page,'Save').click();await expect(page.getByRole('region',{name:'Saved Interval session'})).toContainText('Complete session');await b(page,'Calendar').click();await page.locator('.calendar-event').filter({hasText:'Sprint Madness'}).first().click();await expect(page.getByRole('dialog')).toContainText('Repeat 1')
})

test('navigation, Warm Up and Stop preserve ownership; explicit Cancel removes the workout and notes still confirm',async({page})=>{
 await open(page);await importWorkout(page);await train(page);const original=(await rows(page,'drafts'))[0]
 await b(page,'Create').click();await expect(page.getByRole('dialog')).toHaveCount(0);expect(await rows(page,'drafts')).toHaveLength(1);await b(page,'Train').click();await expect(b(page,'Existing Workout')).toHaveCount(0)
 await page.clock.install({time:new Date()});const one=page.getByRole('region',{name:'Starting slow',exact:true}),two=page.getByRole('region',{name:'Sprint madness',exact:true})
 await one.getByRole('button',{name:'Start Circuit',exact:true}).click();await tick(page,1000);await b(page,'Create').click();await b(page,'Train').click();expect((await rows(page,'drafts'))[0].id).toBe(original.id);await b(page,'Stop').click();expect(await rows(page,'activeWorkouts')).toHaveLength(1)
 await one.getByRole('button',{name:'Start Circuit',exact:true}).click();await tick(page,11000);await setWorkoutNote(page,'Protect this note');await b(page,'Stop').click();await b(page,'Cancel').click();await expect(page.getByRole('dialog',{name:'Leave workout?',exact:true})).toBeVisible();await page.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click();await openWorkoutNote(page);await expect(f(page,'Note')).toHaveValue('Protect this note');await f(page,'Note').fill('');await page.getByRole('dialog').getByRole('button',{name:'Save',exact:true}).click()
 await one.getByRole('button',{name:'Start Circuit',exact:true}).click();await tick(page,250000);await expect(page.getByRole('status').filter({hasText:'Ready to save'})).toBeVisible();await two.getByRole('button',{name:'Start Circuit',exact:true}).click();await tick(page,11000);await b(page,'Stop').click();expect((await rows(page,'drafts'))[0].interval.results.every((r:any)=>r.phase.circuitName==='Starting slow')).toBe(true)
 await b(page,'Create').click();await b(page,'Train').click();expect((await rows(page,'drafts'))[0].id).toBe(original.id);await b(page,'Cancel').click();await b(page,'Confirm').click();expect(await rows(page,'drafts')).toHaveLength(0);expect(await rows(page,'activeWorkouts')).toHaveLength(0)
})

test('type titles, long card containment, shared icons, compact desktop and neutral Archive focus in both themes',async({page},info)=>{
 await open(page)
 for(const type of ['Plan','Workout','Exercise']){await b(page,type==='Plan'?'Create Plan':'Create '+type.toLowerCase()).click();const title=page.getByRole('dialog').getByRole('heading',{name:type+' Type',exact:true});await expect(title).toBeVisible();expect(await title.evaluate(e=>getComputedStyle(e).textAlign)).toBe('center');await b(page,'Cancel').click()}
 const name='A very long workout name that wraps beyond two lines but keeps its complete added date visible',value={...workout,name};await importWorkout(page,value)
 for(const theme of ['Dark','Light']){if(info.project.name.includes('phone')&&theme==='Light')await page.setViewportSize({width:320,height:720});await b(page,'Settings').click();await b(page,theme).click();await b(page,'Create').click();const card=page.getByRole('article',{name:'Workout '+name,exact:true}).getByRole('button');const geometry=await card.evaluate(e=>{const r=e.getBoundingClientRect(),date=e.querySelector('small')!.getBoundingClientRect(),text=e.querySelector('.card-name')!,grid=e.closest('.workout-library-grid')!;return {inside:date.bottom<=r.bottom&&date.right<=r.right&&date.left>=r.left,clamp:getComputedStyle(text).webkitLineClamp,padding:getComputedStyle(e).padding,columns:getComputedStyle(grid).gridTemplateColumns.split(' ').length,icon:e.querySelector('svg')!.getBoundingClientRect().width,height:r.height}});expect(geometry.inside).toBe(true);expect(geometry.clamp).toBe('2');expect(geometry.padding).toBe('10px');expect(geometry.icon).toBe(18);expect(geometry.columns).toBe(info.project.name.includes('phone')?3:5);if(info.project.name.includes('phone'))expect(geometry.height).toBeGreaterThanOrEqual(110)
 await cardAction(page,page.getByRole('article',{name:'Workout '+name,exact:true}),'Edit');await expect(f(page,'Repeat circuit').first()).toHaveValue('1');await b(page,'Cancel').click();await card.click();await b(page,'Workout actions').click();const archive=b(page,'Archive');await archive.focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');expect(await archive.evaluate(e=>getComputedStyle(e).color!==getComputedStyle(e).borderTopColor)).toBe(true);expect(await archive.evaluate(e=>getComputedStyle(e).outlineStyle)).not.toBe('none');await page.screenshot({path:info.outputPath('cards-'+theme+'.png')});await page.keyboard.press('Escape');await b(page,'Close').click()}
})

for(const type of ['strength','interval'] as const)test(type+' deep AI workout/unique plan pickers restore origin after single/multiple additions and cancel',async({page})=>{
 await open(page)
 const items=Array.from({length:9},(_,i)=>type==='interval'?exercise('Deep '+i,20,10):{name:'Deep '+i,sets:[{reps:{min:5,max:5}}]})
 const day=type==='interval'?{name:'Deep day',circuits:[{name:'Deep circuit',repeat:0,restAfterCircuitSeconds:0,exercises:items}]}:{name:'Deep day',exercises:items}
 await b(page,'Import').click();await f(page,'AI output JSON').fill(JSON.stringify({schemaVersion:8,trainingType:type,kind:'workout',workout:{...day,name:'Library seed'}}));await b(page,'Validate and preview').click();await b(page,'Save workout').click();await expect(page.getByRole('article',{name:'Workout Library seed',exact:true})).toBeVisible()
 for(const mode of ['workout','repeating','unique'] as const){const kind=mode==='workout'?'workout':'plan';await b(page,'Import').click();await f(page,'AI output JSON').fill(JSON.stringify({schemaVersion:8,trainingType:type,kind,...(kind==='workout'?{workout:day}:{plan:mode==='repeating'?{mode:'repeating',name:'Deep plan',durationWeeks:4,trainingDaysPerWeek:1,days:[day]}:{mode:'unique',name:'Deep plan',durationWeeks:4,uniqueWeekCount:2,weeks:[{trainingDaysPerWeek:1,days:[day]},{trainingDaysPerWeek:1,days:[{...day,name:'Deep second'}]}]}})}));await b(page,'Validate and preview').click();await expect(f(page,kind==='workout'?'Workout name':'Plan name')).toBeVisible()
 const add=page.getByRole('button',{name:'Add exercise',exact:true}).last();for(const action of ['single','multiple','cancel']){await add.scrollIntoViewIfNeeded();const before=(await add.boundingBox())!.y;await add.click();const picker=page.getByRole('region',{name:'Choose exercise',exact:true});await expect(picker).toBeVisible();if(action==='cancel')await b(page,'Cancel selection').click();else if(action==='single')await b(page,'Add Deep 0').click();else{await picker.getByRole('checkbox',{name:'Deep 1',exact:true}).check();await picker.getByRole('checkbox',{name:'Deep 2',exact:true}).check();await b(page,'Add selected').click()}await expect(picker).toHaveCount(0);await expect(add).toBeFocused();expect(Math.abs((await add.boundingBox())!.y-before)).toBeLessThan(8);expect(await page.evaluate(()=>scrollY)).toBeGreaterThan(200)}
 await b(page,'Cancel').click();const confirm=page.getByRole('dialog');if(await confirm.isVisible())await confirm.getByRole('button',{name:kind==='workout'?'Leave':'Confirm',exact:true}).click();await expect(f(page,'AI output JSON')).toBeVisible();await b(page,'Close').click();await b(page,'Discard').click();await expect(b(page,'Import')).toBeVisible()}
})
