import {test,expect,type Page} from '@playwright/test'
const b=(p:Page,n:string)=>p.getByRole('button',{name:n,exact:true})
test('trailing Plan icons, independent Train gaps and exactly shared Strength/Interval action geometry',async({page},info)=>{
 await page.goto('./');await b(page,'Create').click();if(await b(page,'Understood').isVisible())await b(page,'Understood').click()
 for(const name of ['One','Two','Three']){await b(page,'Import').click();await page.getByLabel('AI output JSON',{exact:true}).fill(JSON.stringify({schemaVersion:8,trainingType:'strength',kind:'plan',plan:{mode:'repeating',name,durationWeeks:4,trainingDaysPerWeek:1,days:[{name:'Day',exercises:[{name:'Press',sets:[{reps:{min:5,max:5}}]}]}]}}));await b(page,'Validate and preview').click();await b(page,'Save plan').click();await expect(page.getByRole('article',{name:'Plan '+name,exact:true})).toBeVisible()}
 for(const card of await page.locator('.plan-card strong').all()){expect(await card.evaluate(e=>{const name=e.querySelector('.card-name')!,icon=e.querySelector('.training-type-icon')!;return icon.previousElementSibling===name&&icon.getBoundingClientRect().left>=name.getBoundingClientRect().right&&icon.getBoundingClientRect().width===18})).toBe(true)}
 await b(page,'Train').click();for(const name of ['One','Two','Three']){await b(page,'Add Plan').click();await page.getByRole('dialog').getByRole('article',{name:'Plan '+name,exact:true}).getByRole('button').click();await expect(page.getByRole('dialog')).toHaveCount(0)}
 const grid=page.locator('.train-plan-cards');expect(await grid.evaluate(e=>getComputedStyle(e).rowGap)).toBe('8px');expect(await b(page,'Add Plan').evaluate(e=>getComputedStyle(e).marginTop)).toBe('24px');expect(await grid.locator('article').count()).toBe(3)
 await page.screenshot({path:info.outputPath('train-plan-spacing.png'),fullPage:true})
 const geometry=()=>page.locator('.session-actions').evaluate(e=>Array.from(e.querySelectorAll('button')).map(b=>{const r=b.getBoundingClientRect(),s=getComputedStyle(b);return {name:b.textContent,x:r.x,y:r.y,width:r.width,height:r.height,padding:s.padding,color:s.color,background:s.backgroundColor,border:s.border,radius:s.borderRadius}}))
 await b(page,'Custom Workout').click();await b(page,'Strength').click();await expect(b(page,'Save')).toBeVisible();const strength=await geometry();expect(strength.map(v=>v.name)).toEqual(['Save','Cancel','Clear']);expect(strength[0].y).toBeLessThan(strength[1].y);expect(strength[1].y).toBe(strength[2].y);await b(page,'Cancel').click();await expect(b(page,'Custom Workout')).toBeVisible()
 await b(page,'Custom Workout').click();await expect(b(page,'Interval')).toBeDisabled();await b(page,'Cancel').click()
 await b(page,'Create').click();await b(page,'Import').click();await page.getByLabel('AI output JSON',{exact:true}).fill(JSON.stringify({schemaVersion:8,trainingType:'interval',kind:'workout',workout:{name:'Footer intervals',circuits:[{name:'Circuit',repeat:0,restAfterCircuitSeconds:0,exercises:[{name:'Sprint',activeSeconds:20,recoverySeconds:0}]}]}}));await b(page,'Validate and preview').click();await b(page,'Save workout').click();await b(page,'Train').click();await b(page,'Existing Workout').click();await page.getByRole('article',{name:'Workout Footer intervals',exact:true}).getByRole('button').click();await expect(b(page,'Edit pending exercises')).toHaveCount(0);const interval=await geometry();expect(interval.map(({y:_y,...style})=>style)).toEqual(strength.map(({y:_y,...style})=>style));await page.screenshot({path:info.outputPath('interval-shared-footer.png'),fullPage:true})
})
