import { cardAction, occurrenceAction } from './create-actions'
import { expect, test, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import JSZip from 'jszip'

test.setTimeout(120000)
const button = (p: Page, name: string) => p.getByRole('button', { name, exact: true })
const field = (p: Page, name: string) => ['Active profile', 'Weight unit', 'Training days per week', 'Schedule plan', 'Import choice'].includes(name) ? p.getByRole('combobox', { name, exact: true }) : p.getByLabel(name, { exact: true })
const planCard = (p: Page, name: string) => p.getByRole('article', { name: `Plan ${name}`, exact: true })
async function download(p: Page) {
  await p.getByRole('checkbox', { name: 'I understand this exports saved data only.' }).check()
  const ready = p.waitForEvent('download'); await button(p, 'Download data').click()
  const bytes = await readFile((await (await ready).path())!)
  const zip = await JSZip.loadAsync(bytes, { checkCRC32: true })
  return { bytes, zip, data: JSON.parse(await zip.file('data.json')!.async('string')) }
}
async function schedule(p: Page, name: string) {
  await button(p, 'Calendar').click(); await button(p, 'Week').click(); await button(p, 'Add Plan').click()
  await field(p, 'Schedule plan').selectOption({ label: name })
  await field(p, 'Starting week (Monday)').fill('2025-01-06')
  await button(p, 'Preview schedule').click(); await button(p, 'Confirm schedule').click()
  await expect(p.getByRole('article', { name: `Schedule ${name}`, exact: true })).toBeVisible()
  await field(p, 'Calendar date').fill('2025-01-06')
}
async function note(p: Page, name: string, text: string) {
  await button(p, name).click(); await field(p, 'Note').fill(text); await button(p, 'Apply note').click()
}

for (const withoutNativeUUID of [false, true]) test(`complete manual and AI journey, immutable history, saved draft, photos and semantic restore with network audit${withoutNativeUUID ? ' without native randomUUID' : ''}`, async ({ page, context }, info) => {
  await context.route('https://www.youtube.com/embed/**', (route) => route.fulfill({ contentType: 'text/html', body: '<button>Simulated player</button>' }))
  if (withoutNativeUUID) await context.addInitScript(() => Object.defineProperty(crypto, 'randomUUID', { value: undefined, configurable: true }))
  page.setDefaultTimeout(15000)
  const requests: string[] = [], errors: string[] = []
  context.on('request', (r) => { if (/^https?:/.test(r.url())) requests.push(r.url()) })
  page.on('pageerror', (e) => errors.push(e.message))
  await page.clock.setFixedTime(new Date('2025-01-08T15:00:00Z'))
  await page.goto('./'); const address = page.url()
  await button(page, 'Settings').click()
  if (await button(page, 'Understood').isVisible()) await button(page, 'Understood').click()
  const guest = await field(page, 'Active profile').inputValue()
  await page.locator('input[name="name"]').fill('Journey Ada with a deliberately long profile name')
  await field(page, 'Weight unit').selectOption('lb')
  await button(page, 'Save profile').click(); await expect(page.getByText('Profile saved.', { exact: true })).toBeVisible()
  expect(await field(page, 'Active profile').inputValue()).toBe(guest)
  await field(page, 'New profile name').fill('Untouched neighbour'); await button(page, 'Create profile').click()
  await expect(page.locator('input[name="name"]')).toHaveValue('Untouched neighbour')
  const other = await download(page)
  await field(page, 'Active profile').selectOption(guest)
  await button(page, 'Create').click(); await button(page, 'Create exercise').click()
  await field(page, 'Exercise name').fill('Journey squat')
  await field(page, 'Number of sets').fill('3'); await button(page, 'Apply').click()
  for (let i = 1; i <= 3; i++) {
    await field(page, `Set ${i} Reps minimum`).fill(String(i + 4))
    await field(page, `Set ${i} RIR minimum (optional)`).fill(String(i - 1))
  }
  await field(page, 'Set 3 Reps maximum (optional)').fill('9')
  await field(page, 'Rest between sets (optional) seconds').fill('30')
  await field(page, 'Rest after exercise (optional) seconds').fill('0')
  await field(page, 'Instructions (optional)').fill('<b>Plain instructions</b>')
  await field(page, 'YouTube tutorial URL (optional)').fill('https://youtu.be/abcdefghijk')
  await field(page, 'New tag').fill('Journey legs'); await button(page, 'Add').click()
  await button(page, 'Save exercise').click(); await expect(page.getByRole('article', { name: 'Journey squat', exact: true })).toBeVisible()
  await button(page, 'Create Plan').click(); await field(page, 'Plan name').fill('Manual four'); await field(page, 'Duration (weeks)').fill('104')
  await field(page, 'Training days per week').selectOption('4')
  for (let i = 0; i < 4; i++) {
    await page.locator('.plan-day').nth(i).getByRole('button', { name: 'Add exercise', exact: true }).click()
    await button(page, 'Add Journey squat').click()
  }
  await button(page, 'Save plan').click(); await expect(planCard(page, 'Manual four')).toBeVisible()
  await schedule(page, 'Manual four')
  await page.locator('.calendar-event').filter({ hasText: 'Manual four / Day 1' }).click()
  await note(page, 'Session Note', 'Session <script>inert</script> note')
  await note(page, 'Note for Journey squat', 'Knee felt good')
  await button(page, 'Information for Journey squat').click()
  await expect(page.getByRole('dialog')).toContainText('<b>Plain instructions</b>')
  await expect(page.getByRole('link', { name: 'Open YouTube tutorial' })).toHaveAttribute('href', 'https://youtu.be/abcdefghijk')
  // Intercept only an explicitly opened external tab; no real third-party request.
  await context.route('https://youtu.be/**', (route) => route.fulfill({ contentType: 'text/html', body: '<title>Explicit tutorial</title>' }))
  expect(requests.every((url) => new URL(url).origin === new URL(address).origin)).toBe(true)
  const popup = page.waitForEvent('popup'); await page.getByRole('link', { name: 'Open YouTube tutorial' }).click(); await (await popup).close()
  await button(page, 'Close').click()
  for (let i = 1; i <= 3; i++) {
    await field(page, `Journey squat set ${i} Weight (lb)`).fill(String((i - 1) * 50))
    await field(page, `Journey squat set ${i} Repetitions`).fill(String(i + 4))
    await field(page, `Journey squat set ${i} Actual RIR (optional)`).fill(String(i - 1))
  }
  await button(page, 'REST Journey squat after set 1').click()
  await expect(page.getByRole('region', { name: 'Rest timer' })).toContainText('30 seconds configured'); await button(page, 'Stop timer').click()
  await button(page, 'Save').click(); await expect(page.getByRole('region', { name: 'Saved session details' })).toContainText('Complete session')
  await button(page, 'Calendar').click(); await button(page, 'Week').click(); await field(page, 'Calendar date').fill('2025-01-06')
  await expect(page.locator('.calendar-event.completed')).toHaveCount(1)
  await button(page, 'Next period').click(); await expect(page.locator('.calendar-event.completed')).toHaveCount(0)
  await button(page, 'Create').click()
  await cardAction(page, page.getByRole('article', { name: 'Journey squat', exact: true }), 'Edit')
  await field(page, 'Set 1 Reps minimum').fill('15'); await button(page, 'Save exercise').click()
  await cardAction(page, planCard(page, 'Manual four'), 'Edit')
  await occurrenceAction(page, page.locator('.plan-day').first(), 'Edit')
  await field(page, 'Exercise name').fill('Edited plan squat'); await page.locator('.exercise-editor button[type=submit]').click(); await button(page, 'Save plan').click()
  await expect(planCard(page, 'Manual four')).toBeVisible()
  await button(page, 'Import AI Output').click()
  await field(page, 'AI output JSON').fill(JSON.stringify({ schemaVersion: 1, kind: 'plan', plan: { name: 'AI plan', trainingDaysPerWeek: 1, days: [{ name: 'AI day', exercises: [{ name: 'AI row', sets: [{ reps: { min: 8, max: 12 } }], tags: ['Back'] }] }] } }))
  await button(page, 'Validate and preview').click()
  await field(page, 'Duration (weeks)').fill('104')
  await occurrenceAction(page, page.locator('.plan-day').first(), 'Edit')
  await field(page, 'Set 1 Reps minimum').fill('9'); await page.locator('.exercise-editor button[type=submit]').click(); await button(page, 'Save plan').click()
  await expect(planCard(page, 'AI plan')).toBeVisible(); await schedule(page, 'AI plan')
  await page.locator('.calendar-event').filter({ hasText: 'AI plan / AI day' }).click()
  await field(page, 'AI row set 1 Weight (lb)').fill('50'); await field(page, 'AI row set 1 Repetitions').fill('10')
  await note(page, 'Session Note', 'AI uses the shared history'); await button(page, 'Save').click()
  await expect(page.getByRole('region', { name: 'Saved session details' })).toContainText('AI uses the shared history')
  await button(page, 'Calendar').click(); await button(page, 'Week').click(); await field(page, 'Calendar date').fill('2025-01-06')
  await page.locator('.calendar-event').filter({ hasText: 'Manual four / Day 3' }).click()
  await field(page, 'Journey squat set 1 Weight (lb)').fill('12.')
  await note(page, 'Session Note', 'Resume me after restore')
  await expect(page.getByText('Draft saved locally.', { exact: true })).toBeVisible()
  await button(page, 'Progress').click(); await button(page, 'Add measurement').click()
  await field(page, 'Weight (lb)').fill('150'); await field(page, 'Measurement date/time').fill('2025-01-08T10:00')
  const photo = await page.evaluate(() => { const c = document.createElement('canvas'); c.width = 640; c.height = 480; c.getContext('2d')!.fillRect(0, 0, 640, 480); return c.toDataURL('image/jpeg').split(',')[1] })
  await field(page, 'Progress photo (optional)').setInputFiles({ name: 'progress <plain>.jpg', mimeType: 'image/jpeg', buffer: Buffer.from(photo, 'base64') })
  await button(page, 'Save measurement').click(); await expect(page.getByText('Measurement saved.', { exact: true })).toBeVisible()
  await button(page, 'Settings').click(); await expect(field(page, 'Weight (lb, optional)')).toHaveValue('150')
  await button(page, 'Light').click()
  const source = await download(page)
  expect(source.data.plans).toHaveLength(2); expect(source.data.sessions).toHaveLength(2); expect(source.data.schedules).toHaveLength(2)
  expect(source.data.sessions.find((s) => s.planName === 'Manual four')?.day.exercises[0].prescription.name).toBe('Journey squat')
  await field(page, 'Backup ZIP').setInputFiles({ name: 'journey.zip', mimeType: 'application/zip', buffer: source.bytes })
  await expect(page.getByRole('heading', { name: /^Validated backup:/ })).toBeVisible()
  await field(page, 'Import choice').selectOption('new'); await field(page, 'Imported profile name').fill('Restored journey')
  await button(page, 'Preview import').click(); await page.getByRole('checkbox', { name: /^I confirm/ }).check(); await button(page, 'Confirm and save').click()
  await expect(page.getByText(/Changes are saved locally\./)).toBeVisible(); await page.reload()
  await expect(page.locator('input[name="name"]')).toHaveValue('Restored journey')
  const restored = await download(page)
  const normalize = (data) => ({ ...data, profile: { ...data.profile, id: 'owner', name: 'name', nameKey: 'name' }, ...Object.fromEntries(['tags', 'exercises', 'plans', 'schedules', 'drafts', 'sessions', 'measurements', 'assets'].map((key) => [key, data[key].map((r) => ({ ...r, profileId: 'owner' }))])) })
  expect(normalize(restored.data)).toEqual(normalize(source.data))
  for (const asset of source.data.assets) expect(await restored.zip.file(asset.path)!.async('uint8array')).toEqual(await source.zip.file(asset.path)!.async('uint8array'))
  await button(page, 'Train').click(); await page.getByRole('button', { name: /Resume Manual four \/ Day 3/ }).click()
  await expect(field(page, 'Journey squat set 1 Weight (lb)')).toHaveValue('12.')
  await button(page, 'Session Note').click(); await expect(field(page, 'Note')).toHaveValue('Resume me after restore'); await page.keyboard.press('Escape')
  await button(page, 'Progress').click(); await button(page, 'View progress photo').click(); await expect(page.getByAltText('Saved progress photo')).toBeVisible()
  await page.keyboard.press('Escape'); await expect(button(page, 'View progress photo')).toBeFocused()
  await page.setViewportSize({ width: 320, height: 740 }); await page.addStyleTag({ content: 'html { font-size: 24px; }' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('journey-large-text.png'), fullPage: true })
  await button(page, 'Edit measurement').click(); await field(page, 'Weight (lb)').fill('151')
  await button(page, 'Save measurement').click(); await expect(page.locator('.current-weight')).toHaveText('Current weight: 151 lb')
  await button(page, 'Settings').click(); await expect(field(page, 'Weight (lb, optional)')).toHaveValue('151')
  await field(page, 'Weight unit').selectOption('kg'); await button(page, 'Save profile').click()
  await expect(page.getByText('Profile saved.', { exact: true })).toBeVisible()
  await button(page, 'Progress').click(); await expect(page.locator('.measurement-card')).toHaveCount(1)
  await button(page, 'Delete measurement').click(); await button(page, 'Delete entry and its photo').click()
  await expect(page.locator('.current-weight')).toHaveText('No recorded weight.')
  await button(page, 'Settings').click(); await expect(field(page, 'Weight (kg, optional)')).toHaveValue('')
  await field(page, 'Active profile').selectOption({ label: 'Untouched neighbour' })
  expect((await download(page)).data).toEqual(other.data)
  expect(page.url()).toBe(address); expect(errors).toEqual([])
  const external = requests.filter((url) => new URL(url).origin !== new URL(address).origin)
  expect(external.filter((url) => !url.startsWith('https://www.youtube.com/embed/'))).toEqual(['https://youtu.be/abcdefghijk'])
  expect(external.filter((url) => url.startsWith('https://www.youtube.com/embed/')).every((url) => url === 'https://www.youtube.com/embed/abcdefghijk?autoplay=0&controls=1&playsinline=1&fs=1')).toBe(true)
})
