import { test, expect, type Page } from '@playwright/test'
import { cardAction } from './create-actions'
import { waitForDraft } from './train-actions'
const b=(p:Page,n:string)=>p.getByRole('button',{name:n,exact:true})
const f=(p:Page,n:string)=>p.getByLabel(n,{exact:true})
const dialog=(p:Page,n:string)=>p.getByRole('dialog',{name:n,exact:true})
async function rows(p:Page,store:string){return p.evaluate(async store=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('boros');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});try{return await new Promise<any[]>((resolve,reject)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}finally{db.close()}},store)}
async function open(p:Page,theme:string){await p.goto('./');await b(p,'Settings').click();if(await b(p,'Understood').isVisible())await b(p,'Understood').click();await b(p,theme).click();await b(p,'Create').click()}
async function importData(p:Page,data:unknown,save:string){await b(p,'Import').click();await f(p,'AI output JSON').fill(JSON.stringify(data));await b(p,'Validate and preview').click();await b(p,save).click();await expect(b(p,'Create exercise')).toBeVisible()}
const movement=(name:string,n=2,tags=['Push'])=>({name,sets:Array.from({length:n},()=>({reps:{min:5,max:8},rir:{min:0,max:0}})),tags,restBetweenSetsSeconds:60,restAfterExerciseSeconds:60})
async function fixture(p:Page){await importData(p,{schemaVersion:5,kind:'plan',plan:{mode:'repeating',name:'Summer',durationWeeks:4,trainingDaysPerWeek:3,days:['Upper','Lower','Third'].map(name=>({name,exercises:[{...movement('Bench'),superset:1},{...movement('Row',3,['Pull']),superset:1},movement('Bench')],supersets:[{number:1,restBetweenRoundsSeconds:60,restAfterGroupSeconds:60}] }))}},'Save plan');await importData(p,{schemaVersion:5,kind:'exercise',exercise:movement('Swap Press',1)},'Save')}
async function activate(p:Page){await b(p,'Train').click();await b(p,'Add Plan').click();await dialog(p,'Add Plan').getByRole('article',{name:'Plan Summer'}).getByRole('button').click();await p.getByRole('article',{name:'Plan Summer'}).getByRole('button').click();await p.locator('.training-day-card').filter({hasText:'Upper'}).click()}
async function exerciseMenu(p:Page,name:string,action:string){await b(p,'Actions for '+name).click();await dialog(p,'Exercise actions').getByRole('button',{name:action,exact:true}).click()}
for(const theme of ['Dark','Light'])test(`preview, replacement confirmation/recovery, group timer and saved replacement (${theme})`,async({page},info)=>{
 test.setTimeout(100000);await open(page,theme);await fixture(page);await activate(page);const address=page.url()
 const actions=dialog(page,'Upper');expect(await actions.locator('.exercise-action-list button').allTextContents()).toEqual(['Start','Preview','Skip','Mark as Complete','Reset'])
 await actions.getByRole('button',{name:'Preview',exact:true}).click();await expect(page.getByRole('dialog').last()).toContainText('Bench');expect(await rows(page,'drafts')).toHaveLength(0);await page.getByRole('dialog').last().getByRole('button',{name:'Close',exact:true}).click();await expect(actions.getByRole('button',{name:'Preview',exact:true})).toBeFocused();await actions.getByRole('button',{name:'Start',exact:true}).click()
 await f(page,'Bench occurrence 1 set 1 Weight (kg)').fill('0');await f(page,'Bench occurrence 1 set 1 Repetitions').fill('8');await f(page,'Row set 1 Weight (kg)').fill('20');await f(page,'Row set 1 Repetitions').fill('6');await waitForDraft(page)
 await exerciseMenu(page,'Bench occurrence 1','Note');await expect(dialog(page,'Upper')).toBeVisible();await f(page,'Note').fill('Private replaced note');await dialog(page,'Upper').getByRole('button',{name:'Save',exact:true}).click();await waitForDraft(page)
 const original=(await rows(page,'drafts'))[0]
 await b(page,'REST Superset 1 after round 1').click();await expect(dialog(page,'Rest Timer')).toContainText('Superset 1');await expect(dialog(page,'Rest Timer')).toContainText('Set 1');await b(page,'Close').click();await expect(page.locator('.timer-compact svg')).toBeVisible()
 await exerciseMenu(page,'Bench occurrence 1','Replace');const picker=dialog(page,'Replace Exercise');await picker.getByRole('button',{name:'Tags (1)',exact:true}).click();await expect(picker.getByRole('button',{name:'Push',exact:true})).toHaveAttribute('aria-pressed','true');await expect(picker.getByRole('button',{name:/^Row Added/})).toHaveCount(0)
 await picker.getByRole('button',{name:/^Swap Press Added/}).click();await picker.getByRole('button',{name:'Cancel',exact:true}).click();expect((await rows(page,'drafts'))[0].day).toEqual(original.day)
 await exerciseMenu(page,'Bench occurrence 1','Replace');await picker.getByRole('button',{name:/^Swap Press Added/}).click();await picker.getByRole('button',{name:'Swap',exact:true}).click();await expect(dialog(page,'Replace Exercise?')).toContainText('This will clear the results and notes entered for this exercise.');await dialog(page,'Replace Exercise?').getByRole('button',{name:'Cancel',exact:true}).click();expect((await rows(page,'drafts'))[0].input).toEqual(original.input)
 await picker.getByRole('button',{name:'Swap',exact:true}).click();await dialog(page,'Replace Exercise?').getByRole('button',{name:'Swap',exact:true}).click();await expect(f(page,'Swap Press set 1 Weight (kg)')).toHaveValue('');await expect(f(page,'Row set 1 Weight (kg)')).toHaveValue('20');expect(await rows(page,'restTimers')).toHaveLength(0)
 const changed=(await rows(page,'drafts'))[0];expect(changed.day.exercises[0].id).toBe(original.day.exercises[0].id);expect(changed.day.exercises[0].groupId).toBe(original.day.exercises[0].groupId);expect(changed.input.exercises[0].notes).toBe('');expect(changed.input.exercises[1]).toEqual(original.input.exercises[1]);expect(changed.day.exercises).toHaveLength(3)
 await page.reload();await page.getByRole('button',{name:/^Resume Summer/}).click();await expect(f(page,'Swap Press set 1 Weight (kg)')).toHaveValue('');await f(page,'Swap Press set 1 Weight (kg)').fill('0');await f(page,'Swap Press set 1 Repetitions').fill('5');await waitForDraft(page);await b(page,'Save').click();await b(page,'Save partial session').click();await expect(page.getByRole('region',{name:'Saved session details'})).toContainText('Swap Press')
 const saved=(await rows(page,'sessions'))[0];expect(saved.day.exercises[0].source.id).toBe((await rows(page,'exercises')).find(e=>e.name==='Swap Press').id);expect(saved.day.exercises[2].prescription.name).toBe('Bench');expect(page.url()).toBe(address)
 await page.screenshot({path:info.outputPath('replacement-'+theme+'.png'),fullPage:true})
})
for(const theme of ['Dark','Light'])test(`Create menus, additive archives, merge direction and active plan deletion (${theme})`,async({page},info)=>{
 test.setTimeout(90000);await open(page,theme);await fixture(page);await activate(page);await b(page,'Start').click();await f(page,'Bench occurrence 1 set 1 Weight (kg)').fill('0');await f(page,'Bench occurrence 1 set 1 Repetitions').fill('5');await waitForDraft(page);await b(page,'Save').click();await b(page,'Save partial session').click();await b(page,'Create').click()
 const exerciseCard=(name:string)=>page.getByRole('article',{name,exact:true})
 await cardAction(page,exerciseCard('Bench'),'Merge');await dialog(page,'Merge exercise').getByRole('button',{name:/^Swap Press Added/}).click();await dialog(page,'Merge exercise').getByRole('button',{name:'Merge',exact:true}).click();await expect(dialog(page,'Merging Exercises?')).toContainText('Merge: Bench');await expect(dialog(page,'Merging Exercises?')).toContainText('Into: Swap Press');await b(page,'Switch').click();await expect(dialog(page,'Merging Exercises?')).toContainText('Merge: Swap Press');await expect(dialog(page,'Merging Exercises?')).toContainText('Into: Bench');await b(page,'Switch').click();await dialog(page,'Merging Exercises?').getByRole('button',{name:'Merge',exact:true}).click();await expect(dialog(page,'Swap Press')).toBeVisible();await b(page,'Close').click();await expect(exerciseCard('Bench')).toHaveCount(0)
 await cardAction(page,exerciseCard('Row'),'Archive');await dialog(page,'Archive exercise?').getByRole('button',{name:'Archive',exact:true}).click();await f(page,'Show archived exercises').check();await expect(exerciseCard('Row')).toContainText('Archived');await expect(exerciseCard('Swap Press')).toBeVisible();await expect(exerciseCard('Bench')).toHaveCount(0)
 await cardAction(page,exerciseCard('Swap Press'),'Delete');await dialog(page,'Delete exercise?').getByRole('button',{name:'Cancel',exact:true}).click();expect(await rows(page,'deletedSources')).toHaveLength(0);await page.getByRole('dialog').last().getByRole('button',{name:'Delete',exact:true}).click();await dialog(page,'Delete exercise?').getByRole('button',{name:'Delete',exact:true}).click();expect((await rows(page,'sessions'))[0].day.exercises[0].prescription.name).toBe('Bench')
 await cardAction(page,page.getByRole('article',{name:'Plan Summer'}),'Delete');await expect(dialog(page,'Deleting an Active Plan')).toContainText('By deleting this plan you will also leave the plan and will no longer be able to complete the workouts or exercises in it.');await dialog(page,'Deleting an Active Plan').getByRole('button',{name:'Delete',exact:true}).click()
 expect(await rows(page,'plans')).toHaveLength(0);expect(await rows(page,'schedules')).toHaveLength(0);expect(await rows(page,'sessions')).toHaveLength(0);expect(await rows(page,'drafts')).toHaveLength(0);expect((await rows(page,'exercises')).map(e=>e.name)).toEqual(['Row'])
 await b(page,'Train').click();await expect(page.getByText('No active plan(s) selected.',{exact:true})).toHaveCount(1);await page.reload();expect(await rows(page,'plans')).toHaveLength(0);await b(page,'Create').click();await expect(exerciseCard('Bench')).toHaveCount(0)
 await page.screenshot({path:info.outputPath('deleted-'+theme+'.png'),fullPage:true})
})
test('exercise charts scroll with fixed axis, filter dates, open only result details and preserve position',async({page},info)=>{
 test.setTimeout(90000);await open(page,'Light');await fixture(page);await activate(page);await b(page,'Start').click();await f(page,'Bench occurrence 1 set 1 Weight (kg)').fill('0');await f(page,'Bench occurrence 1 set 1 Repetitions').fill('5');await waitForDraft(page);await b(page,'Save').click();await b(page,'Save partial session').click()
 // More same-date points in this isolated context exercise scroll/identity behavior.
 await page.evaluate(async()=>{const db=await new Promise<IDBDatabase>(resolve=>{const r=indexedDB.open('boros');r.onsuccess=()=>resolve(r.result)});const read=async(store:string)=>new Promise<any[]>(resolve=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>resolve(r.result)});const [source]=(await read('sessions')),draft=(await read('drafts')).find(d=>d.id===source.draftId);await new Promise<void>((resolve,reject)=>{const tx=db.transaction(['sessions','drafts'],'readwrite');for(let i=1;i<=24;i++){const id=crypto.randomUUID(),at=new Date(Date.now()-i*86400000).toISOString();const s={...source,id,draftId:id,sourcePlanId:source.sourcePlanId,occurrence:undefined,occurrenceKey:undefined,startedAt:at,completedAt:at,loggedAt:at};const d={...draft,id,occurrence:undefined,occurrenceKey:undefined,activeSourceKey:undefined,startedAt:at,updatedAt:at,finalizedAt:at};tx.objectStore('sessions').put(s);tx.objectStore('drafts').put(d)}tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close()})
 await b(page,'Progress').click();await page.getByRole('region',{name:'Overall exercises'}).getByRole('button').filter({hasText:'Bench'}).click();const chart=page.locator('.point-chart').first(),plot=chart.locator('.weight-plot-scroll'),axis=chart.locator('.weight-axis')
 await expect(plot).toBeVisible();await expect.poll(()=>plot.evaluate(e=>e.scrollLeft)).toBeGreaterThan(0);const width=await plot.evaluate(e=>({visible:e.clientWidth,total:e.scrollWidth}));expect(width.total).toBeGreaterThan(width.visible*2)
 const left=(await axis.boundingBox())!.x;await plot.evaluate(e=>{e.scrollLeft=40});expect((await axis.boundingBox())!.x).toBe(left);await chart.getByRole('button',{name:/0 kg/}).nth(1).click();const details=dialog(page,'Exercise result');await expect(details).toBeVisible();await expect(details.getByRole('button',{name:'Delete',exact:true})).toHaveCount(0);await expect(details.locator('input')).toHaveCount(0);await details.getByRole('button',{name:'Close',exact:true}).click();expect(await plot.evaluate(e=>e.scrollLeft)).toBeLessThan(width.total-width.visible)
 const start=new Date(Date.now()-3*86400000).toISOString().slice(0,10);await b(page,'Filter').click();await f(page,'Start date').fill(start);await b(page,'Apply').click();await expect(chart.locator('.weight-point')).toHaveCount(4);await b(page,'Filter, active').click();await b(page,'Clear').click();await expect(chart.locator('.weight-point')).toHaveCount(25)
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('exercise-chart.png'),fullPage:true})
})

test('timer unlock stays silent, clockwise large/compact progress agrees, completion claims once, count-up has no alarm',async({page},info)=>{
 test.setTimeout(90000)
 await page.addInitScript(()=>{const w=window as any;w.plays=[];w.media=[];HTMLMediaElement.prototype.play=function(){w.plays.push({muted:this.muted,volume:this.volume});if(!w.media.includes(this))w.media.push(this);return Promise.resolve()};HTMLMediaElement.prototype.pause=function(){}})
 await page.clock.install();await open(page,'Dark');await b(page,'Settings').click();await page.getByRole('group',{name:'Sound',exact:true}).getByRole('button',{name:'On',exact:true}).click();await b(page,'Create').click();await fixture(page);await activate(page);await b(page,'Start').click();await b(page,'REST Superset 1 after round 1').click();const timer=dialog(page,'Rest Timer');await expect(timer).toBeVisible()
 expect(await page.evaluate(()=>(window as any).plays.every((p:any)=>p.muted&&p.volume===0))).toBe(true)
 const capability=await page.evaluate(()=>({userAgent:navigator.userAgent,vibrate:typeof navigator.vibrate,secure:isSecureContext}));await info.attach('vibration-capability.json',{body:JSON.stringify(capability),contentType:'application/json'})
 await expect(timer.locator('.timer-progress')).toHaveAttribute('transform','rotate(-90 60 60)')
 const initial=(await rows(page,'restTimers'))[0];await timer.getByRole('button',{name:'Close',exact:true}).click();expect((await rows(page,'restTimers'))[0].token).toBe(initial.token);await expect(page.locator('.timer-compact span')).toHaveText(/\d{2}:\d{2}/)
 await page.locator('.timer-compact').click();await timer.getByRole('button',{name:'Reset',exact:true}).click();await expect.poll(async()=>(await rows(page,'restTimers'))[0].token).not.toBe(initial.token)
 expect(await page.evaluate(()=>(window as any).plays.filter((p:any)=>!p.muted&&p.volume>0))).toHaveLength(0)

 await page.clock.fastForward(30000);await expect.poll(async()=>Number((await timer.locator('.timer-progress').getAttribute('stroke-dasharray'))!.split(' ')[0])).toBeGreaterThan(.45)
 expect(await page.locator('.timer-compact .timer-progress').getAttribute('stroke-dasharray')).toBe(await timer.locator('.timer-progress').getAttribute('stroke-dasharray'))
 await page.clock.fastForward(31000);await expect.poll(async()=>!!(await rows(page,'restTimers'))[0].alertedAt).toBe(true);await expect.poll(()=>page.evaluate(()=>(window as any).plays.filter((p:any)=>!p.muted&&p.volume>0).length)).toBe(1)
 await page.evaluate(()=>{const a=(window as any).media[0];a.onended?.(new Event('ended'));a.onended?.(new Event('ended'));a.onended?.(new Event('ended'))});expect(await page.evaluate(()=>(window as any).plays.filter((p:any)=>!p.muted&&p.volume>0))).toHaveLength(3)
 await timer.getByRole('button',{name:'Close',exact:true}).click();await b(page,'Rest finished').click();expect(await page.evaluate(()=>(window as any).plays.filter((p:any)=>!p.muted&&p.volume>0))).toHaveLength(3);await b(page,'Stop').click();await b(page,'Cancel').click()
 await b(page,'Create').click();await importData(page,{schemaVersion:5,kind:'exercise',exercise:{name:'Untimed',sets:[{reps:{min:5,max:5}}]}},'Save');await b(page,'Train').click();await b(page,'Custom Workout').click();await b(page,'Add Exercise').click();await b(page,'Add Untimed').click();await b(page,'REST Untimed between exercises').click();await expect(timer.locator('.timer-progress')).toHaveCount(0);await expect(timer.getByRole('timer')).toHaveText(/\d{2}:\d{2}/);await b(page,'Close').click();await expect(page.locator('.timer-compact .timer-track')).toBeVisible();expect((await rows(page,'restTimers'))[0].mode).toBe('countup');expect(await page.evaluate(()=>(window as any).plays.filter((p:any)=>!p.muted&&p.volume>0))).toHaveLength(3)
})
