import { expect, test, type Page } from '@playwright/test'

test.setTimeout(90000)
const button = (page: Page, name: string) => page.getByRole('button', { name, exact: true })
const card = (page: Page, name: string) => page.getByRole('article', { name: `Plan ${name}`, exact: true })
const days = (page: Page) => page.locator('.plan-day')
async function open(page: Page) {
  await page.goto('./'); await button(page, 'Create').click()
  const notice = button(page, 'Understood'); if (await notice.isVisible()) await notice.click()
}
async function libraryExercise(page: Page, name = 'Squat', tag = 'Legs', heterogeneous = false) {
  await button(page, 'Create Workout').click()
  await page.getByLabel('Exercise name', { exact: true }).fill(name)
  if (heterogeneous) {
    await page.getByLabel('Number of sets', { exact: true }).fill('3'); await button(page, 'Apply set count').click()
    await page.getByLabel('Set 1 Reps maximum (optional)', { exact: true }).fill('8')
    await page.getByLabel('Set 1 RIR minimum (optional)', { exact: true }).fill('0')
    await page.getByLabel('Set 2 Reps minimum', { exact: true }).fill('10')
    await page.getByLabel('Set 3 Reps minimum', { exact: true }).fill('8')
    await page.getByLabel('Set 3 Reps maximum (optional)', { exact: true }).fill('12')
    await page.getByLabel('Set 3 RIR minimum (optional)', { exact: true }).fill('1')
    await page.getByLabel('Set 3 RIR maximum (optional)', { exact: true }).fill('2')
    await page.getByLabel('Rest between sets (seconds, optional)', { exact: true }).fill('0')
    await page.getByLabel('Instructions (optional)', { exact: true }).fill('<b>Keep plain text</b>')
    await page.getByLabel('Notes (optional)', { exact: true }).fill('Saved note')
    await page.getByLabel('YouTube tutorial URL (optional)', { exact: true }).fill('https://youtu.be/abcdefghijk')
  }
  await page.getByLabel('Set 1 Reps minimum', { exact: true }).fill('5')
  await page.getByLabel('New tag', { exact: true }).fill(tag); await button(page, 'Add tag').click()
  await button(page, 'Save workout').click()
  await expect(page.getByRole('article', { name, exact: true })).toBeVisible()
}
async function copy(page: Page, day = 0, source = 'Library: Squat') {
  await days(page).nth(day).getByRole('button', { name: 'Add exercise', exact: true }).click()
  await button(page, `Copy ${source}`).click()
}
async function createPlan(page: Page, name: string, count = 1) {
  await button(page, 'Create Plan').click()
  await page.getByLabel('Plan name', { exact: true }).fill(name)
  await page.getByLabel('Duration (weeks)', { exact: true }).fill('2')
  await page.getByLabel('Training days per week').selectOption(String(count))
  for (let index = 0; index < count; index++) await copy(page, index)
  await save(page, name)
}
async function save(page: Page, name: string) { await button(page, 'Save plan').click(); await expect(card(page, name)).toBeVisible() }
async function cancel(page: Page, dirty = false) {
  await button(page, 'Cancel plan editor').click()
  if (dirty) await page.getByRole('dialog').getByRole('button', { name: 'Confirm', exact: true }).click()
}
async function ids(page: Page) { return page.locator('[data-day-id], [data-occurrence-id]').evaluateAll((items) => items.map((item) => item.getAttribute('data-day-id') ?? item.getAttribute('data-occurrence-id'))) }

test('four-day heterogeneous snapshots, stable ordering/moves, duplicate and archive/restore survive reload', async ({ page }, testInfo) => {
  await open(page); const address = page.url()
  await libraryExercise(page, 'Squat', 'Legs', true)
  await createPlan(page, 'Four days', 4)
  await card(page, 'Four days').getByRole('button', { name: 'Edit plan', exact: true }).click()
  await expect(page.getByText('4 training days; 3 rest days per week.', { exact: true })).toBeVisible()
  const originalIds = await ids(page)
  await copy(page, 0)
  const addedId = await days(page).nth(0).locator('[data-occurrence-id]').last().getAttribute('data-occurrence-id')
  await days(page).nth(0).locator('[data-occurrence-id]').last().getByRole('button', { name: 'Move exercise up', exact: true }).click()
  await days(page).nth(0).locator('[data-occurrence-id]').first().getByLabel('Move Squat to day').selectOption({ label: '2. Day 2' })
  await days(page).nth(1).getByRole('button', { name: 'Move day down', exact: true }).click()
  await page.getByLabel('Day 1 name', { exact: true }).fill('Lower body')
  const orderedIds = await ids(page)
  expect(orderedIds).toContain(addedId)
  for (const id of originalIds) expect(orderedIds).toContain(id)
  await save(page, 'Four days'); await page.reload()
  await card(page, 'Four days').getByRole('button', { name: 'Edit plan', exact: true }).click()
  expect(await ids(page)).toEqual(orderedIds)
  await days(page).first().getByRole('button', { name: 'Edit prescription', exact: true }).click()
  await expect(page.getByLabel('Set 1 RIR minimum (optional)', { exact: true })).toHaveValue('0')
  await expect(page.getByLabel('Set 2 RIR minimum (optional)', { exact: true })).toHaveValue('')
  await expect(page.getByLabel('Set 3 Reps maximum (optional)', { exact: true })).toHaveValue('12')
  await expect(page.getByLabel('Rest between sets (seconds, optional)', { exact: true })).toHaveValue('0')
  await expect(page.getByLabel('Rest after exercise (seconds, optional)', { exact: true })).toHaveValue('')
  await expect(page.getByLabel('Instructions (optional)', { exact: true })).toHaveValue('<b>Keep plain text</b>')
  await expect(page.getByLabel('Notes (optional)', { exact: true })).toHaveValue('Saved note')
  await expect(page.getByLabel('YouTube tutorial URL (optional)', { exact: true })).toHaveValue('https://youtu.be/abcdefghijk')
  await button(page, 'Cancel editor').click(); await cancel(page)
  await card(page, 'Four days').getByRole('button', { name: 'Duplicate plan', exact: true }).click()
  await expect(page.getByLabel('Plan name', { exact: true })).toHaveValue('Four days (copy)')
  for (const id of await ids(page)) expect(orderedIds).not.toContain(id)
  await save(page, 'Four days (copy)')
  await card(page, 'Four days').getByRole('button', { name: 'Archive plan', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Archive', exact: true }).click()
  await expect(card(page, 'Four days')).toHaveCount(0)
  await page.getByLabel('Show archived plans').check()
  await card(page, 'Four days').getByRole('button', { name: 'Restore plan', exact: true }).click()
  await page.getByLabel('Show archived plans').uncheck(); await page.reload()
  await expect(card(page, 'Four days')).toBeVisible()
  await expect(card(page, 'Four days (copy)')).toBeVisible()
  await expect(page).toHaveURL(address)
  await page.screenshot({ path: testInfo.outputPath('plan-library.png'), fullPage: true })
})

test('source picker filters combine and copied prescriptions remain independent of library and plans', async ({ page }) => {
  await open(page); await libraryExercise(page); await libraryExercise(page, 'Row', 'Back')
  await createPlan(page, 'Source')
  await button(page, 'Create Plan').click(); await page.getByLabel('Plan name', { exact: true }).fill('Destination'); await page.getByLabel('Duration (weeks)', { exact: true }).fill('2')
  await days(page).first().getByRole('button', { name: 'Add exercise', exact: true }).click()
  const picker = page.getByRole('region', { name: 'Choose exercise', exact: true })
  await picker.getByLabel('Search sources').fill('squat')
  await picker.getByLabel('Sort sources').selectOption('newest')
  await picker.getByLabel('Legs', { exact: true }).check(); await picker.getByLabel('Back', { exact: true }).check()
  await expect(picker.locator('.source-list li')).toHaveCount(2)
  await expect(picker).toContainText('ANY selected tag matches')
  await button(page, 'Copy Plan: Source / Day 1: Day 1 / Exercise 1: Squat').click()
  await days(page).first().getByRole('button', { name: 'Edit prescription', exact: true }).click()
  await page.getByLabel('Set 1 Reps minimum', { exact: true }).fill('9')
  await page.getByLabel('New tag', { exact: true }).fill('Copied'); await button(page, 'Add tag').click()
  await button(page, 'Apply to plan').click(); await save(page, 'Destination')
  await card(page, 'Source').getByRole('button', { name: 'Edit plan', exact: true }).click()
  await days(page).first().getByRole('button', { name: 'Edit prescription', exact: true }).click()
  await expect(page.getByLabel('Set 1 Reps minimum', { exact: true })).toHaveValue('5')
  await page.getByLabel('Set 1 Reps minimum', { exact: true }).fill('7')
  await button(page, 'Apply to plan').click(); await save(page, 'Source')
  const library = page.getByRole('article', { name: 'Squat', exact: true })
  await library.getByRole('button', { name: 'View / edit', exact: true }).click()
  await expect(page.getByLabel('Set 1 Reps minimum', { exact: true })).toHaveValue('5')
  await page.getByLabel('Set 1 Reps minimum', { exact: true }).fill('6'); await button(page, 'Save workout').click()
  await library.getByRole('button', { name: 'Archive', exact: true }).click(); await page.getByRole('dialog').getByRole('button', { name: 'Archive', exact: true }).click()
  await card(page, 'Source').getByRole('button', { name: 'Archive plan', exact: true }).click(); await page.getByRole('dialog').getByRole('button', { name: 'Archive', exact: true }).click()
  await page.reload(); await card(page, 'Destination').getByRole('button', { name: 'Edit plan', exact: true }).click()
  await days(page).first().getByRole('button', { name: 'Edit prescription', exact: true }).click()
  await expect(page.getByLabel('Set 1 Reps minimum', { exact: true })).toHaveValue('9')
  await expect(button(page, 'Remove tag Copied')).toBeVisible()
})

test('validation, destructive cancellation, nested drafts, failed saves and mobile spacing retain input', async ({ page }, testInfo) => {
  await open(page); await libraryExercise(page)
  await button(page, 'Create Plan').click(); await button(page, 'Save plan').click()
  await expect(page.getByText('Enter a name.', { exact: true })).toBeVisible()
  await expect(page.getByText('Add at least one exercise to this day.', { exact: true })).toBeVisible()
  await page.getByLabel('Plan name', { exact: true }).fill('Recoverable'); await page.getByLabel('Duration (weeks)', { exact: true }).fill('2')
  await copy(page); const firstIds = await ids(page)
  await button(page, 'Add training day').click(); await copy(page, 1)
  await page.getByLabel('Training days per week').selectOption('1')
  await page.getByRole('dialog').getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByLabel('Training days per week')).toHaveValue('2')
  await days(page).last().getByRole('button', { name: 'Remove day', exact: true }).click(); await page.keyboard.press('Escape')
  await expect(days(page)).toHaveCount(2)
  await days(page).first().getByRole('button', { name: 'Remove exercise', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Cancel', exact: true }).click()
  for (const id of firstIds) expect(await ids(page)).toContain(id)
  await button(page, 'Add training day').click(); await copy(page, 2)
  await days(page).last().getByRole('button', { name: 'Remove exercise', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(days(page).last().locator('[data-occurrence-id]')).toHaveCount(0)
  await days(page).last().getByRole('button', { name: 'Remove day', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(days(page)).toHaveCount(2)
  await button(page, 'Add training day').click(); await copy(page, 2)
  await page.getByLabel('Training days per week').selectOption('2')
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(days(page)).toHaveCount(2)
  for (const id of firstIds) expect(await ids(page)).toContain(id)
  await days(page).first().getByRole('button', { name: 'Edit prescription', exact: true }).click()
  await page.getByLabel('Exercise name', { exact: true }).fill('Unsaved nested')
  page.once('dialog', (dialog) => dialog.dismiss()); await button(page, 'Settings').click()
  await expect(page.getByLabel('Exercise name', { exact: true })).toHaveValue('Unsaved nested')
  await button(page, 'Cancel editor').click(); await page.getByRole('dialog').getByRole('button', { name: 'Confirm', exact: true }).click()
  page.once('dialog', (dialog) => dialog.dismiss()); await button(page, 'Train').click()
  await expect(page.getByLabel('Plan name', { exact: true })).toHaveValue('Recoverable')
  const unload = page.waitForEvent('dialog')
  await page.evaluate(() => { setTimeout(() => window.location.reload(), 0) })
  const unloadDialog = await unload
  expect(unloadDialog.type()).toBe('beforeunload')
  await unloadDialog.dismiss()
  await expect(page.getByLabel('Plan name', { exact: true })).toHaveValue('Recoverable')
  await page.evaluate(() => {
    const original = IDBObjectStore.prototype.put
    ;(window as unknown as { restoreWrite: () => void }).restoreWrite = () => { IDBObjectStore.prototype.put = original }
    IDBObjectStore.prototype.put = function (...args) { if (this.name === 'plans') throw new DOMException('Simulated plan disk full', 'QuotaExceededError'); return original.apply(this, args) }
  })
  await button(page, 'Save plan').click()
  await expect(page.getByRole('alert')).toContainText('Simulated plan disk full')
  await expect(page.getByLabel('Plan name', { exact: true })).toHaveValue('Recoverable')
  await expect(days(page)).toHaveCount(2)
  await page.setViewportSize({ width: 320, height: 720 })
  await button(page, 'Save plan').focus()
  await button(page, 'Save plan').scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  const saveBox = await button(page, 'Save plan').boundingBox(), nav = await page.getByRole('navigation').boundingBox()
  expect(saveBox!.y + saveBox!.height).toBeLessThanOrEqual(nav!.y)
  await page.screenshot({ path: testInfo.outputPath('plan-editor-320.png'), fullPage: true })
  await page.evaluate(() => (window as unknown as { restoreWrite: () => void }).restoreWrite())
  await save(page, 'Recoverable'); await page.reload(); await expect(card(page, 'Recoverable')).toBeVisible()
})

test('stale tabs and another tab profile selection cannot retarget plan input', async ({ page, context }) => {
  await open(page); await libraryExercise(page); await createPlan(page, 'Original')
  const other = await context.newPage(); await open(other)
  await card(other, 'Original').getByRole('button', { name: 'Edit plan', exact: true }).click()
  await other.getByLabel('Plan name', { exact: true }).fill('Stale draft')
  await card(page, 'Original').getByRole('button', { name: 'Edit plan', exact: true }).click()
  await page.getByLabel('Plan name', { exact: true }).fill('Latest'); await save(page, 'Latest')
  await button(other, 'Save plan').click(); await expect(other.getByRole('alert')).toContainText('changed in another tab')
  await expect(other.getByLabel('Plan name', { exact: true })).toHaveValue('Stale draft')
  await cancel(other, true)
  await card(other, 'Latest').getByRole('button', { name: 'Edit plan', exact: true }).click()
  await other.getByLabel('Plan name', { exact: true }).fill('Guest updated')
  await button(page, 'Settings').click(); await page.getByLabel('New profile name').fill('Other')
  await button(page, 'Create profile').click(); await expect(page.locator('input[name="name"]')).toHaveValue('Other')
  await button(page, 'Light').click(); await button(page, 'Create').click()
  await expect(card(page, 'Latest')).toHaveCount(0)
  await save(other, 'Guest updated')
  await expect(card(page, 'Guest updated')).toHaveCount(0)
  await button(page, 'Create Plan').click(); await days(page).first().getByRole('button', { name: 'Add exercise', exact: true }).click()
  await expect(page.getByText('No matching sources. Save a library workout or plan first.')).toBeVisible()
  await button(page, 'Cancel selection').click(); await cancel(page)
  await button(page, 'Settings').click(); await page.getByLabel('Active profile').selectOption({ label: 'Guest' })
  await button(page, 'Create').click(); await expect(card(page, 'Guest updated')).toBeVisible()
})

test('plan name conflicts and archive restoration offer explicit rename recovery', async ({ page }) => {
  await open(page); await libraryExercise(page); await createPlan(page, 'Strength')
  await card(page, 'Strength').getByRole('button', { name: 'Duplicate plan', exact: true }).click()
  await page.getByLabel('Plan name', { exact: true }).fill(' STRENGTH '); await button(page, 'Save plan').click()
  await expect(page.getByRole('alert')).toContainText('already exists')
  await page.getByLabel('Plan name', { exact: true }).fill('Second'); await save(page, 'Second')
  await card(page, 'Strength').getByRole('button', { name: 'Archive plan', exact: true }).click(); await page.getByRole('dialog').getByRole('button', { name: 'Archive', exact: true }).click()
  await createPlan(page, 'Strength')
  await page.getByLabel('Show archived plans').check(); await card(page, 'Strength').getByRole('button', { name: 'Restore plan', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('rename an archived plan')
  await card(page, 'Strength').getByRole('button', { name: 'Edit plan', exact: true }).click()
  await page.getByLabel('Plan name', { exact: true }).fill('Older Strength'); await save(page, 'Older Strength')
  await card(page, 'Older Strength').getByRole('button', { name: 'Restore plan', exact: true }).click()
  await page.getByLabel('Show archived plans').uncheck(); await expect(card(page, 'Older Strength')).toBeVisible()
  await expect(button(page, 'Import AI Output')).toBeEnabled()
})
