import { createNamedProfile } from './settings-actions'
import { cardAction, occurrenceAction } from './create-actions'
import { expect, test, type Page } from '@playwright/test'

test.setTimeout(90000)
test.beforeEach(async ({ page }) => { await page.route('https://www.youtube.com/embed/**', (route) => route.fulfill({ contentType: 'text/html', body: '<button>Simulated player</button>' })) })
const button = (page: Page, name: string) => page.getByRole('button', { name, exact: true })
const card = (page: Page, name: string) => page.getByRole('article', { name: `Plan ${name}`, exact: true })
const days = (page: Page) => page.locator('.plan-day')
async function open(page: Page) {
  await page.goto('./'); await button(page, 'Create').click()
  const notice = button(page, 'Understood'); if (await notice.isVisible()) await notice.click()
}
async function libraryExercise(page: Page, name = 'Squat', tag = 'Legs', heterogeneous = false) {
  await button(page, 'Create exercise').click()
  await page.getByLabel('Exercise name', { exact: true }).fill(name)
  if (heterogeneous) {
    await page.getByLabel('Number of sets', { exact: true }).fill('3'); await button(page, 'Apply').click()
    await page.getByLabel('Set 1 Reps maximum', { exact: true }).fill('8')
    await page.getByLabel('Set 1 RIR minimum', { exact: true }).fill('0')
    await page.getByLabel('Set 2 Reps minimum', { exact: true }).fill('10')
    await page.getByLabel('Set 3 Reps minimum', { exact: true }).fill('8')
    await page.getByLabel('Set 3 Reps maximum', { exact: true }).fill('12')
    await page.getByLabel('Set 3 RIR minimum', { exact: true }).fill('1')
    await page.getByLabel('Set 3 RIR maximum', { exact: true }).fill('2')
    await page.getByLabel('Rest between sets (optional) seconds', { exact: true }).fill('0')
    await page.getByLabel('Instructions (optional)', { exact: true }).fill('<b>Keep plain text</b>')
    await page.getByLabel('Notes (optional)', { exact: true }).fill('Saved note')
    await page.getByLabel('YouTube tutorial URL (optional)', { exact: true }).fill('https://youtu.be/abcdefghijk')
  }
  await page.getByLabel('Set 1 Reps minimum', { exact: true }).fill('5')
  await page.getByLabel('New tag', { exact: true }).fill(tag); await button(page, 'Add').click()
  await button(page, 'Save').click()
  await expect(page.getByRole('article', { name, exact: true })).toBeVisible()
}
async function copy(page: Page, day = 0, source = 'Library: Squat') {
  await days(page).nth(day).getByRole('button', { name: 'Add exercise', exact: true }).click()
  await button(page, 'Add ' + source.replace('Library: ', '')).click()
}
async function createPlan(page: Page, name: string, count = 1) {
  await button(page, 'Create Plan').click()
  await page.getByLabel('Plan name', { exact: true }).fill(name)
  await page.getByLabel('Duration (weeks)', { exact: true }).fill('2')
  await page.getByLabel('Workouts per week').selectOption(String(count))
  for (let index = 0; index < count; index++) await copy(page, index)
  await save(page, name)
}
async function save(page: Page, name: string) { await button(page, 'Save plan').click(); await expect(card(page, name)).toBeVisible() }
async function cancel(page: Page, dirty = false) {
  await button(page, 'Cancel').click()
  if (dirty) await page.getByRole('dialog').getByRole('button', { name: 'Confirm', exact: true }).click()
}
async function ids(page: Page) { return page.locator('[data-day-id], [data-occurrence-id]').evaluateAll((items) => items.map((item) => item.getAttribute('data-day-id') ?? item.getAttribute('data-occurrence-id'))) }

test('four-day heterogeneous snapshots, stable ordering/moves, duplicate and archive/restore survive reload', async ({ page }, testInfo) => {
  await open(page); const address = page.url()
  await libraryExercise(page, 'Squat', 'Legs', true)
  await createPlan(page, 'Four days', 4)
  await cardAction(page, card(page, 'Four days'), 'Edit')
  await expect(page.getByText('4 workouts · 3 rest days', { exact: true })).toBeVisible()
  const originalIds = await ids(page)
  await copy(page, 0)
  const addedId = await days(page).nth(0).locator('[data-occurrence-id]').last().getAttribute('data-occurrence-id')
  await days(page).nth(0).locator('[data-occurrence-id]').last().getByRole('button', { name: 'Move exercise up', exact: true }).click()
  await occurrenceAction(page, days(page).nth(0).locator('[data-occurrence-id]').first(), 'Move'); await page.getByRole('dialog').getByRole('button', { name: 'Workout 2: Day 2', exact: true }).click()
  await days(page).nth(1).getByRole('button', { name: 'Move workout down', exact: true }).click()
  await page.getByLabel('Workout 1 name', { exact: true }).fill('Lower body')
  const orderedIds = await ids(page)
  expect(orderedIds).toContain(addedId)
  for (const id of originalIds) expect(orderedIds).toContain(id)
  await save(page, 'Four days'); await page.reload()
  await cardAction(page, card(page, 'Four days'), 'Edit')
  expect(await ids(page)).toEqual(orderedIds)
  await occurrenceAction(page, days(page).first(), 'Edit')
  await expect(page.getByLabel('Set 1 RIR minimum', { exact: true })).toHaveValue('0')
  await expect(page.getByLabel('Set 2 RIR minimum', { exact: true })).toHaveValue('')
  await expect(page.getByLabel('Set 3 Reps maximum', { exact: true })).toHaveValue('12')
  await expect(page.getByLabel('Rest between sets (optional) seconds', { exact: true })).toHaveValue('0')
  await expect(page.getByLabel('Rest after exercise (optional) seconds', { exact: true })).toHaveValue('')
  await expect(page.getByLabel('Instructions (optional)', { exact: true })).toHaveValue('<b>Keep plain text</b>')
  await expect(page.getByLabel('Notes (optional)', { exact: true })).toHaveValue('Saved note')
  await expect(page.getByLabel('YouTube tutorial URL (optional)', { exact: true })).toHaveValue('https://youtu.be/abcdefghijk')
  await button(page, 'Cancel').click(); await cancel(page)
  await cardAction(page, card(page, 'Four days'), 'Duplicate')
  await expect(page.getByLabel('Plan name', { exact: true })).toHaveValue('Four days (copy)')
  for (const id of await ids(page)) expect(orderedIds).not.toContain(id)
  await save(page, 'Four days (copy)')
  await cardAction(page, card(page, 'Four days'), 'Archive')
  await page.getByRole('dialog').getByRole('button', { name: 'Archive', exact: true }).click()
  await expect(card(page, 'Four days')).toHaveCount(0)
  await page.getByLabel('Show archived plans').check()
  await cardAction(page, card(page, 'Four days'), 'Restore')
  await page.getByLabel('Show archived plans').uncheck(); await page.reload()
  await expect(card(page, 'Four days')).toBeVisible()
  await expect(card(page, 'Four days (copy)')).toBeVisible()
  await expect(page).toHaveURL(address)
  await page.screenshot({ path: testInfo.outputPath('plan-library.png'), fullPage: true })
})

test('source picker filters combine and copied prescriptions remain independent of library and plans', async ({ page }) => {
  await open(page); await libraryExercise(page); await libraryExercise(page, 'Row', 'Back')
  await createPlan(page, 'Source')
  await button(page, 'Create Plan').click(); await page.getByLabel('Plan name', { exact: true }).fill('Destination'); await page.getByLabel('Duration (weeks)', { exact: true }).fill('2')
  await days(page).first().getByRole('button', { name: 'Add exercise', exact: true }).click()
  const picker = page.getByRole('region', { name: 'Choose exercise', exact: true })
  await picker.getByLabel('Search exercises to add').fill('squat')
  await picker.getByLabel('Sort exercises to add').selectOption('newest')
  await picker.getByRole('button', { name: 'Tags', exact: true }).click()
  await picker.getByRole('button', { name: 'Legs', exact: true }).click(); await picker.getByRole('button', { name: 'Back', exact: true }).click()
  await expect(picker.locator('.exercise-selection-row')).toHaveCount(1)
  await expect(picker).not.toContainText('ANY selected tag matches')
  await button(page, 'Add Squat').click()
  await occurrenceAction(page, days(page).first(), 'Edit')
  await page.getByLabel('Set 1 Reps minimum', { exact: true }).fill('9')
  await page.getByLabel('New tag', { exact: true }).fill('Copied'); await button(page, 'Add').click()
  await page.locator('.exercise-editor button[type=submit]').click(); await save(page, 'Destination')
  await cardAction(page, card(page, 'Source'), 'Edit')
  await occurrenceAction(page, days(page).first(), 'Edit')
  await expect(page.getByLabel('Set 1 Reps minimum', { exact: true })).toHaveValue('5')
  await page.getByLabel('Set 1 Reps minimum', { exact: true }).fill('7')
  await page.locator('.exercise-editor button[type=submit]').click(); await save(page, 'Source')
  const library = page.getByRole('article', { name: 'Squat', exact: true })
  await cardAction(page, library, 'Edit')
  await expect(page.getByLabel('Set 1 Reps minimum', { exact: true })).toHaveValue('5')
  await page.getByLabel('Set 1 Reps minimum', { exact: true }).fill('6'); await button(page, 'Save').click()
  await cardAction(page, library, 'Archive'); await page.getByRole('dialog').getByRole('button', { name: 'Archive', exact: true }).click()
  await cardAction(page, card(page, 'Source'), 'Archive'); await page.getByRole('dialog').getByRole('button', { name: 'Archive', exact: true }).click()
  await page.reload(); await cardAction(page, card(page, 'Destination'), 'Edit')
  await occurrenceAction(page, days(page).first(), 'Edit')
  await expect(page.getByLabel('Set 1 Reps minimum', { exact: true })).toHaveValue('9')
  await expect(page.locator('.tag-editor').getByRole('button', { name: 'Copied', exact: true })).toHaveAttribute('aria-pressed', 'true')
})

test('validation, destructive cancellation, nested drafts, failed saves and mobile spacing retain input', async ({ page }, testInfo) => {
  await open(page); await libraryExercise(page)
  await button(page, 'Create Plan').click(); await button(page, 'Save plan').click()
  await expect(page.getByText('Enter a name.', { exact: true })).toBeVisible()
  await expect(page.getByText('Add at least one exercise to this workout.', { exact: true })).toBeVisible()
  await page.getByLabel('Plan name', { exact: true }).fill('Recoverable'); await page.getByLabel('Duration (weeks)', { exact: true }).fill('2')
  await copy(page); const firstIds = await ids(page)
  await button(page, 'Add workout').click(); await button(page, 'New empty workout').click(); await copy(page, 1)
  await page.getByLabel('Workouts per week').selectOption('1')
  await page.getByRole('dialog').getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByLabel('Workouts per week')).toHaveValue('2')
  await days(page).last().getByRole('button', { name: 'Delete workout', exact: true }).click(); await page.keyboard.press('Escape')
  await expect(days(page)).toHaveCount(2)
  await occurrenceAction(page, days(page).first(), 'Delete')
  await page.getByRole('dialog').getByRole('button', { name: 'Cancel', exact: true }).click()
  for (const id of firstIds) expect(await ids(page)).toContain(id)
  await button(page, 'Add workout').click(); await button(page, 'New empty workout').click(); await copy(page, 2)
  await occurrenceAction(page, days(page).last(), 'Delete')
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(days(page).last().locator('[data-occurrence-id]')).toHaveCount(0)
  await days(page).last().getByRole('button', { name: 'Delete workout', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(days(page)).toHaveCount(2)
  await button(page, 'Add workout').click(); await button(page, 'New empty workout').click(); await copy(page, 2)
  await page.getByLabel('Workouts per week').selectOption('2')
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(days(page)).toHaveCount(2)
  for (const id of firstIds) expect(await ids(page)).toContain(id)
  await occurrenceAction(page, days(page).first(), 'Edit')
  await page.getByLabel('Exercise name', { exact: true }).fill('Unsaved nested')
  await button(page, 'Settings').click(); await page.getByRole('dialog').getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByLabel('Exercise name', { exact: true })).toHaveValue('Unsaved nested')
  await button(page, 'Cancel').click(); await page.getByRole('dialog').getByRole('button', { name: 'Confirm', exact: true }).click()
  await button(page, 'Train').click(); await page.getByRole('dialog').getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByLabel('Plan name', { exact: true })).toHaveValue('Recoverable')
  const unload = page.waitForEvent('dialog')
  await page.evaluate(() => { setTimeout(() => window.location.reload(), 0) })
  const unloadDialog = await unload
  expect(unloadDialog.type()).toBe('beforeunload')
  await unloadDialog.dismiss()
  await expect(page.getByLabel('Plan name', { exact: true })).toHaveValue('Recoverable')
  await page.evaluate(() => {
    const original = IDBObjectStore.prototype.put
    ;(window as unknown as { restoreWrite: () => void }).restoreWrite = () => { IDBObjectStore.prototype.put = original }
    IDBObjectStore.prototype.put = function (...args) { if (this.name === 'plans') throw new DOMException('Simulated plan disk full', 'QuotaExceededError'); return original.apply(this, args) }
  })
  await button(page, 'Save plan').click()
  await expect(page.getByRole('alert')).toContainText('Simulated plan disk full')
  await expect(page.getByLabel('Plan name', { exact: true })).toHaveValue('Recoverable')
  await expect(days(page)).toHaveCount(2)
  await page.setViewportSize({ width: 320, height: 720 })
  await button(page, 'Save plan').focus()
  await button(page, 'Save plan').scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  const saveBox = await button(page, 'Save plan').boundingBox(), nav = await page.getByRole('navigation', { name: 'Main navigation' }).boundingBox()
  expect(saveBox!.y + saveBox!.height).toBeLessThanOrEqual(nav!.y)
  await page.screenshot({ path: testInfo.outputPath('plan-editor-320.png'), fullPage: true })
  await page.evaluate(() => (window as unknown as { restoreWrite: () => void }).restoreWrite())
  await save(page, 'Recoverable'); await page.reload(); await expect(card(page, 'Recoverable')).toBeVisible()
})

test('stale tabs and another tab profile selection cannot retarget plan input', async ({ page, context }) => {
  await open(page); await libraryExercise(page); await createPlan(page, 'Original')
  const other = await context.newPage(); await open(other)
  await cardAction(other, card(other, 'Original'), 'Edit')
  await other.getByLabel('Plan name', { exact: true }).fill('Stale draft')
  await cardAction(page, card(page, 'Original'), 'Edit')
  await page.getByLabel('Plan name', { exact: true }).fill('Latest'); await save(page, 'Latest')
  await button(other, 'Save plan').click(); await expect(other.getByRole('alert')).toContainText('changed in another tab')
  await expect(other.getByLabel('Plan name', { exact: true })).toHaveValue('Stale draft')
  await cancel(other, true)
  await cardAction(other, card(other, 'Latest'), 'Edit')
  await other.getByLabel('Plan name', { exact: true }).fill('Guest updated')
  await button(page, 'Settings').click(); await createNamedProfile(page, 'Other'); await expect(page.locator('input[name="name"]')).toHaveValue('Other')
  await button(page, 'Light').click(); await button(page, 'Create').click()
  await expect(card(page, 'Latest')).toHaveCount(0)
  await save(other, 'Guest updated')
  await expect(card(page, 'Guest updated')).toHaveCount(0)
  await button(page, 'Create Plan').click(); await days(page).first().getByRole('button', { name: 'Add exercise', exact: true }).click()
  await expect(page.getByText('No matching exercises.')).toBeVisible()
  await button(page, 'Cancel selection').click(); await cancel(page)
  await button(page, 'Settings').click(); await page.getByLabel('Active profile').selectOption({ label: 'Guest' })
  await button(page, 'Create').click(); await expect(card(page, 'Guest updated')).toBeVisible()
})

test('plan name conflicts and archive restoration offer explicit rename recovery', async ({ page }) => {
  await open(page); await libraryExercise(page); await createPlan(page, 'Strength')
  await cardAction(page, card(page, 'Strength'), 'Duplicate')
  await page.getByLabel('Plan name', { exact: true }).fill(' STRENGTH '); await button(page, 'Save plan').click()
  await expect(page.getByRole('alert')).toContainText('already exists')
  await page.getByLabel('Plan name', { exact: true }).fill('Second'); await save(page, 'Second')
  await cardAction(page, card(page, 'Strength'), 'Archive'); await page.getByRole('dialog').getByRole('button', { name: 'Archive', exact: true }).click()
  await createPlan(page, 'Strength')
  await page.getByLabel('Show archived plans').check(); await cardAction(page, card(page, 'Strength').filter({ hasText: 'Archived' }), 'Restore')
  const actions = page.getByRole('dialog', { name: 'Plan actions', exact: true })
  await expect(actions.getByRole('alert')).toContainText('rename an archived plan'); await actions.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('dialog', { name: 'Strength', exact: true }).getByRole('button', { name: 'Close', exact: true }).click()
  await cardAction(page, card(page, 'Strength').filter({ hasText: 'Archived' }), 'Edit')
  await page.getByLabel('Plan name', { exact: true }).fill('Older Strength'); await save(page, 'Older Strength')
  await cardAction(page, card(page, 'Older Strength'), 'Restore')
  await page.getByLabel('Show archived plans').uncheck(); await expect(card(page, 'Older Strength')).toBeVisible()
  await expect(button(page, 'Import')).toBeEnabled()
})
