import { expect, test, type Page } from '@playwright/test'

async function openSettings(page: Page) {
  await page.goto('./')
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Settings', exact: true })).toBeVisible()
  const notice = page.getByRole('button', { name: 'Understood' })
  if (await notice.isVisible()) await notice.click()
}
const nameInput = (page: Page) => page.locator('input[name="name"]')
const save = async (page: Page) => {
  await page.getByRole('button', { name: 'Save profile', exact: true }).click()
  await expect(page.getByText('Profile saved.', { exact: true })).toBeVisible()
}
async function photoFixture(page: Page) {
  const data = await page.evaluate(() => {
    const canvas = document.createElement('canvas')
    canvas.width = 8; canvas.height = 8
    const context = canvas.getContext('2d')!
    context.fillStyle = '#808080'; context.fillRect(0, 0, 8, 8)
    return canvas.toDataURL('image/png').split(',')[1]
  })
  return Buffer.from(data, 'base64')
}

test('Guest conversion, units, avatar, profile switching, and reload persistence', async ({ page }) => {
  await openSettings(page)
  const selection = page.getByLabel('Active profile')
  const guestId = await selection.inputValue()
  await expect(page.getByRole('button', { name: 'Settings', exact: true })).toHaveText('')
  await expect(page.getByRole('button', { name: 'Settings', exact: true })).toHaveAttribute('title', 'Settings')
  await expect(page.getByLabel('Default avatar').first()).toBeVisible()
  await page.getByLabel('Weight (kg, optional)', { exact: true }).fill('70')
  await page.getByLabel('Height (cm, optional)', { exact: true }).fill('177.8')
  await page.getByLabel('Age (optional)').fill('30')
  await save(page)
  await nameInput(page).fill('Ada')
  await page.getByLabel('Profile photo', { exact: true }).setInputFiles({ name: 'avatar.png', mimeType: 'image/png', buffer: await photoFixture(page) })
  await expect(page.locator('.profile-form img')).toBeVisible()
  await save(page)
  await expect(selection).toHaveValue(guestId)
  await page.getByRole('combobox', { name: 'Weight unit', exact: true }).selectOption('lb')
  await page.getByRole('combobox', { name: 'Height unit', exact: true }).selectOption('ft')
  expect(Number(await page.getByLabel('Weight (lb, optional)', { exact: true }).inputValue())).toBeCloseTo(154.323584, 5)
  await expect(page.getByLabel('Height (feet)', { exact: true })).toHaveValue('5')
  await expect(page.getByLabel('Height (inches)', { exact: true })).toHaveValue('10')
  await save(page)
  await page.reload()
  await expect(nameInput(page)).toHaveValue('Ada')
  await expect(page.locator('header .avatar img')).toBeVisible()
  await page.getByLabel('New profile name').fill('Bea')
  await page.getByRole('button', { name: 'Create profile', exact: true }).click()
  await expect(nameInput(page)).toHaveValue('Bea')
  await expect(page.getByLabel('Weight (kg, optional)', { exact: true })).toHaveValue('')
  await expect(page.getByLabel('Age (optional)')).toHaveValue('')
  await expect(page.locator('header .avatar img')).toHaveCount(0)
  await page.getByLabel('Age (optional)').fill('42')
  await save(page)
  await page.reload()
  await expect(nameInput(page)).toHaveValue('Bea')
  await expect(page.getByLabel('Age (optional)')).toHaveValue('42')
  await selection.selectOption({ label: 'Ada' })
  await expect(nameInput(page)).toHaveValue('Ada')
  await expect(page.getByLabel('Age (optional)')).toHaveValue('30')
  await expect(page.locator('header .avatar img')).toBeVisible()
  await page.getByRole('button', { name: 'Remove photo' }).click()
  await save(page)
  await page.reload()
  await expect(page.locator('header .avatar img')).toHaveCount(0)
})

test('theme and approved shell persist across routes; settings navigation is inactive', async ({ page }, testInfo) => {
  await openSettings(page)
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.locator('header')).toHaveCSS('background-color', 'rgb(0, 0, 0)')
  await expect(page.getByRole('navigation')).toHaveCSS('background-color', 'rgb(40, 40, 40)')
  await expect(page.getByText('Ask not for a lighter burden', { exact: true })).toBeVisible()
  await expect(page.getByRole('img', { name: 'Ouroboros: a snake eating its tail' })).toBeVisible()
  await expect(page.locator('nav [aria-current]')).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('settings-dark.png'), fullPage: true })
  await page.getByRole('button', { name: 'Light', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.reload()
  await expect(page.getByRole('button', { name: 'Light', exact: true })).toHaveAttribute('aria-pressed', 'true')
  for (const route of ['Train', 'Create', 'Calendar', 'Progress']) {
    await page.getByRole('button', { name: route, exact: true }).click()
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
    await expect(page.getByRole('main')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  }
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await nameInput(page).fill('A very long profile name that must never push branding outside the viewport')
  await save(page)
  await page.setViewportSize({ width: 320, height: 640 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Save profile', exact: true }).focus()
  const saveBox = await page.getByRole('button', { name: 'Save profile', exact: true }).boundingBox()
  const navBox = await page.getByRole('navigation').boundingBox()
  expect(saveBox!.y + saveBox!.height).toBeLessThanOrEqual(navBox!.y)
  await page.screenshot({ path: testInfo.outputPath('settings-light-320.png'), fullPage: true })
})

test('duplicate names, invalid demographics, and rejected photos preserve input', async ({ page }) => {
  await openSettings(page)
  await page.getByLabel('New profile name').fill('Ada Lovelace')
  await page.getByRole('button', { name: 'Create profile', exact: true }).click()
  await expect(nameInput(page)).toHaveValue('Ada Lovelace')
  await page.getByLabel('New profile name').fill('  ＡDA   LOVELACE ')
  await page.getByRole('button', { name: 'Create profile', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('already exists')
  await page.getByLabel('Age (optional)').fill('-1')
  await page.getByRole('button', { name: 'Save profile', exact: true }).click()
  await expect(page.getByText('Age must be a whole number from 0 to 130, or left blank.')).toBeVisible()
  await expect(page.getByLabel('Age (optional)')).toHaveValue('-1')
  await page.getByLabel('Profile photo', { exact: true }).setInputFiles({ name: 'bad.png', mimeType: 'image/png', buffer: Buffer.from('not an image') })
  await expect(page.getByText('Choose a readable JPEG, PNG, or WebP, up to 5 MB and 4096 pixels per side.')).toBeVisible()
})

test('stale tab cannot overwrite; tab selection cannot retarget another tab draft', async ({ page, context }) => {
  await openSettings(page)
  const other = await context.newPage()
  await openSettings(other)
  await nameInput(other).fill('Unsaved in other tab')
  await nameInput(page).fill('Ada')
  await save(page)
  await other.getByRole('button', { name: 'Save profile', exact: true }).click()
  await expect(other.getByRole('alert')).toContainText('changed in another tab')
  await expect(nameInput(other)).toHaveValue('Unsaved in other tab')
  await page.getByLabel('New profile name').fill('Bea')
  await page.getByRole('button', { name: 'Create profile', exact: true }).click()
  await expect(nameInput(page)).toHaveValue('Bea')
  await expect(other.getByLabel('Active profile')).not.toHaveValue(await page.getByLabel('Active profile').inputValue())
  other.once('dialog', (dialog) => dialog.accept())
  await other.getByRole('button', { name: 'Reload saved profile' }).click()
  await expect(nameInput(other)).toHaveValue('Ada')
  await nameInput(other).fill('Updated Ada')
  await save(other)
  await expect(nameInput(page)).toHaveValue('Bea')
})

test('failed writes retain form input and successful retry persists it', async ({ page }) => {
  await openSettings(page)
  await nameInput(page).fill('Recoverable input')
  await page.evaluate(() => {
    const original = IDBObjectStore.prototype.put
    ;(window as unknown as { restoreWrite: () => void }).restoreWrite = () => { IDBObjectStore.prototype.put = original }
    IDBObjectStore.prototype.put = function (...args) {
      if (this.name === 'profiles') throw new DOMException('Simulated disk full', 'QuotaExceededError')
      return original.apply(this, args)
    }
  })
  await page.getByRole('button', { name: 'Save profile', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Simulated disk full')
  await expect(nameInput(page)).toHaveValue('Recoverable input')
  await expect(page.getByText('Profile saved.', { exact: true })).toHaveCount(0)
  await page.evaluate(() => (window as unknown as { restoreWrite: () => void }).restoreWrite())
  await save(page)
  await page.reload()
  await expect(nameInput(page)).toHaveValue('Recoverable input')
})

test('unavailable IndexedDB shows retry without reporting an empty workspace', async ({ page }) => {
  await page.addInitScript(() => { IDBFactory.prototype.open = () => { throw new DOMException('Storage denied', 'SecurityError') } })
  await page.goto('./')
  await expect(page.getByRole('heading', { name: 'Browser storage unavailable' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Retry storage' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Settings', exact: true })).toHaveCount(0)
})

test('switching with an unsaved form requires confirmation and cannot copy it to another profile', async ({ page }) => {
  await openSettings(page)
  await page.getByLabel('New profile name').fill('Ada')
  await page.getByRole('button', { name: 'Create profile', exact: true }).click()
  await expect(nameInput(page)).toHaveValue('Ada')
  await page.getByLabel('Active profile').selectOption({ label: 'Guest' })
  await expect(nameInput(page)).toHaveValue('')
  await nameInput(page).fill('Uncommitted Guest name')
  page.once('dialog', (dialog) => dialog.dismiss())
  await page.getByLabel('Active profile').selectOption({ label: 'Ada' })
  await expect(nameInput(page)).toHaveValue('Uncommitted Guest name')
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByLabel('Active profile').selectOption({ label: 'Ada' })
  await expect(nameInput(page)).toHaveValue('Ada')
  await page.getByLabel('Age (optional)').fill('25')
  await save(page)
  await page.getByLabel('Active profile').selectOption({ label: 'Guest' })
  await expect(nameInput(page)).toHaveValue('')
  await expect(page.getByLabel('Age (optional)')).toHaveValue('')
})
