import { expect, test, type Page } from '@playwright/test'
import { stagePlan, runPage, manageRun, returnCalendar } from './calendar-actions'

test.setTimeout(90000)
const b = (page: Page, name: string) => page.getByRole('button', { name, exact: true })
const f = (page: Page, name: string) => page.getByLabel(name, { exact: true })
async function rows(page: Page, store: string) { return page.evaluate(async store => { const db = await new Promise<IDBDatabase>(resolve => { const r = indexedDB.open('boros'); r.onsuccess = () => resolve(r.result) }); const rows = await new Promise<any[]>(resolve => { const r = db.transaction(store).objectStore(store).getAll(); r.onsuccess = () => resolve(r.result) }); db.close(); return rows }, store) }
async function setup(page: Page) {
  await page.clock.setFixedTime(new Date('2026-10-05T12:00:00Z')); await page.goto('./'); if (await b(page, 'Understood').isVisible()) await b(page, 'Understood').click()
  await b(page, 'Create').click(); await b(page, 'Imported').click(); await f(page, 'AI output JSON').fill(JSON.stringify({ schemaVersion: 3, kind: 'plan', plan: { name: 'Unified strength', durationWeeks: 4, trainingDaysPerWeek: 2, days: ['Upper', 'Lower'].map(name => ({ name, exercises: [{ name: 'Press', sets: [{ reps: { min: 5, max: 5 } }] }] })) } })); await b(page, 'Validate and preview').click(); await b(page, 'Save plan').click(); await expect(page.getByRole('article', { name: 'Plan Unified strength' })).toBeVisible()
}
test('Calendar activates Train atomically, excludes active template, repairs missing selection, Train schedules same instance', async ({ page, context }) => {
  await setup(page); await b(page, 'Calendar').click(); await b(page, 'Add Plan').click(); await stagePlan(page, 'Unified strength'); expect(await rows(page, 'schedules')).toHaveLength(0); await expect(page.getByText(/Page Save adds/)).toHaveCount(0)
  await b(page, 'Save').click(); await expect(page.getByRole('heading', { level: 1, name: 'Calendar' })).toBeVisible(); const [original] = await rows(page, 'schedules'); expect((await rows(page, 'profiles'))[0].selectedPlanIds).toContain(original.planId)
  await b(page, 'Train').click(); await expect(page.getByRole('article', { name: 'Plan Unified strength' })).toBeVisible(); await b(page, 'Add Plan').click(); await expect(page.getByRole('dialog').getByRole('article')).toHaveCount(0); await b(page, 'Cancel').click()
  await page.evaluate(async () => { const db = await new Promise<IDBDatabase>(resolve => { const r = indexedDB.open('boros'); r.onsuccess = () => resolve(r.result) }); await new Promise<void>(resolve => { const tx = db.transaction('profiles', 'readwrite'), store = tx.objectStore('profiles'), r = store.getAll(); r.onsuccess = () => { const p = r.result[0]; p.selectedPlanIds = []; store.put(p) }; tx.oncomplete = () => resolve() }); db.close() })
  await page.reload(); await expect(page.getByRole('article', { name: 'Plan Unified strength' })).toBeVisible(); expect(await rows(page, 'schedules')).toEqual([original])
  await b(page, 'Calendar').click(); await b(page, 'Add Plan').click(); await expect(page.getByText('No eligible plans', { exact: true })).toBeVisible(); await f(page, 'Search plans').fill('none'); await expect(page.getByText('No plans match this search.')).toBeVisible(); await b(page, 'Cancel').click()
  await manageRun(page, 'End'); await page.getByRole('dialog', { name: 'Ending a Plan?' }).getByRole('button', { name: 'End', exact: true }).click(); await b(page, 'Train').click(); await b(page, 'Add Plan').click(); await page.getByRole('dialog').getByRole('article').getByRole('button').click(); const active = (await rows(page, 'schedules')).find(r => !r.closedAt); expect(active.id).not.toBe(original.id); expect(active.kind).toBe('unscheduled')
  await b(page, 'Calendar').click(); await manageRun(page, 'Edit'); await f(page, 'Upper weekday').selectOption('1'); await f(page, 'Lower weekday').selectOption('3'); await b(page, 'Save').click(); await expect(page.getByRole('heading', { name: 'Current Plans' })).toBeVisible(); expect((await rows(page, 'schedules')).find(r => r.id === active.id).kind).toBeUndefined(); expect(await rows(page, 'schedules')).toHaveLength(2)
  const peer = await context.newPage(); await peer.goto('./'); await b(peer, 'Train').click(); await b(peer, 'Add Plan').click(); await expect(peer.getByRole('dialog').getByRole('article')).toHaveCount(0); await peer.close()
})
test('Month weeks use horizontal columns, default and independent keyboard toggles persist during events, Today expands correctly', async ({ page }, info) => {
  await setup(page); await b(page, 'Calendar').click(); await b(page, 'Add Plan').click(); await stagePlan(page); await b(page, 'Save').click(); await expect(b(page, 'Week 2')).toHaveAttribute('aria-expanded', 'true'); await expect(b(page, 'Week 1')).toHaveAttribute('aria-expanded', String(page.viewportSize()!.width >= 640))
  const week = page.getByRole('region', { name: 'Calendar Week 2' }), days = week.locator('.calendar-day'); await expect(days).toHaveCount(7)
  const boxes = await days.evaluateAll(nodes => nodes.map(node => { const r = node.getBoundingClientRect(); return { x: r.x, y: r.y, bottom: r.bottom } })); expect(new Set(boxes.map(p => p.y)).size).toBe(1); for (let i = 1; i < boxes.length; i++) expect(boxes[i].x).toBeGreaterThan(boxes[i - 1].x)
  if (page.viewportSize()!.width >= 640) await b(page, 'Week 1').click()
  await b(page, 'Week 1').focus(); await page.keyboard.press('Enter'); await expect(b(page, 'Week 1')).toHaveAttribute('aria-expanded', 'true'); await expect(b(page, 'Week 2')).toHaveAttribute('aria-expanded', 'true')
  await b(page, 'Week 2').click(); await expect(days.first()).not.toBeVisible(); await b(page, 'Today').click(); await expect(b(page, 'Week 2')).toHaveAttribute('aria-expanded', 'true'); await expect(b(page, 'Week 1')).toHaveAttribute('aria-expanded', 'true')
  const original = await rows(page, 'schedules'); await runPage(page); await returnCalendar(page); await expect(b(page, 'Week 1')).toHaveAttribute('aria-expanded', 'true'); expect(await rows(page, 'schedules')).toEqual(original)
  await f(page, 'Calendar date').fill('2025-02-15'); await expect(b(page, 'Week 1')).toHaveAttribute('aria-expanded', String(page.viewportSize()!.width >= 640)); await expect(b(page, 'Week 2')).toHaveAttribute('aria-expanded', String(page.viewportSize()!.width >= 640)); await b(page, 'Today').click(); await expect(b(page, 'Week 2')).toHaveAttribute('aria-expanded', 'true')
  await page.setViewportSize({ width: 768, height: 1024 }); await page.screenshot({ path: info.outputPath('month-columns-tablet.png'), fullPage: true }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
test('Create ordering and measured two-row scrolling; shared three-row exercise browsing, tags, themes and large text', async ({ page }, info) => {
  await setup(page); await expect(page.locator('.create-carousel button')).toHaveText(['Plan', 'Workout', 'Exercise']); await expect(page.locator('main h2')).toHaveText(['Plans', 'Workouts', 'Exercises'])
  await page.evaluate(async () => {
    const db = await new Promise<IDBDatabase>(resolve => { const r = indexedDB.open('boros'); r.onsuccess = () => resolve(r.result) })
    const all = (store: string) => new Promise<any[]>(resolve => { const r = db.transaction(store).objectStore(store).getAll(); r.onsuccess = () => resolve(r.result) })
    const [plan] = await all('plans'), [exercise] = await all('exercises'), tagId = crypto.randomUUID()
    await new Promise<void>(resolve => { const tx = db.transaction(['plans', 'exercises', 'tags'], 'readwrite'); tx.objectStore('tags').put({ id: tagId, profileId: plan.profileId, name: 'Strength', nameKey: 'strength', createdAt: plan.createdAt, updatedAt: plan.updatedAt, revision: 1 }); for (let i = 0; i < 15; i++) { tx.objectStore('plans').put({ ...plan, id: crypto.randomUUID(), name: `Plan ${i}`, nameKey: `plan ${i}`, activeNameKey: `plan ${i}` }); tx.objectStore('exercises').put({ ...exercise, id: crypto.randomUUID(), name: `Exercise ${i}`, nameKey: `exercise ${i}`, activeNameKey: `exercise ${i}`, tagIds: i % 2 ? [tagId] : [] }) } tx.oncomplete = () => resolve() }); db.close()
  })
  await page.reload(); const plans = page.getByRole('region', { name: 'Plan catalog' }); await expect(plans.locator('.plan-card')).toHaveCount(16); await expect.poll(() => plans.evaluate(el => el.scrollHeight > el.clientHeight)).toBe(true); await plans.evaluate(el => { el.scrollTop = el.scrollHeight }); expect(await plans.evaluate(el => el.scrollTop)).toBeGreaterThan(0)
  const createCard = await page.locator('.exercise-list').getByRole('button', { name: 'Press', exact: true }).innerText()
  expect(createCard).toMatch(/Added: \d{2}\/\d{2}\/\d{4}/)
  await expect(page.locator('.create-carousel')).toHaveCSS('border-bottom-width', '0px'); await expect(page.locator('.plan-library')).toHaveCSS('border-top-width', '0px')
  const dimensions = await page.locator('.library-filters').evaluateAll(rows => rows.map(row => { const input = row.querySelector('input')!.getBoundingClientRect(), select = row.querySelector('select')!.getBoundingClientRect(), box = row.getBoundingClientRect(); return { inputH: input.height, selectH: select.height, selectW: select.width, aligned: input.bottom === select.bottom, farLeft: input.left === box.left, farRight: select.right === box.right } }))
  expect(dimensions).toHaveLength(3); for (const row of dimensions) expect(row).toEqual({ inputH: 44, selectH: 44, selectW: 132, aligned: true, farLeft: true, farRight: true })
  for (const select of await page.locator('.library-filters select').all()) { await expect(select.locator('option')).toHaveText(['A–Z', 'Z–A', 'Newest', 'Oldest']); await select.selectOption('newest'); expect((await select.boundingBox())!.width).toBe(132) }
  await b(page, 'Progress').click(); const exercises = page.getByRole('region', { name: 'Exercises', exact: true }), grid = page.getByRole('region', { name: 'Overall exercises' }); await expect.poll(() => grid.evaluate(el => el.scrollHeight > el.clientHeight)).toBe(true); await expect(grid).toHaveCSS('grid-template-columns', /\S+ \S+ \S+/)
  expect(await grid.getByRole('button', { name: 'Press', exact: true }).innerText()).toBe(createCard)
  await exercises.getByRole('button', { name: 'Tags', exact: true }).click(); const pill = exercises.getByRole('button', { name: 'Strength', exact: true }), before = await pill.locator('span').boundingBox(); await pill.click(); const after = await pill.locator('span').boundingBox(); expect(after!.width).toBe(before!.width); expect(after!.height).toBe(before!.height); await expect(pill).toHaveCSS('box-shadow', 'none'); await expect(pill).toHaveCSS('border-top-width', '0px'); expect((await pill.boundingBox())!.height).toBeGreaterThanOrEqual(44); const tagRow = exercises.locator('.tag-filter-heading'); expect(await tagRow.evaluate(row => { const buttons = row.querySelectorAll('button'), box = row.getBoundingClientRect(); return Math.abs(buttons[0].getBoundingClientRect().left - box.left) < 1 && Math.abs(buttons[1].getBoundingClientRect().right - box.right) < 1 })).toBe(true); await exercises.getByLabel('Search exercises', { exact: true }).fill('Exercise'); await exercises.getByLabel('Sort exercises', { exact: true }).selectOption('za'); await expect(grid.getByRole('button')).toHaveCount(7); await expect(exercises.getByText('ANY selected tag matches.')).toHaveCount(0); await exercises.getByRole('button', { name: 'Clear', exact: true }).click(); await expect(grid.getByRole('button')).toHaveCount(16)
  await b(page, 'Settings').click(); await b(page, 'Light').click(); await b(page, 'Create').click(); await page.screenshot({ path: info.outputPath('create-order-light.png'), fullPage: true }); await page.setViewportSize({ width: 320, height: 844 }); await page.evaluate(() => { document.documentElement.style.fontSize = '24px' }); await b(page, 'Progress').click(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
