import { expect, test, type Page } from '@playwright/test'
import { cardAction } from './create-actions'
import { createNamedProfile } from './settings-actions'
import { waitForDraft } from './train-actions'
const b=(p:Page,name:string)=>p.getByRole('button',{name,exact:true})
const f=(p:Page,name:string)=>p.getByLabel(name,{exact:true})
const card=(p:Page,name:string)=>p.getByRole('article',{name:`Workout ${name}`,exact:true})
async function records(p:Page,store:string) {return p.evaluate(async store=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('boros');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});try{return await new Promise<any[]>((resolve,reject)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}finally{db.close()}},store)}
async function open(p:Page) {await p.goto('./');if(await b(p,'Understood').isVisible())await b(p,'Understood').click();await b(p,'Create').click();if(await b(p,'Understood').isVisible())await b(p,'Understood').click();await expect(b(p,'Create exercise')).toBeEnabled()}
async function exercise(p:Page) {await b(p,'Imported').click();await f(p,'AI output JSON').fill(JSON.stringify({schemaVersion:5,kind:'exercise',exercise:{name:'Press',sets:[{reps:{min:5,max:8},rir:{min:0,max:0}},{reps:{min:8,max:8}}],restBetweenSetsSeconds:0}}));await b(p,'Validate and preview').click();await b(p,'Save exercise').click();await expect(b(p,'Create workout')).toBeVisible()}
async function add(p:Page) {await p.getByRole('button',{name:/^Add exercise$/i}).click();await b(p,'Add Press').click()}
async function partial(p:Page) {await f(p,'Press occurrence 1 set 1 Weight (kg)').fill('0');await f(p,'Press occurrence 1 set 1 Repetitions').fill('5');await waitForDraft(p)}

test('workout creation, guard, independent plan copies, archive/restore and profile isolation',async({page})=>{
 test.setTimeout(90000);await open(page);await exercise(page)
 await b(page,'Create workout').click();await expect(page.getByRole('heading',{level:1})).toHaveText('Create > Workout');await expect(f(page,'Duration (weeks)')).toHaveCount(0)
 await b(page,'Cancel').click();await expect(page.getByRole('dialog')).toHaveCount(0)
 await b(page,'Create workout').click();await f(page,'Workout name').fill('Upper');await b(page,'Calendar').click();await expect(page.getByRole('dialog')).toHaveAccessibleName('Leaving workout creation');await page.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click()
 await add(page);await add(page);await b(page,'Save workout').click();await expect(card(page,'Upper')).toBeVisible();const saved=(await records(page,'workouts'))[0];expect(saved.exercises).toHaveLength(2)
 await cardAction(page,card(page,'Upper'),'Edit');await f(page,'Instructions').fill('Updated instructions');await b(page,'Save workout').click();await card(page,'Upper').getByRole('button').click();await expect(page.getByRole('dialog')).toContainText('Updated instructions');await b(page,'Close').click()
 await cardAction(page,card(page,'Upper'),'Duplicate');await f(page,'Workout name').fill('Upper copy');await b(page,'Save workout').click();expect((await records(page,'workouts')).find(w=>w.name==='Upper copy').id).not.toBe(saved.id)
 await cardAction(page,card(page,'Upper'),'Archive');await page.getByRole('dialog',{name:'Archive workout?'}).getByRole('button',{name:'Archive',exact:true}).click();await expect(card(page,'Upper')).toHaveCount(0)
 await f(page,'Show archived workouts').check();await cardAction(page,card(page,'Upper'),'Restore');await f(page,'Show archived workouts').uncheck();await expect(card(page,'Upper')).toBeVisible()
 await b(page,'Create Plan').click();await f(page,'Plan name').fill('Copies');await f(page,'Duration (weeks)').fill('2');await b(page,'Add workout').click();await card(page,'Upper').getByRole('button').click();await b(page,'Add workout').click();await card(page,'Upper').getByRole('button').click()
 await page.locator('.plan-day').first().getByRole('button',{name:'Delete workout'}).click();await page.getByRole('dialog').getByRole('button',{name:'Confirm',exact:true}).click();await b(page,'Save plan').click()
 const plan=(await records(page,'plans'))[0];expect(plan.days).toHaveLength(2);expect(plan.days[0].id).not.toBe(plan.days[1].id);expect(plan.days[0].sourceWorkoutId).toBe(saved.id)
 await page.reload();await expect(card(page,'Upper')).toBeVisible();expect((await records(page,'workouts')).find(w=>w.id===saved.id).exercises).toEqual(saved.exercises)
 await b(page,'Settings').click();const owner=await f(page,'Active profile').inputValue();await createNamedProfile(page,'Other');await b(page,'Create').click();await expect(page.getByRole('region',{name:'Workout catalog'}).getByRole('article')).toHaveCount(0);await b(page,'Settings').click();await f(page,'Active profile').selectOption(owner);await b(page,'Create').click();await expect(card(page,'Upper')).toBeVisible()
})

test('custom save Cancel/No/Yes, repeated exercises, reload recovery, calendar nested notes preserve focus and address',async({page})=>{
 test.setTimeout(90000);await open(page);await exercise(page);const address=page.url();await b(page,'Train').click();await expect(page.getByRole('heading',{name:'Active Plans',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:/Saved sessions/})).toHaveCount(0)
 await b(page,'Custom Workout').click();await expect(page.getByRole('heading',{level:1})).toHaveText('Custom Workout');await add(page);await add(page);await partial(page);await page.reload();await page.getByRole('button',{name:/^Resume Workout/}).click();await expect(f(page,'Press occurrence 1 set 1 Weight (kg)')).toHaveValue('0')
 await b(page,'Session Note').click();await f(page,'Note').fill('Historical workout note');await b(page,'Apply note').click();await waitForDraft(page)
 await b(page,'Settings').click();await b(page,'Train').click();await expect(page.getByRole('heading',{level:1})).toHaveText('Custom Workout');await expect(f(page,'Press occurrence 1 set 1 Weight (kg)')).toHaveValue('0')
 await b(page,'Save').click();await b(page,'Save partial session').click();const popup=page.getByRole('dialog',{name:'Saving Completed Workout'});await expect(popup.getByRole('button',{name:'No',exact:true})).toHaveAttribute('aria-pressed','true');await popup.getByRole('button',{name:'Cancel',exact:true}).click();expect(await records(page,'sessions')).toHaveLength(0)
 await b(page,'Save').click();await b(page,'Save partial session').click();await popup.getByRole('button',{name:'Yes',exact:true}).click();await popup.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('region',{name:'Saved session details'})).toBeVisible()
 expect((await records(page,'workouts'))[0].name).toBe('Custom Workout (1)');const session=(await records(page,'sessions'))[0];expect(session.sourcePlanId).toBeUndefined();expect(session.partial).toBe(true)
 await b(page,'Calendar').click();await b(page,'Month').click();const event=page.locator('.calendar-event').filter({hasText:'Custom Workout (1)'});await expect(event).toContainText('Completed');await event.scrollIntoViewIfNeeded();const calendarState=await page.evaluate(()=>({y:scrollY,date:(document.querySelector('input[type=date]') as HTMLInputElement).value,expanded:[...document.querySelectorAll('.calendar-week-section h2 button')].map(b=>b.getAttribute('aria-expanded'))}));await event.click();const review=page.getByRole('dialog',{name:'Completed workout'});await expect(review).toBeVisible();await expect(page.getByRole('heading',{level:1})).toHaveText('Calendar');await review.getByRole('button',{name:'Session Note'}).click();await expect(page.getByRole('dialog',{name:'Session note',exact:true})).toContainText('Historical workout note');await b(page,'Close note').click();await expect(review.getByRole('button',{name:'Session Note'})).toBeFocused();await review.getByRole('button',{name:'Close',exact:true}).click();await expect(event).toBeFocused();expect(await page.evaluate(()=>({y:scrollY,date:(document.querySelector('input[type=date]') as HTMLInputElement).value,expanded:[...document.querySelectorAll('.calendar-week-section h2 button')].map(b=>b.getAttribute('aria-expanded'))}))).toEqual(calendarState);expect(page.url()).toBe(address)
 await b(page,'Train').click();await b(page,'Existing Workout').click();await card(page,'Custom Workout (1)').getByRole('button').click();await expect(page.getByRole('heading',{level:1})).toHaveText('Standalone Workout');await partial(page);await b(page,'Save').click();await b(page,'Save partial session').click();await expect(page.getByRole('region',{name:'Saved session details'})).toBeVisible();expect(await records(page,'workouts')).toHaveLength(1);expect(await records(page,'sessions')).toHaveLength(2)
 await b(page,'Back to workouts').click();await b(page,'Custom Workout').click();await add(page);await f(page,'Press set 1 Weight (kg)').fill('0');await f(page,'Press set 1 Repetitions').fill('8');await waitForDraft(page);await b(page,'Save').click();await b(page,'Save partial session').click();await popup.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('region',{name:'Saved session details'})).toBeVisible();expect(await records(page,'workouts')).toHaveLength(1);expect((await records(page,'sessions')).some(s=>s.day.name==='Custom Workout')).toBe(true)
})


test('v5 workout import, unique-week targeting, stale edits and light mobile layout',async({page,context},info)=>{
 test.setTimeout(60000);await open(page);await b(page,'Settings').click();await b(page,'Light').click();await b(page,'Create').click();await b(page,'Imported').click()
 await f(page,'Formatting instructions for').selectOption('workout');expect(await f(page,'Formatting instructions').inputValue()).toContain('schemaVersion 5')
 await f(page,'AI output JSON').fill(JSON.stringify({schemaVersion:5,kind:'workout',workout:{name:'Circuit',instructions:'Workout instructions',notes:'Template note',supersets:[{number:1,restBetweenRoundsSeconds:0}],exercises:[{name:'A',superset:1,sets:[{reps:{min:5,max:8}},{reps:{min:10,max:10}}]},{name:'A',superset:1,sets:[{reps:{min:12,max:12}}]}]}}));await b(page,'Validate and preview').click();await expect(page.getByRole('heading',{level:1})).toHaveText('Create > Workout');await b(page,'Save workout').click();await expect(card(page,'Circuit')).toBeVisible()
 const source=(await records(page,'workouts'))[0];expect(source.exercises[0].id).not.toBe(source.exercises[1].id);expect(source.exercises[0].templateId).toBe(source.exercises[1].templateId)
 await card(page,'Circuit').getByRole('button').click();await expect(page.getByRole('dialog')).toContainText('Superset 1');await expect(page.getByRole('dialog')).toContainText('Workout instructions');await b(page,'Close').click()
 await b(page,'Create Plan').click();await f(page,'Plan name').fill('Unique copies');await f(page,'Duration (weeks)').fill('4');await page.getByRole('switch',{name:'Unique training weeks?'}).click();await f(page,'Number of Unique weeks').selectOption('2')
 const first=page.getByRole('region',{name:'Week 1',exact:true}),second=page.getByRole('region',{name:'Week 2',exact:true})
 for(const week of [first,second]) {await week.getByRole('button',{name:'Add workout',exact:true}).click();await page.getByRole('dialog',{name:'Workouts',exact:true}).getByLabel('Search workouts',{exact:true}).fill('circ');await page.getByRole('dialog',{name:'Workouts',exact:true}).getByLabel('Sort workouts',{exact:true}).selectOption('newest');await card(page,'Circuit').getByRole('button').click();await week.getByRole('button',{name:'Delete workout',exact:true}).first().click();await page.getByRole('dialog').getByRole('button',{name:'Confirm',exact:true}).click()}
 await b(page,'Save plan').click();const plan=(await records(page,'plans'))[0];expect(plan.weeks).toHaveLength(2);expect(plan.weeks[0].dayIds).toEqual([plan.days[0].id]);expect(plan.weeks[1].dayIds).toEqual([plan.days[1].id]);expect(plan.days[0].groups[0].id).not.toBe(plan.days[1].groups[0].id)
 await cardAction(page,card(page,'Circuit'),'Edit');await f(page,'Workout name').fill('Local unsaved')
 const peer=await context.newPage();await peer.goto('./');await b(peer,'Create').click();await cardAction(peer,card(peer,'Circuit'),'Edit');await f(peer,'Workout name').fill('Peer saved');await b(peer,'Save workout').click();await expect(card(peer,'Peer saved')).toBeVisible();await peer.close()
 await b(page,'Save workout').click();await expect(page.getByRole('alert')).toContainText('another tab');await expect(f(page,'Workout name')).toHaveValue('Local unsaved');await b(page,'Cancel').click();await page.getByRole('dialog').getByRole('button',{name:'Leave',exact:true}).click()
 await expect(card(page,'Peer saved')).toBeVisible();expect((await records(page,'plans'))[0]).toEqual(plan)
 const row=await page.locator('.create-carousel').boundingBox(),imported=await b(page,'Imported').boundingBox();expect(Math.abs(row!.width-imported!.width)).toBeLessThan(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.screenshot({path:info.outputPath('workout-library-light.png'),fullPage:true})
})
