import { Field } from '../../components/ui/Field'
import { RestInput } from '../../components/ui/RestInput'
import { parseRest, restFields, type RestFields } from '../../lib/rest-duration'
import { useState } from 'react'
import { newCircuit, isRepeatCircuit, type Circuit } from '../../schemas/circuit'
import { duplicateDay, type PlanExercise, type TrainingDay } from '../../schemas/plan'

export function CircuitFields({ day, onChange, onPick, onEdit, confirm }: { day: TrainingDay; onChange: (day: TrainingDay) => void; onPick: (circuitId: string) => void; onEdit: (exercise: PlanExercise) => void; confirm: (title: string, action: () => void) => void }) {
  const [rests, setRests] = useState<Record<string, RestFields>>({})
  const circuits = day.circuits ?? []
  const arrange = (list: Circuit[], exercises = day.exercises) => onChange({ ...day, circuits: list, exercises: list.flatMap(c => c.exerciseIds.map(id => exercises.find(e => e.id === id)!)) })
  const update = (id: string, patch: Partial<Circuit>) => arrange(circuits.map(c => c.id === id ? { ...c, ...patch } : c))
  const move = <T,>(list: T[], index: number, offset: number) => { const copy = [...list]; const [item] = copy.splice(index, 1); copy.splice(index + offset, 0, item); return copy }
  return <div className="circuit-builder">{circuits.map((c, i) => <section className="plan-day" key={c.id} aria-label={`Circuit ${i + 1}`} data-circuit-id={c.id}>
    <h4>Circuit {i + 1}</h4><Field label="Circuit name" required value={c.name} maxLength={120} onChange={e => update(c.id, { name: e.target.value })} />
    {isRepeatCircuit(c) && <label>Repeat circuit<select aria-label="Repeat circuit" value={c.repeat} onChange={e => update(c.id, { repeat: Number(e.target.value) })}>{Array.from({ length: 11 }, (_, n) => <option key={n} value={n}>{n}</option>)}</select></label>}
    <RestInput label="Rest after circuit" value={rests[c.id] ?? restFields(c.restAfterCircuitSeconds)} errors={Number.isNaN(c.restAfterCircuitSeconds) ? { seconds: 'Enter a nonnegative duration.' } : c.restAfterCircuitSeconds > 86400 ? { seconds: 'Use at most 86,400 seconds.' } : {}} onChange={value => { setRests(old => ({ ...old, [c.id]: value })); const parsed = parseRest(value); update(c.id, { restAfterCircuitSeconds: Object.keys(parsed.errors).length || parsed.value === undefined ? NaN : parsed.value }) }} />
    <ol className="plan-exercises">{c.exerciseIds.map((id, n) => { const e = day.exercises.find(e => e.id === id)!; return <li key={id} data-occurrence-id={id}><h4>{e.prescription.name}</h4>{e.prescription.trainingType === 'interval' && <p>{e.prescription.activeSeconds}s active · {e.prescription.recoverySeconds}s rest</p>}<div className="actions"><button type="button" onClick={() => onEdit(e)}>Edit</button><button type="button" aria-label="Move exercise up" disabled={!n} onClick={() => update(c.id, { exerciseIds: move(c.exerciseIds, n, -1) })}>↑</button><button type="button" aria-label="Move exercise down" disabled={n === c.exerciseIds.length - 1} onClick={() => update(c.id, { exerciseIds: move(c.exerciseIds, n, 1) })}>↓</button><button type="button" onClick={() => { const copy = duplicateDay({ ...day, circuits: [{ ...c, exerciseIds: [e.id] }], exercises: [e] }).exercises[0]; arrange(circuits.map(item => item.id === c.id ? { ...item, exerciseIds: [...item.exerciseIds.slice(0, n + 1), copy.id, ...item.exerciseIds.slice(n + 1)] } : item), [...day.exercises, copy]) }}>Duplicate</button><button type="button" className="danger" onClick={() => confirm(`Remove ${e.prescription.name}?`, () => update(c.id, { exerciseIds: c.exerciseIds.filter(value => value !== id) }))}>Delete</button></div></li> })}</ol>
    <button type="button" className="plan-add-button" disabled={day.exercises.length >= 100} onClick={() => onPick(c.id)}>Add exercise</button>
    <div className="actions"><button type="button" aria-label="Move circuit up" disabled={!i} onClick={() => arrange(move(circuits, i, -1))}>↑</button><button type="button" aria-label="Move circuit down" disabled={i === circuits.length - 1} onClick={() => arrange(move(circuits, i, 1))}>↓</button><button type="button" onClick={() => { const copy = duplicateDay({ ...day, circuits: [c], exercises: c.exerciseIds.map(id => day.exercises.find(e => e.id === id)!) }); arrange([...circuits.slice(0, i + 1), ...copy.circuits!, ...circuits.slice(i + 1)], [...day.exercises, ...copy.exercises]) }}>Duplicate circuit</button><button type="button" className="danger" disabled={circuits.length === 1} onClick={() => confirm(`Remove ${c.name}?`, () => arrange(circuits.filter(item => item.id !== c.id)))}>Delete circuit</button></div>
  </section>)}<button type="button" className="plan-add-button" onClick={() => arrange([...circuits, newCircuit(circuits.length + 1)])}>Add circuit</button><RestInput label="Post-workout rest" value={rests.workout ?? restFields(day.postWorkoutRestSeconds)} errors={Number.isNaN(day.postWorkoutRestSeconds) ? { seconds: 'Enter a nonnegative duration.' } : (day.postWorkoutRestSeconds ?? 0) > 86400 ? { seconds: 'Use at most 86,400 seconds.' } : {}} onChange={value => { setRests(old => ({ ...old, workout: value })); const parsed = parseRest(value); onChange({ ...day, postWorkoutRestSeconds: Object.keys(parsed.errors).length ? NaN : parsed.value }) }} /></div>
}
