import { expect,test,type Page } from '@playwright/test'
import { createServer } from 'node:http'
import { readFile,stat } from 'node:fs/promises'
import { extname,resolve,sep } from 'node:path'
import { convertIntervalDay } from '../../src/schemas/interval-conversion'
const b=(p:Page,n:string)=>p.getByRole('button',{name:n,exact:true}),f=(p:Page,n:string)=>p.getByLabel(n,{exact:true})
async function records(p:Page){return p.evaluate(async()=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('boros');r.onupgradeneeded=()=>r.transaction!.abort();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});try{const tables:Record<string,any[]>={};for(const name of Array.from(db.objectStoreNames)){tables[name]=await new Promise<any[]>((resolve,reject)=>{const r=db.transaction(name).objectStore(name).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}for(const photo of tables.photos)photo.blob={type:photo.blob.type,bytes:Array.from(new Uint8Array(await photo.blob.arrayBuffer()))};return {version:db.version,tables}}finally{db.close()}})}

test('same context: populated v9 legacy intervals to v10, reopen and a second build preserve all stored identities and photos',async({page:initial,context},info)=>{
 const {stages}=JSON.parse(await readFile('test-results/repeat-update-builds/builds.json','utf8'));let active=stages[0],page=initial
 const mount=info.project.name.startsWith('project-')?'/project-check/':'/',mime:Record<string,string>={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png'}
 const server=createServer(async(req,res)=>{try{const path=decodeURIComponent(new URL(req.url!,'http://localhost').pathname);if(!path.startsWith(mount))throw Error();const file=resolve(active.directory,path.slice(mount.length)||'index.html');if(!file.startsWith(active.directory+sep)||!(await stat(file)).isFile())throw Error();res.writeHead(200,{'Content-Type':mime[extname(file)]??'application/octet-stream','Cache-Control':'no-store','X-Update-Build':active.label});res.end(await readFile(file))}catch{res.writeHead(404);res.end()}})
 await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const address=`http://127.0.0.1:${(server.address() as {port:number}).port}${mount}`
 try{
  await page.goto(address);await b(page,'Settings').click();if(await b(page,'Understood').isVisible())await b(page,'Understood').click();const guest=await f(page,'Active profile').inputValue();await f(page,'Active profile').selectOption('new-profile');await page.locator('input[name="name"]').fill('Repeat migration owner');await b(page,'Save profile').click();await expect(page.locator('input[name="name"]')).toHaveValue('Repeat migration owner');const owner=await f(page,'Active profile').inputValue();await f(page,'Weight (kg, optional)').fill('72.5')
  const photo=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=12;c.getContext('2d')!.fillRect(0,0,12,12);return c.toDataURL().split(',')[1]});await f(page,'Profile photo').setInputFiles({name:'photo.png',mimeType:'image/png',buffer:Buffer.from(photo,'base64')});await b(page,'Save profile').click();await expect(page.getByText('Profile saved.',{exact:true})).toBeVisible();await b(page,'Light').click()
  const day={name:'Legacy timed day',circuits:[{name:'Legacy large circuit',sets:3,roundsPerSet:5,restBetweenSetsSeconds:20,restAfterCircuitSeconds:30,exercises:[{name:'Legacy sprint',activeSeconds:20,recoverySeconds:10}]}],postWorkoutRestSeconds:60}
  await b(page,'Create').click();await b(page,'Import').click();await f(page,'AI output JSON').fill(JSON.stringify({schemaVersion:7,trainingType:'interval',kind:'plan',plan:{mode:'repeating',name:'Legacy timed plan',durationWeeks:4,trainingDaysPerWeek:1,days:[day]}}));await b(page,'Validate and preview').click();await b(page,'Save plan').click();await expect(page.getByRole('article',{name:'Plan Legacy timed plan',exact:true})).toBeVisible()
  await b(page,'Train').click();await b(page,'Add Plan').click();await page.getByRole('dialog').getByRole('article',{name:'Plan Legacy timed plan',exact:true}).getByRole('button').click()
  const start=async()=>{await b(page,'Train').click();if(await page.getByRole('region',{name:'Saved Interval session'}).isVisible())await b(page,'Back').click();await b(page,'Existing Workout').click();await page.getByRole('article',{name:'Workout Legacy timed day',exact:true}).getByRole('button').click();await expect(b(page,'Start')).toBeEnabled();await b(page,'Start').click();await expect(b(page,'Pause')).toBeEnabled();await page.clock.fastForward(12345);await page.waitForTimeout(350);await b(page,'Pause').click();await expect(b(page,'Start')).toBeEnabled()}
  await page.clock.install({time:new Date()});await start();await f(page,'Session Note').fill('Frozen old history');await b(page,'Save').click();await b(page,'Confirm').click();await expect(page.getByRole('region',{name:'Saved Interval session'})).toBeVisible();await start();await f(page,'Session Note').fill('Keep old checkpoint');await b(page,'Settings').click()
  const before=await records(page);expect(before.version).toBe(90);expect(before.tables.sessions).toHaveLength(1);expect(before.tables.drafts.filter(d=>!d.finalizedAt)).toHaveLength(1);expect(before.tables.photos).toHaveLength(1)
  const expected={version:100,tables:{...before.tables,workouts:before.tables.workouts.map(convertIntervalDay),plans:before.tables.plans.map(p=>({...p,days:p.days.map(convertIntervalDay)}))}}
  expect(expected.tables.workouts[0].circuits).toHaveLength(6)
  for(const stage of stages.slice(1)){active=stage;expect((await page.reload())!.headers()['x-update-build']).toBe(stage.label);await expect(f(page,'Active profile')).toHaveValue(owner);expect(await records(page)).toEqual(expected);await expect(page.locator('header .avatar img')).toBeVisible();expect(await page.locator('header .avatar img').evaluate((i:HTMLImageElement)=>i.naturalWidth)).toBeGreaterThan(0);await expect(page.locator('html')).toHaveAttribute('data-theme','light');await page.close();page=await context.newPage();await page.goto(address);await b(page,'Settings').click();await expect(f(page,'Active profile')).toHaveValue(owner);expect(await records(page)).toEqual(expected);expect(page.url()).toBe(address)}
  await f(page,'Active profile').selectOption(guest);await b(page,'Create').click();await expect(page.getByRole('article')).toHaveCount(0);await b(page,'Settings').click();await f(page,'Active profile').selectOption(owner);expect(await records(page)).toEqual(expected)
  await info.attach('repeat-upgrade-receipt.json',{body:JSON.stringify({address,stages,before,after:expected},null,2),contentType:'application/json'})
 }finally{await page.close();await new Promise<void>((resolve,reject)=>server.close(e=>e?reject(e):resolve()))}
})
